#!/bin/bash

cd $HOME

if [ -e $HOME/.gcc_profile ] ; 
then 
    source $HOME/.gcc_profile ;
else
    export NEW_GCC_LIB=/usr/local/lib
    export NEW_GCC_LIB64=/usr/local/lib64
    export LD_LIBRARY_PATH=$NEW_GCC_LIB64:$NEW_GCC_LIB:$LD_LIBRARY_PATH
fi

CRSOP_SCRIPT=$HOME/LiveExec/scripts/call_run_sim_overnight_perdir.pl ;
if [ ! -e $CRSOP_SCRIPT ] ; then 
CRSOP_SCRIPT=$HOME/basetrade_install/scripts/call_run_sim_overnight_perdir.pl ;
fi

#if [ ! -e $HOME/locks/call_run_sim_overnight.lock ] ; then
#touch $HOME/locks/call_run_sim_overnight_recent.lock ;

$CRSOP_SCRIPT HHI_0
$CRSOP_SCRIPT HSI_0
$CRSOP_SCRIPT MHI_0
$CRSOP_SCRIPT MCH_0

$CRSOP_SCRIPT TOPIX_0
$CRSOP_SCRIPT JGBL_0
$CRSOP_SCRIPT NK_0
$CRSOP_SCRIPT NKM_0

$CRSOP_SCRIPT BR_DOL_0
$CRSOP_SCRIPT FGBS_0
$CRSOP_SCRIPT FGBM_0
$CRSOP_SCRIPT FGBL_0
$CRSOP_SCRIPT RI_0
$CRSOP_SCRIPT GD_0

$CRSOP_SCRIPT LFR_0

$CRSOP_SCRIPT ZN_0
$CRSOP_SCRIPT ZB_0

$CRSOP_SCRIPT BR_WIN_0
$CRSOP_SCRIPT DI1F15
$CRSOP_SCRIPT DI1F16
$CRSOP_SCRIPT DI1F17
$CRSOP_SCRIPT DI1F18
$CRSOP_SCRIPT DI1F21
$CRSOP_SCRIPT DI1N14
$CRSOP_SCRIPT DI1N15
$CRSOP_SCRIPT DI1J15

$CRSOP_SCRIPT ZF_0
$CRSOP_SCRIPT UB_0

$CRSOP_SCRIPT FESX_0

$CRSOP_SCRIPT CGB_0
$CRSOP_SCRIPT SXF_0

$CRSOP_SCRIPT KFFTI_0
$CRSOP_SCRIPT JFFCE_0
$CRSOP_SCRIPT LFZ_0

$CRSOP_SCRIPT BR_IND_0
$CRSOP_SCRIPT FBTP_0
$CRSOP_SCRIPT FBTS_0
$CRSOP_SCRIPT FOAT_0

#

$CRSOP_SCRIPT LFI_0
$CRSOP_SCRIPT LFI_1
$CRSOP_SCRIPT LFI_2
$CRSOP_SCRIPT LFI_3
$CRSOP_SCRIPT LFI_4
$CRSOP_SCRIPT LFI_5
$CRSOP_SCRIPT LFI_6

$CRSOP_SCRIPT FDAX_0


#
#$CRSOP_SCRIPT DI1F19
#$CRSOP_SCRIPT DI1F20
#$CRSOP_SCRIPT DI1N16
#$CRSOP_SCRIPT DI1N17
#$CRSOP_SCRIPT BR_DI1N_4
#$CRSOP_SCRIPT BR_DI1N_5
#$CRSOP_SCRIPT BR_DI1G_0
#$CRSOP_SCRIPT BR_DI1G_1
#$CRSOP_SCRIPT BR_DI1G_2
#$CRSOP_SCRIPT DI1J16
#$CRSOP_SCRIPT DI1J17

$CRSOP_SCRIPT YFEBM_1
$CRSOP_SCRIPT XFC_0


#
#$CRSOP_SCRIPT FXXP_0
#$CRSOP_SCRIPT FSTB_0
#$CRSOP_SCRIPT FSMI_0
$CRSOP_SCRIPT FGBX_0
##
$CRSOP_SCRIPT BR_WDO_0
#$CRSOP_SCRIPT ES_0
#$CRSOP_SCRIPT 6A_0
#$CRSOP_SCRIPT 6B_0
#$CRSOP_SCRIPT 6E_0
#$CRSOP_SCRIPT 6J_0
#$CRSOP_SCRIPT 6M_0
#$CRSOP_SCRIPT 6N_0
#$CRSOP_SCRIPT 6S_0
#$CRSOP_SCRIPT CL_0
#$CRSOP_SCRIPT GC_0
#$CRSOP_SCRIPT NQ_0
#$CRSOP_SCRIPT YM_0


#rm -f $HOME/locks/call_run_sim_overnight_recent.lock ;
#else
#    echo "$HOME/locks/call_run_sim_overnight_recent.lock present";
#fi

