/home/dvctrader/basetrade/scripts/move_staged_strats.pl 6A_0 EST_0800-EST_1600 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl 6M_0 BRT_901-EST_1600 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_0 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_1 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_2 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_3 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_4 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_5 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_6 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BAX_7 EST_600-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BOVA11 BRT_1005-BRT_1645 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_0 MSK_1010-MSK_2340 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_DOL_1 BRT_901-BRT_1745 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_IND_0 BRT_1000-BRT_1750 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_IND_0 EST_1230-BRT_1750 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_IND_0 EST_800-BRT_1750 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_IND_0 EST_930-EST_1230 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_WDO_0 BRT_901-BRT_1745 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl BR_WIN_0 BRT_905-BRT_1750 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl CGB_0 EST_730-EST_1530 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1F17 BRT_905-BRT_1540 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1F18 BRT_905-BRT_1540 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1F19 BRT_905-BRT_1540 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1F20 BRT_905-BRT_1540 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1F21 BRT_905-BRT_1540 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1J16 BRT_905-BRT_1540 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1N16 BRT_905-BRT_1540 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1N16 BRT_920-BRT_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl DI1N17 BRT_920-BRT_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ED_0 EST_800-MSK_2340 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ED_0 MSK_1010-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ED_0 MSK_1010-MSK_1350 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ED_0 MSK_1405-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl EUR_RUB__TOD MSK_1000-MSK_1010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl EUR_RUB__TOD MSK_1010-MSK_1445 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl EUR_RUB__TOM MSK_1000-MSK_1010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl EUR_RUB__TOM MSK_1010-MSK_1445 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FBTP_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FBTP_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FBTP_0 EU_HDD /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FBTS_0 CET_815-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FBTS_0 CET_815-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FBTS_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FDAX_0 700-1300 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FDAX_0 CET_1400-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FDAX_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FESX_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FESX_0 EST_800-CET_2100 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FESX_0 HUTS_STRATS /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBL_0 CET_805-CET_855 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBL_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBL_0 EST_800-CET_1900 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBM_0 CET_805-CET_855 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBM_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBM_0 EST_800-CET_1900 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBS_0 CET_805-CET_855 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBS_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBS_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBX_0 CET_900-CET_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBX_0 CET_900-CET_915 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBX_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FGBX_0 EST_800-CET_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FOAT_0 CET_801-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FOAT_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FOAT_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_0 CET_905-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_0 CET_910-CET_2010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_1 CET_905-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_1 CET_910-CET_2010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_1 EST_800-CET_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_2 CET_905-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_2 CET_910-CET_2010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_2 EST_800-CET_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FVS_3 CET_910-CET_2010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FXXP_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl FXXP_0 EST_800-EST_1200 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GD_0 EST_800-MSK_2340 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GD_0 MSK_1010-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GD_0 MSK_1910-MSK_2345 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_10 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_10 EST_700-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_11 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_11 EST_700-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_12 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_12 EST_700-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_2 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_3 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_4 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_5 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_6 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_6 EST_700-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_7 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_7 EST_700-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_8 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_8 EST_700-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_9 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl GE_9 EST_700-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JFFCE_0 CET_805-CET_905 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JFFCE_0 CET_855-CET_905 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JFFCE_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JFFCE_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JGBL_0 EST_700-UTC_1630 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JGBL_0 JST_1235-JST_1445 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JGBL_0 JST_1531-EST_700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JGBL_0 JST_1531-JST_1631 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JGBL_0 JST_1531-UTC_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JGBL_0 JST_905-JST_1045 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JP400_0 JST_1700-UTC_1645 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JP400_0 JST_1700-UTC_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl JP400_0 JST_905-JST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl KFFTI_0 CET_859-CET_905 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl KFFTI_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl KFFTI_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_0 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_1 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_1 EST_700-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_10 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_2 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_2 EST_700-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_3 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_3 EST_700-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_4 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_4 EST_700-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_5 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_5 EST_700-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_6 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_6 EST_700-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_7 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_8 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFI_9 BST_715-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_0 BST_745-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_1 BST_745-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_2 BST_745-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_3 BST_745-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_4 BST_745-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_4 BST_745-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_4 EST_800-BST_1745 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_5 BST_745-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_5 BST_745-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_5 EST_800-BST_1745 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_6 BST_745-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_6 BST_745-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFL_6 EST_800-BST_1745 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFR_0 BST_810-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFR_0 EST_800-BST_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFZ_0 BST_805-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFZ_0 CET_1729-CET_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFZ_0 CET_900-CET_905 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl LFZ_0 EST_800-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl MCH_0 HKT_0920-HKT_1150 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl MHI_0 HKT_1305-HKT_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl MHI_0 HKT_920-HKT_1155 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl MX_0 MSK_1010-MSK_2340 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NIY_0 EST_800-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NIY_0 EST_800-UTC_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NIY_0 JST_1035-JST_1300 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NIY_0 JST_1300-JST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NIY_0 JST_1700-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NIY_0 JST_1710-UTC_1750 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NK_0 EST_800-UTC_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NK_0 JST_1035-JST_1300 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NK_0 JST_1700-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NK_0 JST_905-JST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKD_0 EST_800-UTC_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKD_0 JST_1035-JST_1300 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKD_0 JST_1300-JST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKD_0 JST_1700-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKD_0 JST_1710-UTC_1750 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKM_0 EST_800-UTC_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKM_0 JST_1700-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKM_0 JST_1730-UTC_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKMF_0 EST_800-UTC_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKMF_0 JST_1700-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NKMF_0 JST_905-JST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NSE_USDINR_FUT0 IST_902-IST_1658 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl NSE_USDINR_FUT0 IST_932-IST_1528 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl RI_0 EST_800-MSK_2340 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl RI_0 MSK_1000-MSK_1010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl RI_0 MSK_1010-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl Si_0 EST_800-MSK_1840 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl Si_0 MSK_1000-MSK_1010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl Si_0 MSK_1010-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl Si_0 MSK_1905-MSK_2340 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SP_VX0_VX1 EST_300-EST_930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SP_VX0_VX1 EST_915-EST_1613 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SP_VX1_VX2 EST_300-EST_930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SP_VX1_VX2 EST_915-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SP_VX2_VX3 EST_915-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SR_0 MSK_1010-MSK_1830 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SXF_0 EST_930-EST_945 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl SXF_0 EST_945-EST_1559 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl TOPIX_0 EST_800-UTC_1730 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl TOPIX_0 HKT_935-HKT_1155 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl TOPIX_0 JST_1645-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl TOPIX_0 JST_905-JST_1500 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl UB_0 EST_330-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl UB_0 EST_830-EST_1600 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl UB_0 UTC_0015-UTC_0555 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl USD000000TOD EST_800-MSK_1700 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl USD000000TOD MSK_1000-MSK_1010 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl USD000000TOD MSK_1010-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl USD000UTSTOM EST_800-MSK_1840 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl USD000UTSTOM MSK_1010-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl USD000UTSTOM MSK_1905-MSK_2340 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_0 EST_1550-EST_1614 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_0 EST_300-EST_930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_0 EST_915-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_1 EST_1550-EST_1614 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_1 EST_1600-EST_1615 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_1 EST_300-EST_900 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_1 EST_915-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_2 EST_1550-EST_1614 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_2 EST_1600-EST_1615 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_2 EST_300-EST_900 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_2 EST_915-EST_1600 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_2 EST_915-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_3 EST_1550-EST_1614 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_3 EST_300-EST_915 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_3 EST_915-EST_1600 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_3 EST_915-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl VX_4 EST_915-EST_1605 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl AP_0 AST_1715-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl AP_0 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl AP_0 EST_800-UTC_1930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl XT_0 AST_1715-EST_0755 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl XT_0 AST_1715-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl XT_0 AST_845-AST_1615 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl XT_0 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl XT_0 EST_800-UTC_1930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_0 CET_1045-CET_1100 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_0 CET_1100-EST_930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_0 EST_930-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_1 CET_1045-CET_1100 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_1 CET_1100-EST_930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_1 EST_930-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_2 CET_1045-CET_1100 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_2 CET_1100-EST_930 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YFEBM_2 EST_930-CET_1800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl YT_0 CET_800-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZB_0 EST_330-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZB_0 EST_830-EST_1600 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZB_0 UTC_0015-UTC_0555 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZF_0 EST_330-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZF_0 EST_830-EST_1545 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZF_0 PREV_UTC_2305-UTC_0015 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZF_0 UTC_0015-UTC_0555 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZN_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZN_0 EST_330-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZN_0 EST_830-EST_1600 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZN_0 PREV_UTC_2305-UTC_0015 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZN_0 UTC_0015-UTC_0555 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZT_0 CET_900-EST_800 /home/dvctrader/move_staged_configs/config.default.txt
/home/dvctrader/basetrade/scripts/move_staged_strats.pl ZT_0 EST_800-EST_1500 /home/dvctrader/move_staged_configs/config.default.txt
