import sys
import subprocess
import os

### this function basically finds what all params have been permuted. Basically sees which param line has more than 3 tokens
def get_permuted_params( filename ):
    f = open( filename, "r" )
    output = []
    for line in f:
        temp = line.split( " " )
        if len ( temp ) > 3 and temp[1]!= "TRADEINDICATOR":
            output.append( temp[1] )
    return output

### this function gets the value of the params that have been permuted in the specific strat. Used to tabulate the final result.
def get_permuted_params_value( filename, permuted_params ):
    params = [line.rstrip('\n') for line in open( filename )]
    current = 0
    output = []
    for i in params:
        temp = i.split( " " )
        if len(temp) < 2:
            print(temp)
        elif len(permuted_params) <= current:
            break
        elif permuted_params[current] == temp[1]:
            output.append(temp[2])
            current = current + 1
    return output

if len(sys.argv) != 7:
    print("USAGE: " + sys.argv[0] + " stratfile paramfile start_date end_date algo data_output_dir")
    exit()

Strat = sys.argv[1]
Param = sys.argv[2]
Start_Date = sys.argv[3]
End_Date = sys.argv[4]
Algo = sys.argv[5]
Work_Dir = sys.argv[6]

permuted_params = get_permuted_params( Param )

### run the parallel param permute command. 
permute_param_cmd = "~/basetrade/ModelScripts/parllel_params_permute.pl -p " + Param + " -s " + Strat + " -sd " + Start_Date + " -ed " + End_Date + " > " + Work_Dir + "/output_permute_param"
os.system( permute_param_cmd )

### fetch the directory in which param permtue results are outputted
directory = [line.rstrip('\n') for line in open(Work_Dir+"/output_permute_param")][0].split( " " )[2]
print(directory)

### summarize results and get results for each strat generated by parllel param permute cmd. Further write the results in a file.
summarise_results_cmd = "~/basetrade_install/bin/summarize_local_results_dir_and_choose_by_algo kCNAPnlMaxLoss 4000 4000 -1 1 5000 100000 " + directory + "/local_results_base_dir | grep ST > " + Work_Dir + "/summarise"
print(summarise_results_cmd)
os.system( summarise_results_cmd )

### Now starts the tabulation part. Fetch the summarized results that have been written in file. 
contents = [line.rstrip('\n') for line in open(Work_Dir+"/summarise")]

### I have only fetched Pnl, Sharpe, MaxLoss and Volume column. More columns can be added if someone wants.
output = []
output.append( permuted_params + [ "PnL", "Sharpe", "MaxLoss", "Volume" ] )
for i in contents:
    temp = i.split( " " )
    if temp[0] == "STRATEGYFILEBASE":
        stratfile = directory + "/strats_dir/" + temp[1]
        stratcontents = [line.strip('\n') for line in open( stratfile )]
        param_file = stratcontents[0].split(" ")[4]
        params = get_permuted_params_value( param_file, permuted_params )
    elif temp[0] == "STATISTICS":
        param_output = [ temp[1], temp[4], temp[22], temp[3] ]
        output.append( params + param_output )

### Tabular format output generation
for line in output:
    for element in line:
        sys.stdout.write(element)
        sys.stdout.write('\t')
    sys.stdout.write('\n')

