~/basetrade/scripts/set_live_exec_new.sh aflash_decode_category
~/basetrade/scripts/set_live_exec_new.sh af_print_xmlspecs
~/basetrade/scripts/set_live_exec_new.sh af_save_estimates_fx
~/basetrade/scripts/set_live_exec_new.sh af_save_mdslogs_fx
~/basetrade/scripts/set_live_exec_new.sh all_exchanges_volume_reconciliation
~/basetrade/scripts/set_live_exec_new.sh all_volumes_on_day
~/basetrade/scripts/set_live_exec_new.sh all_volumes_on_day_new_handler
~/basetrade/scripts/set_live_exec_new.sh analyse_strategy_results
~/basetrade/scripts/set_live_exec_new.sh aws_job_scheduler
~/basetrade/scripts/set_live_exec_new.sh AWSScheduler
~/basetrade/scripts/set_live_exec_new.sh bandwidth_monitor
~/basetrade/scripts/set_live_exec_new.sh calc_na_adjusted_covariance_matrix
~/basetrade/scripts/set_live_exec_new.sh calc_next_day
~/basetrade/scripts/set_live_exec_new.sh calc_next_week_day
~/basetrade/scripts/set_live_exec_new.sh calc_prev_day
~/basetrade/scripts/set_live_exec_new.sh calc_prev_week_day
~/basetrade/scripts/set_live_exec_new.sh calculate_median_delay_per_day
~/basetrade/scripts/set_live_exec_new.sh callFSHDVLR
~/basetrade/scripts/set_live_exec_new.sh callFSHDVLRbackpass
~/basetrade/scripts/set_live_exec_new.sh callFSHLR
~/basetrade/scripts/set_live_exec_new.sh call_fslogr
~/basetrade/scripts/set_live_exec_new.sh callFSLR
~/basetrade/scripts/set_live_exec_new.sh callFSLRbackpass
~/basetrade/scripts/set_live_exec_new.sh callFSLR_inef
~/basetrade/scripts/set_live_exec_new.sh callFSLRnomem
~/basetrade/scripts/set_live_exec_new.sh callFSRLM
~/basetrade/scripts/set_live_exec_new.sh callfsr_mean_fss_corr
~/basetrade/scripts/set_live_exec_new.sh callfsr_mean_sharpe_corr
~/basetrade/scripts/set_live_exec_new.sh callFSRR
~/basetrade/scripts/set_live_exec_new.sh callfsr_sharpe_rsq
~/basetrade/scripts/set_live_exec_new.sh callFSVLR
~/basetrade/scripts/set_live_exec_new.sh callMARS
~/basetrade/scripts/set_live_exec_new.sh call_multiple_fslr
~/basetrade/scripts/set_live_exec_new.sh call_pca_reg
~/basetrade/scripts/set_live_exec_new.sh callPCAREG
~/basetrade/scripts/set_live_exec_new.sh check_indicator_data
~/basetrade/scripts/set_live_exec_new.sh check_product_data
~/basetrade/scripts/set_live_exec_new.sh check_samplefeatures_presence
~/basetrade/scripts/set_live_exec_new.sh choose_strategy_set_by_algo
~/basetrade/scripts/set_live_exec_new.sh clip_outliers
~/basetrade/scripts/set_live_exec_new.sh closed_form_lr
~/basetrade/scripts/set_live_exec_new.sh closed_form_rr
~/basetrade/scripts/set_live_exec_new.sh collect_features
~/basetrade/scripts/set_live_exec_new.sh collect_features_samples
~/basetrade/scripts/set_live_exec_new.sh collect_shortcodes_from_model
~/basetrade/scripts/set_live_exec_new.sh compute_pca_coefficients
~/basetrade/scripts/set_live_exec_new.sh compute_realized_volatility
~/basetrade/scripts/set_live_exec_new.sh controlscreen
~/basetrade/scripts/set_live_exec_new.sh daily_trade_aggregator
~/basetrade/scripts/set_live_exec_new.sh datagen
~/basetrade/scripts/set_live_exec_new.sh dump_raw_multicast_data_using_config
~/basetrade/scripts/set_live_exec_new.sh economic_events_of_the_day
~/basetrade/scripts/set_live_exec_new.sh exchange_simulator
~/basetrade/scripts/set_live_exec_new.sh exchange_symbol_vomapper
~/basetrade/scripts/set_live_exec_new.sh filter_indicators
~/basetrade/scripts/set_live_exec_new.sh fix_bin_reader
~/basetrade/scripts/set_live_exec_new.sh GC_volume_reader
~/basetrade/scripts/set_live_exec_new.sh generate_bardata
~/basetrade/scripts/set_live_exec_new.sh generate_ors_conf_mktdata_delays_stats
~/basetrade/scripts/set_live_exec_new.sh generate_ors_mktdata_delays_stats
~/basetrade/scripts/set_live_exec_new.sh generate_price_data
~/basetrade/scripts/set_live_exec_new.sh generate_sec_data
~/basetrade/scripts/set_live_exec_new.sh get_all_mds_stats_for_day
~/basetrade/scripts/set_live_exec_new.sh get_all_securities
~/basetrade/scripts/set_live_exec_new.sh get_avg_l1ord_on_day
~/basetrade/scripts/set_live_exec_new.sh get_avg_l1sz_on_day
~/basetrade/scripts/set_live_exec_new.sh get_avg_l1sz_on_day_using_mds_data
~/basetrade/scripts/set_live_exec_new.sh get_avg_spread_on_day
~/basetrade/scripts/set_live_exec_new.sh get_avg_volume_for_shortcode
~/basetrade/scripts/set_live_exec_new.sh get_contract_specs
~/basetrade/scripts/set_live_exec_new.sh get_correlation_matrix
~/basetrade/scripts/set_live_exec_new.sh get_covariance_matrix
~/basetrade/scripts/set_live_exec_new.sh get_cxl_rejection_periods
~/basetrade/scripts/set_live_exec_new.sh get_cxl_seqd_to_conf
~/basetrade/scripts/set_live_exec_new.sh get_data_verification_stats
~/basetrade/scripts/set_live_exec_new.sh get_dep_corr
~/basetrade/scripts/set_live_exec_new.sh get_dep_median_corr
~/basetrade/scripts/set_live_exec_new.sh get_di_dv01
~/basetrade/scripts/set_live_exec_new.sh get_di_numbers_to_dollars
~/basetrade/scripts/set_live_exec_new.sh get_di_pnl
~/basetrade/scripts/set_live_exec_new.sh get_di_pos_for_risk
~/basetrade/scripts/set_live_exec_new.sh get_di_term
~/basetrade/scripts/set_live_exec_new.sh get_dv01_for_shortcode
~/basetrade/scripts/set_live_exec_new.sh get_economic_events_of_the_day_for_shortcode
~/basetrade/scripts/set_live_exec_new.sh get_eurex_product_expiry
~/basetrade/scripts/set_live_exec_new.sh get_exchanges
~/basetrade/scripts/set_live_exec_new.sh get_exchange_symbol
~/basetrade/scripts/set_live_exec_new.sh get_exch_from_shortcode
~/basetrade/scripts/set_live_exec_new.sh get_expiry_nse
~/basetrade/scripts/set_live_exec_new.sh get_fillratio_for_shortcode_by_saci
~/basetrade/scripts/set_live_exec_new.sh get_l1events_on_day
~/basetrade/scripts/set_live_exec_new.sh get_l1events_on_day_using_mds_data
~/basetrade/scripts/set_live_exec_new.sh get_latency_stats
~/basetrade/scripts/set_live_exec_new.sh get_mfm_from_utc_time
~/basetrade/scripts/set_live_exec_new.sh get_min_price_increment
~/basetrade/scripts/set_live_exec_new.sh get_msecs_from_midnight
~/basetrade/scripts/set_live_exec_new.sh get_nse_spl_days
~/basetrade/scripts/set_live_exec_new.sh get_numbers_to_dollars
~/basetrade/scripts/set_live_exec_new.sh get_num_trades_on_day
~/basetrade/scripts/set_live_exec_new.sh get_option_greeks
~/basetrade/scripts/set_live_exec_new.sh get_options
~/basetrade/scripts/set_live_exec_new.sh get_option_shortcodes
~/basetrade/scripts/set_live_exec_new.sh get_our_presence_in_market_stats
~/basetrade/scripts/set_live_exec_new.sh get_path
~/basetrade/scripts/set_live_exec_new.sh get_periodic_l1events_on_day
~/basetrade/scripts/set_live_exec_new.sh get_periodic_numtrades_on_day
~/basetrade/scripts/set_live_exec_new.sh get_periodic_price_stdev_on_day
~/basetrade/scripts/set_live_exec_new.sh get_periodic_price_stdev_on_day_V1
~/basetrade/scripts/set_live_exec_new.sh get_periodic_trades_on_day
~/basetrade/scripts/set_live_exec_new.sh get_periodic_volume_on_day
~/basetrade/scripts/set_live_exec_new.sh get_periodic_volume_on_day_utc
~/basetrade/scripts/set_live_exec_new.sh get_pnl_for_shortcode_bytime_stats
~/basetrade/scripts/set_live_exec_new.sh get_price_info_for_day
~/basetrade/scripts/set_live_exec_new.sh get_rejection_periods
~/basetrade/scripts/set_live_exec_new.sh get_rep_matrix
~/basetrade/scripts/set_live_exec_new.sh get_seqd_to_conf
~/basetrade/scripts/set_live_exec_new.sh get_shortcode_expiry_date
~/basetrade/scripts/set_live_exec_new.sh get_shortcode_for_symbol
~/basetrade/scripts/set_live_exec_new.sh get_sim_config_description_from_file
~/basetrade/scripts/set_live_exec_new.sh get_stdev_correlation_matrix
~/basetrade/scripts/set_live_exec_new.sh get_term
~/basetrade/scripts/set_live_exec_new.sh get_timeavg_l1sz_on_day
~/basetrade/scripts/set_live_exec_new.sh get_trades_within_time_frame
~/basetrade/scripts/set_live_exec_new.sh get_utc_hhmmss_str
~/basetrade/scripts/set_live_exec_new.sh get_utc_hhmm_str
~/basetrade/scripts/set_live_exec_new.sh get_UTS_for_a_day
~/basetrade/scripts/set_live_exec_new.sh get_volume_on_day
~/basetrade/scripts/set_live_exec_new.sh get_volume_on_day_2
~/basetrade/scripts/set_live_exec_new.sh holiday_manager
~/basetrade/scripts/set_live_exec_new.sh indicator_price_printer
~/basetrade/scripts/set_live_exec_new.sh kalman_exec
~/basetrade/scripts/set_live_exec_new.sh l1_data_generator
~/basetrade/scripts/set_live_exec_new.sh lin_mod
~/basetrade/scripts/set_live_exec_new.sh make_indicator_list
~/basetrade/scripts/set_live_exec_new.sh make_indicator_list_extended
~/basetrade/scripts/set_live_exec_new.sh mcast_bw_simple_tool
~/basetrade/scripts/set_live_exec_new.sh mcast_status_logger
~/basetrade/scripts/set_live_exec_new.sh md_simulator
~/basetrade/scripts/set_live_exec_new.sh mds_log_bcaster
~/basetrade/scripts/set_live_exec_new.sh mds_log_l1_trade
~/basetrade/scripts/set_live_exec_new.sh mds_log_reader
~/basetrade/scripts/set_live_exec_new.sh mkt_book_viewer
~/basetrade/scripts/set_live_exec_new.sh mkt_trade_logger
~/basetrade/scripts/set_live_exec_new.sh notional_to_uts_nse
~/basetrade/scripts/set_live_exec_new.sh nse_opt_mkt_info
~/basetrade/scripts/set_live_exec_new.sh nse_simple_trader_sim
~/basetrade/scripts/set_live_exec_new.sh option_details
~/basetrade/scripts/set_live_exec_new.sh option_volume_check
~/basetrade/scripts/set_live_exec_new.sh ors_binary_reader
~/basetrade/scripts/set_live_exec_new.sh ors_binary_reader_from_file
~/basetrade/scripts/set_live_exec_new.sh ors_delay_calc
~/basetrade/scripts/set_live_exec_new.sh ors_delay_calc_new
~/basetrade/scripts/set_live_exec_new.sh our_extended_bidask_mkt_book_util
~/basetrade/scripts/set_live_exec_new.sh our_extended_bidask_mkt_book_util_options
~/basetrade/scripts/set_live_exec_new.sh p2y
~/basetrade/scripts/set_live_exec_new.sh pca
~/basetrade/scripts/set_live_exec_new.sh pinv
~/basetrade/scripts/set_live_exec_new.sh price_diff
~/basetrade/scripts/set_live_exec_new.sh price_diff_new
~/basetrade/scripts/set_live_exec_new.sh print_lrdb_values
~/basetrade/scripts/set_live_exec_new.sh print_moving_correlation_for_day
~/basetrade/scripts/set_live_exec_new.sh print_paramset
~/basetrade/scripts/set_live_exec_new.sh print_queue_pos
~/basetrade/scripts/set_live_exec_new.sh print_scaled_volume_for_day
~/basetrade/scripts/set_live_exec_new.sh print_trend_mean_reversion_ind_for_day
~/basetrade/scripts/set_live_exec_new.sh print_volume_ratio_for_day
~/basetrade/scripts/set_live_exec_new.sh production_risk_manager
~/basetrade/scripts/set_live_exec_new.sh quantile_filter
~/basetrade/scripts/set_live_exec_new.sh quantile_summary
~/basetrade/scripts/set_live_exec_new.sh read_feature
~/basetrade/scripts/set_live_exec_new.sh realign_to_quantiles
~/basetrade/scripts/set_live_exec_new.sh remove_indicators_from_model
~/basetrade/scripts/set_live_exec_new.sh remove_mean_reg_data
~/basetrade/scripts/set_live_exec_new.sh remove_outliers
~/basetrade/scripts/set_live_exec_new.sh retail_logger
~/basetrade/scripts/set_live_exec_new.sh retrieve_eurex_MatDat
~/basetrade/scripts/set_live_exec_new.sh retrieve_eurex_trades
~/basetrade/scripts/set_live_exec_new.sh retrieve_eurex_trades_v1
~/basetrade/scripts/set_live_exec_new.sh risk_control
~/basetrade/scripts/set_live_exec_new.sh risk_monitor_client
~/basetrade/scripts/set_live_exec_new.sh run_tests
~/basetrade/scripts/set_live_exec_new.sh scale_reg_data_udm
~/basetrade/scripts/set_live_exec_new.sh search_exec
~/basetrade/scripts/set_live_exec_new.sh sim_ors_binary_reader
~/basetrade/scripts/set_live_exec_new.sh sim_real_packet_order_mismatch_detector
~/basetrade/scripts/set_live_exec_new.sh sim_strategy
~/basetrade/scripts/set_live_exec_new.sh sim_strategy_mb
~/basetrade/scripts/set_live_exec_new.sh sim_strategy_options
~/basetrade/scripts/set_live_exec_new.sh split_cme_logged_message_file
~/basetrade/scripts/set_live_exec_new.sh split_eurex_logged_message_file
~/basetrade/scripts/set_live_exec_new.sh spread_exec
~/basetrade/scripts/set_live_exec_new.sh summarize_single_strategy_results
~/basetrade/scripts/set_live_exec_new.sh summarize_strategy_results
~/basetrade/scripts/set_live_exec_new.sh summarize_local_results_and_choose_by_algo_extended_checks
~/basetrade/scripts/set_live_exec_new.sh summarize_local_results_by_timeperiod
~/basetrade/scripts/set_live_exec_new.sh summarize_local_results_dir_and_choose_by_algo
~/basetrade/scripts/set_live_exec_new.sh symbol_driver_main
~/basetrade/scripts/set_live_exec_new.sh test_implied_volatility
~/basetrade/scripts/set_live_exec_new.sh time_converter
~/basetrade/scripts/set_live_exec_new.sh timed_data_to_corr_record
~/basetrade/scripts/set_live_exec_new.sh timed_data_to_multiple_reg_data
~/basetrade/scripts/set_live_exec_new.sh timed_data_to_reg_data
~/basetrade/scripts/set_live_exec_new.sh timed_data_to_reg_data_bd
~/basetrade/scripts/set_live_exec_new.sh timed_data_to_stats_record
~/basetrade/scripts/set_live_exec_new.sh update_date
~/basetrade/scripts/set_live_exec_new.sh user_msg
~/basetrade/scripts/set_live_exec_new.sh volume_monitor
#~/basetrade/scripts/set_live_exec_new.sh tradeinit

mkdir -p ~/LiveExec/ModelScripts/

cp -v ~/basetrade/ModelScripts/generate_strategies.pl ~/LiveExec/ModelScripts/

HOSTNAME=`hostname -s`;
if [ $HOSTNAME = "sdv-ny4-srv11" ] ; then 
    find $HOME/LiveExec -type f \( -iname "*.~*" ! -iname "sim_strategy*" ! -iname "datagen*" \) -atime +50 -exec rm {} \;
else
    find $HOME/LiveExec -name *~ -type f -atime +30 -exec rm -f {} \;
fi
