// =====================================================================================
//
//       Filename:  nse_tbt_templates.hpp
//
//    Description:  This is a template class derived from API, used to make decoding scalable for future changes,
//                  since just adjusting fields will automatically adjust new offsets
//                  This also allows us to directly access required elements without defining packed structs
//                  as boundaries are not comptible with word alignment
//
//        Version:  1.0
//        Created:  09/17/2015 06:48:37 PM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#define NSE_TBT_DATA_START_OFFSET 0

#define NSE_BCAST_TRADE_RANGE_TRANS_CODE 7220

// MESSAGE TYPES

#define HEARTBEAT_MESSAGE_TYPE 'Z'

#define MASTER_DATA_HEADER_MESSAGE_TYPE 'B'
#define MASTER_DATA_CONTRACT_SPEC_MESSAGE_TYPE 'C'
#define MASTER_DATA_SPREAD_CONTRACT_SPEC_MESSAGE_TYPE 'P'
#define MASTER_DATA_TRAILER_MESSAGE_TYPE 'E'

#define ORDER_MESSAGE_TYPE_NEW 'N'
#define ORDER_MESSAGE_TYPE_MODIFY 'M'
#define ORDER_MESSAGE_TYPE_DELETE 'X'
#define TRADE_MESSAGE_TYPE_TRADE 'T'

#define SPREAD_ORDER_MESSAGE_TYPE_NEW 'G'
#define SPREAD_ORDER_MESSAGE_TYPE_MODIFY 'H'
#define SPREAD_ORDER_MESSAGE_TYPE_DELETE 'J'
#define SPREAD_TRADE_MESSAGE_TYPE_TRADE 'K'

// HEARTBEAT

#define NSE_TBT_DATA_HEARTBEAT_LAST_SEQUENCE_NUMBER_OFFSET \
  (NSE_TBT_DATA_MESSAGE_TYPE_OFFSET + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)
#define NSE_TBT_DATA_HEARTBEAT_LAST_SEQUENCE_NUMBER_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_HEARTBEAT_MESSAGE_LENGTH \
  (NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH + NSE_TBT_DATA_HEARTBEAT_LAST_SEQUENCE_NUMBER_LENGTH)

// MASTER INFO HEADER

#define NSE_TBT_DATA_MASTER_INFO_HEADER_TOKEN_COUNT_OFFSET \
  (NSE_TBT_DATA_MESSAGE_TYPE_OFFSET + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)
#define NSE_TBT_DATA_MASTER_INFO_HEADER_TOKEN_COUNT_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_MASTER_INFO_HEADER_MESSAGE_LENGTH \
  (NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH + NSE_TBT_DATA_MASTER_INFO_HEADER_TOKEN_COUNT_LENGTH)

// MASTER INFO CONTRCT SPEC

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_STREAM_ID_OFFSET \
  (NSE_TBT_DATA_MESSAGE_TYPE_OFFSET + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)
#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_STREAM_ID_LENGTH sizeof(int16_t)

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_TOKEN_NUMBER_OFFSET \
  (NSE_TBT_DATA_MASTER_CONTRACT_INFO_STREAM_ID_OFFSET + NSE_TBT_DATA_MASTER_CONTRACT_INFO_STREAM_ID_LENGTH)
#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_TOKEN_NUMBER_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_INSTRUMENT_OFFSET \
  (NSE_TBT_DATA_MASTER_CONTRACT_INFO_TOKEN_NUMBER_OFFSET + NSE_TBT_DATA_MASTER_CONTRACT_INFO_TOKEN_NUMBER_LENGTH)
#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_INSTRUMENT_LENGTH 6

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_SYMBOL_OFFSET \
  (NSE_TBT_DATA_MASTER_CONTRACT_INFO_INSTRUMENT_OFFSET + NSE_TBT_DATA_MASTER_CONTRACT_INFO_INSTRUMENT_LENGTH)
#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_SYMBOL_LENGTH 10

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_EXPIRY_DATE_OFFSET \
  (NSE_TBT_DATA_MASTER_CONTRACT_INFO_SYMBOL_OFFSET + NSE_TBT_DATA_MASTER_CONTRACT_INFO_SYMBOL_LENGTH)
#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_EXPIRY_DATE_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_STRIKE_PRICE_OFFSET \
  (NSE_TBT_DATA_MASTER_CONTRACT_INFO_EXPIRY_DATE_OFFSET + NSE_TBT_DATA_MASTER_CONTRACT_INFO_EXPIRY_DATE_LENGTH)
#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_STRIKE_PRICE_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_OPTION_TYPE_OFFSET \
  (NSE_TBT_DATA_MASTER_CONTRACT_INFO_STRIKE_PRICE_OFFSET + NSE_TBT_DATA_MASTER_CONTRACT_INFO_STRIKE_PRICE_LENGTH)
#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_OPTION_TYPE_LENGTH 2

#define NSE_TBT_DATA_MASTER_CONTRACT_INFO_MESSAGE_LENGTH                                                         \
  (NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH + NSE_TBT_DATA_MASTER_CONTRACT_INFO_STREAM_ID_LENGTH +    \
   NSE_TBT_DATA_MASTER_CONTRACT_INFO_TOKEN_NUMBER_LENGTH + NSE_TBT_DATA_MASTER_CONTRACT_INFO_INSTRUMENT_LENGTH + \
   NSE_TBT_DATA_MASTER_CONTRACT_INFO_SYMBOL_LENGTH + NSE_TBT_DATA_MASTER_CONTRACT_INFO_EXPIRY_DATE_LENGTH +      \
   NSE_TBT_DATA_MASTER_CONTRACT_INFO_STRIKE_PRICE_LENGTH + NSE_TBT_DATA_MASTER_CONTRACT_INFO_OPTION_TYPE_LENGTH)

// MASTER INFO SPREAD CONTRACT SPEC

#define NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_STREAM_ID_OFFSET \
  (NSE_TBT_DATA_MESSAGE_TYPE_OFFSET + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)
#define NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_STREAM_ID_LENGTH sizeof(int16_t)

#define NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN1_OFFSET \
  (NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_STREAM_ID_OFFSET + \
   NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_STREAM_ID_LENGTH)
#define NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN1_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN2_OFFSET \
  (NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN1_OFFSET + NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN1_LENGTH)
#define NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN2_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_HEADER_LENGTH                                                       \
  (NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH + NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_STREAM_ID_LENGTH + \
   NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN1_LENGTH + NSE_TBT_DATA_MASTER_SPREAD_CONTRACT_INFO_TOKEN2_LENGTH)

// MASTER INFO TRAILER MESSAGE

#define NSE_TBT_DATA_MASTER_TRAILER_TOKEN_COUNT_OFFSET \
  (NSE_TBT_DATA_MESSAGE_TYPE_OFFSET + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)
#define NSE_TBT_DATA_MASTER_TRAILER_TOKEN_COUNT_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_MASTER_TRAILER_MESSAGE_LENGTH \
  (NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH + NSE_TBT_DATA_MASTER_TRAILER_TOKEN_COUNT_LENGTH)
// HEADER RELATED INFO

#define NSE_TBT_DATA_HEADER_MSGLENGTH_OFFSET NSE_TBT_DATA_START_OFFSET
#define NSE_TBT_DATA_HEADER_MSGLENGTH_LENGTH sizeof(int16_t)

#define NSE_TBT_DATA_HEADER_STREAMID_OFFSET \
  (NSE_TBT_DATA_HEADER_MSGLENGTH_OFFSET + NSE_TBT_DATA_HEADER_MSGLENGTH_LENGTH)
#define NSE_TBT_DATA_HEADER_STREAMID_LENGTH sizeof(int16_t)

#define NSE_TBT_DATA_HEADER_SEQUENCE_NUMBER_OFFSET \
  (NSE_TBT_DATA_HEADER_STREAMID_OFFSET + NSE_TBT_DATA_HEADER_STREAMID_LENGTH)
#define NSE_TBT_DATA_HEADER_SEQUENCE_NUMBER_LENGTH sizeof(int32_t)

// MESSAGE TYPE INFO

#define NSE_TBT_DATA_MESSAGE_TYPE_OFFSET \
  (NSE_TBT_DATA_HEADER_SEQUENCE_NUMBER_OFFSET + NSE_TBT_DATA_HEADER_SEQUENCE_NUMBER_LENGTH)
#define NSE_TBT_DATA_MESSAGE_TYPE_LENGTH sizeof(char)

// HEADER and MESSAGE TYPE COMMON LENGTH

#define NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH                     \
  (NSE_TBT_DATA_HEADER_MSGLENGTH_LENGTH + NSE_TBT_DATA_HEADER_STREAMID_LENGTH + \
   NSE_TBT_DATA_HEADER_SEQUENCE_NUMBER_LENGTH + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)

// ORDER MESSAGE INFO

#define NSE_TBT_DATA_ORDER_MESSAGE_TIMESTAMP_OFFSET \
  (NSE_TBT_DATA_MESSAGE_TYPE_OFFSET + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)
#define NSE_TBT_DATA_ORDER_MESSAGE_TIMESTAMP_LENGTH sizeof(uint64_t)

#define NSE_TBT_DATA_ORDER_MESSAGE_ORDERID_OFFSET \
  (NSE_TBT_DATA_ORDER_MESSAGE_TIMESTAMP_OFFSET + NSE_TBT_DATA_ORDER_MESSAGE_TIMESTAMP_LENGTH)
#define NSE_TBT_DATA_ORDER_MESSAGE_ORDERID_LENGTH \
  sizeof(double)  // Specs says it's double but we interpret it as uint64_t everyplace except this one

#define NSE_TBT_DATA_ORDER_MESSAGE_TOKEN_OFFSET \
  (NSE_TBT_DATA_ORDER_MESSAGE_ORDERID_OFFSET + NSE_TBT_DATA_ORDER_MESSAGE_ORDERID_LENGTH)
#define NSE_TBT_DATA_ORDER_MESSAGE_TOKEN_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_ORDER_MESSAGE_ORDERTYPE_OFFSET \
  (NSE_TBT_DATA_ORDER_MESSAGE_TOKEN_OFFSET + NSE_TBT_DATA_ORDER_MESSAGE_TOKEN_LENGTH)
#define NSE_TBT_DATA_ORDER_MESSAGE_ORDERTYPE_LENGTH sizeof(char)

#define NSE_TBT_DATA_ORDER_MESSAGE_PRICE_OFFSET \
  (NSE_TBT_DATA_ORDER_MESSAGE_ORDERTYPE_OFFSET + NSE_TBT_DATA_ORDER_MESSAGE_ORDERTYPE_LENGTH)
#define NSE_TBT_DATA_ORDER_MESSAGE_PRICE_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_ORDER_MESSAGE_QUANTITY_OFFSET \
  (NSE_TBT_DATA_ORDER_MESSAGE_PRICE_OFFSET + NSE_TBT_DATA_ORDER_MESSAGE_PRICE_LENGTH)
#define NSE_TBT_DATA_ORDER_MESSAGE_QUANTITY_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_ORDER_MESSAGE_LENGTH                                                              \
  (NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH + NSE_TBT_DATA_ORDER_MESSAGE_TIMESTAMP_LENGTH + \
   NSE_TBT_DATA_ORDER_MESSAGE_ORDERID_LENGTH + NSE_TBT_DATA_ORDER_MESSAGE_TOKEN_LENGTH +               \
   NSE_TBT_DATA_ORDER_MESSAGE_ORDERTYPE_LENGTH + NSE_TBT_DATA_ORDER_MESSAGE_PRICE_LENGTH +             \
   NSE_TBT_DATA_ORDER_MESSAGE_QUANTITY_LENGTH)

// TRADE MESSAGE INFO

#define NSE_TBT_DATA_MESSAGE_TYPE_OFFSET \
  (NSE_TBT_DATA_HEADER_SEQUENCE_NUMBER_OFFSET + NSE_TBT_DATA_HEADER_SEQUENCE_NUMBER_LENGTH)
#define NSE_TBT_DATA_MESSAGE_TYPE_LENGTH sizeof(char)

#define NSE_TBT_DATA_TRADE_MESSAGE_TIMESTAMP_OFFSET \
  (NSE_TBT_DATA_MESSAGE_TYPE_OFFSET + NSE_TBT_DATA_MESSAGE_TYPE_LENGTH)
#define NSE_TBT_DATA_TRADE_MESSAGE_TIMESTAMP_LENGTH sizeof(uint64_t)

#define NSE_TBT_DATA_TRADE_MESSAGE_BUYORDERID_OFFSET \
  (NSE_TBT_DATA_TRADE_MESSAGE_TIMESTAMP_OFFSET + NSE_TBT_DATA_TRADE_MESSAGE_TIMESTAMP_LENGTH)
#define NSE_TBT_DATA_TRADE_MESSAGE_BUYORDERID_LENGTH sizeof(double)

#define NSE_TBT_DATA_TRADE_MESSAGE_SELLORDERID_OFFSET \
  (NSE_TBT_DATA_TRADE_MESSAGE_BUYORDERID_OFFSET + NSE_TBT_DATA_TRADE_MESSAGE_BUYORDERID_LENGTH)
#define NSE_TBT_DATA_TRADE_MESSAGE_SELLORDERID_LENGTH sizeof(double)

#define NSE_TBT_DATA_TRADE_MESSAGE_TOKEN_OFFSET \
  (NSE_TBT_DATA_TRADE_MESSAGE_SELLORDERID_OFFSET + NSE_TBT_DATA_TRADE_MESSAGE_SELLORDERID_LENGTH)
#define NSE_TBT_DATA_TRADE_MESSAGE_TOKEN_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_TRADE_MESSAGE_TRADEPRICE_OFFSET \
  (NSE_TBT_DATA_TRADE_MESSAGE_TOKEN_OFFSET + NSE_TBT_DATA_TRADE_MESSAGE_TOKEN_LENGTH)
#define NSE_TBT_DATA_TRADE_MESSAGE_TRADEPRICE_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_TRADE_MESSAGE_TRADEQUANTITY_OFFSET \
  (NSE_TBT_DATA_TRADE_MESSAGE_TRADEPRICE_OFFSET + NSE_TBT_DATA_TRADE_MESSAGE_TRADEPRICE_LENGTH)
#define NSE_TBT_DATA_TRADE_MESSAGE_TRADEQUANTITY_LENGTH sizeof(int32_t)

#define NSE_TBT_DATA_TRADE_MESSAGE_LENGTH                                                              \
  (NSE_TBT_DATA_MESSAGE_HEADER_AND_MESSAGE_TYPE_LENGTH + NSE_TBT_DATA_TRADE_MESSAGE_TIMESTAMP_LENGTH + \
   NSE_TBT_DATA_TRADE_MESSAGE_BUYORDERID_LENGTH + NSE_TBT_DATA_TRADE_MESSAGE_SELLORDERID_LENGTH +      \
   NSE_TBT_DATA_TRADE_MESSAGE_TOKEN_LENGTH + NSE_TBT_DATA_TRADE_MESSAGE_TRADEPRICE_LENGTH +            \
   NSE_TBT_DATA_TRADE_MESSAGE_TRADEQUANTITY_LENGTH)
