#ifndef _BSE_MDS_SHM_INTERFACE_DEFINES_HPP_
#define _BSE_MDS_SHM_INTERFACE_DEFINES_HPP_

#define BSE_MDS_QUEUE_SIZE 131072
#define BSE_MDS_QUEUE_SIZE_LAG_THRESHOLD 117964
#define BSE_MDS_SHM_KEY 9117

#endif
