#ifndef _NSE_MDS_SHM_INTERFACE_DEFINES_HPP_
#define _NSE_MDS_SHM_INTERFACE_DEFINES_HPP_

#define NSE_MDS_QUEUE_SIZE 131072
#define NSE_MDS_QUEUE_SIZE_LAG_THRESHOLD 117964
#define NSE_MDS_SHM_KEY 9116

#endif
