// =====================================================================================
//
//       Filename:  LogonResponseDerivatives.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/29/2015 05:47:46 AM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/LogonResponse.hpp"

#define NSE_LOGON_RESPONSE_USERID_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_LOGON_RESPONSE_USERID_LENGTH sizeof(int32_t)

#define NSE_LOGON_RESPONSE_STP_RESERVED1_OFFSET (NSE_LOGON_RESPONSE_USERID_OFFSET + NSE_LOGON_RESPONSE_USERID_LENGTH)
#define NSE_LOGON_RESPONSE_STP_RESERVED1_LENGTH 8

#define NSE_LOGON_RESPONSE_PASSWORD_OFFSET (NSE_LOGON_RESPONSE_STP_RESERVED1_OFFSET+NSE_LOGON_RESPONSE_STP_RESERVED1_LENGTH)
#define NSE_LOGON_RESPONSE_PASSWORD_LENGTH LENGTH_OF_LOGON_RESPONSE_PASSWORD_CHAR_FIELD

#define NSE_LOGON_RESPONSE_STP_RESERVED2_OFFSET (NSE_LOGON_RESPONSE_PASSWORD_OFFSET+NSE_LOGON_RESPONSE_PASSWORD_LENGTH)
#define NSE_LOGON_RESPONSE_STP_RESERVED2_LENGTH 8

#define NSE_LOGON_RESPONSE_NEWPASSWORD_OFFSET (NSE_LOGON_RESPONSE_STP_RESERVED2_OFFSET+NSE_LOGON_RESPONSE_STP_RESERVED2_LENGTH)
#define NSE_LOGON_RESPONSE_NEWPASSWORD_LENGTH LENGTH_OF_LOGON_RESPONSE_PASSWORD_CHAR_FIELD

#define NSE_LOGON_RESPONSE_TRADERNAME_OFFSET \
  (NSE_LOGON_RESPONSE_NEWPASSWORD_OFFSET + NSE_LOGON_RESPONSE_NEWPASSWORD_LENGTH)
#define NSE_LOGON_RESPONSE_TRADERNAME_LENGTH LENGTH_OF_LOGON_RESPONSE_TRADERNAME_CHAR_FIELD

#define NSE_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_OFFSET \
  (NSE_LOGON_RESPONSE_TRADERNAME_OFFSET + NSE_LOGON_RESPONSE_TRADERNAME_LENGTH)
#define NSE_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_LENGTH sizeof(int32_t)

#define NSE_LOGON_RESPONSE_BROKERID_OFFSET \
  (NSE_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_OFFSET + NSE_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_LENGTH)
#define NSE_LOGON_RESPONSE_BROKERID_LENGTH LENGTH_OF_LOGON_RESPONSE_BROKERID_CHAR_FIELD

#define NSE_LOGON_RESPONSE_RESERVED_1_OFFSET (NSE_LOGON_RESPONSE_BROKERID_OFFSET + NSE_LOGON_RESPONSE_BROKERID_LENGTH)
#define NSE_LOGON_RESPONSE_RESERVED_1_LENGTH sizeof(char)

#define NSE_LOGON_RESPONSE_BRANCHID_OFFSET (NSE_LOGON_RESPONSE_RESERVED_1_OFFSET + NSE_LOGON_RESPONSE_RESERVED_1_LENGTH)
#define NSE_LOGON_RESPONSE_BRANCHID_LENGTH sizeof(int16_t)

#define NSE_LOGON_RESPONSE_VERSIONNUMBER_OFFSET \
  (NSE_LOGON_RESPONSE_BRANCHID_OFFSET + NSE_LOGON_RESPONSE_BRANCHID_LENGTH)
#define NSE_LOGON_RESPONSE_VERSIONNUMBER_LENGTH sizeof(int32_t)

#define NSE_LOGON_RESPONSE_BATCH2STARTTIME_OFFSET \
  (NSE_LOGON_RESPONSE_VERSIONNUMBER_OFFSET + NSE_LOGON_RESPONSE_VERSIONNUMBER_LENGTH)
#define NSE_LOGON_RESPONSE_BATCH2STARTTIME_LENGTH sizeof(int32_t)

#define NSE_LOGON_RESPONSE_HOSTSWITCHCONTEXT_OFFSET \
  (NSE_LOGON_RESPONSE_BATCH2STARTTIME_OFFSET + NSE_LOGON_RESPONSE_BATCH2STARTTIME_LENGTH)
#define NSE_LOGON_RESPONSE_HOSTSWITCHCONTEXT_LENGTH sizeof(char)

#define NSE_LOGON_RESPONSE_COLOUR_OFFSET \
  (NSE_LOGON_RESPONSE_HOSTSWITCHCONTEXT_OFFSET + NSE_LOGON_RESPONSE_HOSTSWITCHCONTEXT_LENGTH)
#define NSE_LOGON_RESPONSE_COLOUR_LENGTH LENGTH_OF_LOGON_RESPONSE_COLOUR_CHAR_FIELD

#define NSE_LOGON_RESPONSE_RESERVED_2_OFFSET (NSE_LOGON_RESPONSE_COLOUR_OFFSET + NSE_LOGON_RESPONSE_COLOUR_LENGTH)
#define NSE_LOGON_RESPONSE_RESERVED_2_LENGTH sizeof(char)

#define NSE_LOGON_RESPONSE_USERTYPE_OFFSET (NSE_LOGON_RESPONSE_RESERVED_2_OFFSET + NSE_LOGON_RESPONSE_RESERVED_2_LENGTH)
#define NSE_LOGON_RESPONSE_USERTYPE_LENGTH sizeof(int16_t)

#define NSE_LOGON_RESPONSE_SEQUENCENUMBER_OFFSET \
  (NSE_LOGON_RESPONSE_USERTYPE_OFFSET + NSE_LOGON_RESPONSE_USERTYPE_LENGTH)
#define NSE_LOGON_RESPONSE_SEQUENCENUMBER_LENGTH sizeof(double)

#define NSE_LOGON_RESPONSE_WSCLASSNAME_OFFSET \
  (NSE_LOGON_RESPONSE_SEQUENCENUMBER_OFFSET + NSE_LOGON_RESPONSE_SEQUENCENUMBER_LENGTH)
#define NSE_LOGON_RESPONSE_WSCLASSNAME_LENGTH LENGTH_OF_LOGON_RESPONSE_WSCLASSNAME_CHAR_FIELD

#define NSE_LOGON_RESPONSE_BROKERSTATUS_OFFSET \
  (NSE_LOGON_RESPONSE_WSCLASSNAME_OFFSET + NSE_LOGON_RESPONSE_WSCLASSNAME_LENGTH)
#define NSE_LOGON_RESPONSE_BROKERSTATUS_LENGTH sizeof(char)

#define NSE_LOGON_RESPONSE_SHOWINDEX_OFFSET \
  (NSE_LOGON_RESPONSE_BROKERSTATUS_OFFSET + NSE_LOGON_RESPONSE_BROKERSTATUS_LENGTH)
#define NSE_LOGON_RESPONSE_SHOWINDEX_LENGTH sizeof(char)

#define NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_OFFSET \
  (NSE_LOGON_RESPONSE_SHOWINDEX_OFFSET + NSE_LOGON_RESPONSE_SHOWINDEX_LENGTH)
#define NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH sizeof(int8_t)

#define NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_OFFSET \
  (NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_OFFSET +    \
   NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH)
#define NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH sizeof(int8_t)

#define NSE_LOGON_RESPONSE_MEMBERTYPE_OFFSET                           \
  (NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_OFFSET + \
   NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH)
#define NSE_LOGON_RESPONSE_MEMBERTYPE_LENGTH sizeof(int16_t)

#define NSE_LOGON_RESPONSE_CLEARING_STATUS_OFFSET \
  (NSE_LOGON_RESPONSE_MEMBERTYPE_OFFSET + NSE_LOGON_RESPONSE_MEMBERTYPE_LENGTH)
#define NSE_LOGON_RESPONSE_CLEARING_STATUS_LENGTH sizeof(char)

#define NSE_LOGON_RESPONSE_BROKERNAME_OFFSET \
  (NSE_LOGON_RESPONSE_CLEARING_STATUS_OFFSET + NSE_LOGON_RESPONSE_CLEARING_STATUS_LENGTH)
#define NSE_LOGON_RESPONSE_BROKERNAME_LENGTH LENGTH_OF_LOGON_RESPONSE_BROKERNAME_CHAR_FIELD

#define NSE_LOGON_RESPONSE_STP_RESERVED_GROUP_OFFSET (NSE_LOGON_RESPONSE_BROKERNAME_OFFSET+NSE_LOGON_RESPONSE_BROKERNAME_LENGTH)
#define NSE_LOGON_RESPONSE_STP_RESERVED_GROUP_LENGTH 48

#define NSE_LOGON_RESPONSE_LENGTH                                                                                   \
  (NSE_LOGON_RESPONSE_USERID_LENGTH + NSE_LOGON_RESPONSE_PASSWORD_LENGTH + NSE_LOGON_RESPONSE_NEWPASSWORD_LENGTH +  \
   NSE_LOGON_RESPONSE_TRADERNAME_LENGTH + NSE_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_LENGTH +                        \
   NSE_LOGON_RESPONSE_BROKERID_LENGTH + NSE_LOGON_RESPONSE_RESERVED_1_LENGTH + NSE_LOGON_RESPONSE_BRANCHID_LENGTH + \
   NSE_LOGON_RESPONSE_VERSIONNUMBER_LENGTH + NSE_LOGON_RESPONSE_BATCH2STARTTIME_LENGTH +                            \
   NSE_LOGON_RESPONSE_HOSTSWITCHCONTEXT_LENGTH + NSE_LOGON_RESPONSE_COLOUR_LENGTH +                                 \
   NSE_LOGON_RESPONSE_RESERVED_2_LENGTH + NSE_LOGON_RESPONSE_USERTYPE_LENGTH +                                      \
   NSE_LOGON_RESPONSE_SEQUENCENUMBER_LENGTH + NSE_LOGON_RESPONSE_WSCLASSNAME_LENGTH +                               \
   NSE_LOGON_RESPONSE_BROKERSTATUS_LENGTH + NSE_LOGON_RESPONSE_SHOWINDEX_LENGTH +                                   \
   NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH +                                              \
   NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH + NSE_LOGON_RESPONSE_MEMBERTYPE_LENGTH +       \
   NSE_LOGON_RESPONSE_CLEARING_STATUS_LENGTH + NSE_LOGON_RESPONSE_BROKERNAME_LENGTH +                               \
   NSE_LOGON_RESPONSE_STP_RESERVED1_LENGTH + NSE_LOGON_RESPONSE_STP_RESERVED2_LENGTH + NSE_LOGON_RESPONSE_STP_RESERVED_GROUP_LENGTH)

// Logon Msgs : received on login failure if error code in header is nonzero
#define NSE_LOGON_RESPONSE_ERROR_MSG_OFFSET 14
#define NSE_LOGON_RESPONSE_ERROR_MSG_LENGTH 128

namespace HFSAT {
namespace NSE {

class NSELogonResponseDerivatives : public NSELogonResponse {
 public:
  NSELogonResponseDerivatives() {}

  inline ProcessedLogonResponse *ProcessLogon(char const *msg_ptr) {
    processed_logon_response_.user_id = ntoh32(*((int32_t *)(msg_ptr + NSE_LOGON_RESPONSE_USERID_OFFSET)));

    memcpy((void *)processed_logon_response_.trader_name, (void *)(msg_ptr + NSE_LOGON_RESPONSE_TRADERNAME_OFFSET),
           NSE_LOGON_RESPONSE_TRADERNAME_LENGTH);

    processed_logon_response_.last_password_changed_date_time =
        ntoh32(*((int32_t *)(msg_ptr + NSE_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_OFFSET)));

    memcpy((void *)processed_logon_response_.broker_id, (void *)(msg_ptr + NSE_LOGON_RESPONSE_BROKERID_OFFSET),
           NSE_LOGON_RESPONSE_BROKERID_LENGTH);

    processed_logon_response_.branch_id = ntoh16(*((int16_t *)(msg_ptr + NSE_LOGON_RESPONSE_BRANCHID_OFFSET)));
    processed_logon_response_.end_time = ntoh32(*((int32_t *)(msg_ptr + NSE_LOGON_RESPONSE_BATCH2STARTTIME_OFFSET)));
    processed_logon_response_.user_type = ntoh16(*((int16_t *)(msg_ptr + NSE_LOGON_RESPONSE_USERTYPE_OFFSET)));
    processed_logon_response_.sequence_number = *((double *)(msg_ptr + NSE_LOGON_RESPONSE_SEQUENCENUMBER_OFFSET));
    processed_logon_response_.broker_status = *((char *)(msg_ptr + NSE_LOGON_RESPONSE_BROKERSTATUS_OFFSET));

    processed_logon_response_.broker_eligibility_per_mkt =
        ntoh16(*((int16_t *)(msg_ptr + NSE_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_OFFSET)));

    processed_logon_response_.member_type = ntoh16(*((int16_t *)(msg_ptr + NSE_LOGON_RESPONSE_MEMBERTYPE_OFFSET)));
    processed_logon_response_.clearing_status = *((char *)(msg_ptr + NSE_LOGON_RESPONSE_CLEARING_STATUS_OFFSET));

    memcpy((void *)processed_logon_response_.broker_name, (void *)(msg_ptr + NSE_LOGON_RESPONSE_BROKERNAME_OFFSET),
           NSE_LOGON_RESPONSE_BROKERNAME_LENGTH);

    return &processed_logon_response_;
  }

  int32_t GetLogonErrorMsgLength() { return NSE_LOGON_RESPONSE_ERROR_MSG_LENGTH; }
  int32_t GetLogonErrorMsgOffset() { return NSE_LOGON_RESPONSE_ERROR_MSG_OFFSET; }
};
}
}
