// =====================================================================================
//
//       Filename:  OrderEntry.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/29/2015 11:11:05 PM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/OrderResponses.hpp"

#define NSE_ORDER_RESPONSE_TRANSACTIONCODE_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_ORDER_RESPONSE_TRANSACTIONCODE_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_LOGTIME_OFFSET \
  (NSE_ORDER_RESPONSE_TRANSACTIONCODE_OFFSET + NSE_ORDER_RESPONSE_TRANSACTIONCODE_LENGTH)
#define NSE_ORDER_RESPONSE_LOGTIME_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_USERID_OFFSET (NSE_ORDER_RESPONSE_LOGTIME_OFFSET + NSE_ORDER_RESPONSE_LOGTIME_LENGTH)
#define NSE_ORDER_RESPONSE_USERID_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_ERRORCODE_OFFSET (NSE_ORDER_RESPONSE_USERID_OFFSET + NSE_ORDER_RESPONSE_USERID_LENGTH)
#define NSE_ORDER_RESPONSE_ERRORCODE_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_TIMESTAMP1_OFFSET (NSE_ORDER_RESPONSE_ERRORCODE_OFFSET + NSE_ORDER_RESPONSE_ERRORCODE_LENGTH)
#define NSE_ORDER_RESPONSE_TIMESTAMP1_LENGTH sizeof(double)

#define NSE_ORDER_RESPONSE_TIMESTAMP2_OFFSET \
  (NSE_ORDER_RESPONSE_TIMESTAMP1_OFFSET + NSE_ORDER_RESPONSE_TIMESTAMP1_LENGTH)
#define NSE_ORDER_RESPONSE_TIMESTAMP2_LENGTH sizeof(char)

#define NSE_ORDER_RESPONSE_MOD_CAN_BY_OFFSET \
  (NSE_ORDER_RESPONSE_TIMESTAMP2_OFFSET + NSE_ORDER_RESPONSE_TIMESTAMP2_LENGTH)
#define NSE_ORDER_RESPONSE_MOD_CAN_BY_LENGTH sizeof(char)

#define NSE_ORDER_RESPONSE_REASONCODE_OFFSET \
  (NSE_ORDER_RESPONSE_MOD_CAN_BY_OFFSET + NSE_ORDER_RESPONSE_MOD_CAN_BY_LENGTH)
#define NSE_ORDER_RESPONSE_REASONCODE_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_TOKENNO_OFFSET (NSE_ORDER_RESPONSE_REASONCODE_OFFSET + NSE_ORDER_RESPONSE_REASONCODE_LENGTH)
#define NSE_ORDER_RESPONSE_TOKENNO_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET \
  (NSE_ORDER_RESPONSE_TOKENNO_OFFSET + NSE_ORDER_RESPONSE_TOKENNO_LENGTH)
#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH \
  LENGTH_OF_NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_CHAR_FIELD

#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET      \
  (NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET + \
   NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH)
#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH \
  LENGTH_OF_NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_CHAR_FIELD

#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET \
  (NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET + NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH)
#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET \
  (NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET +     \
   NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH)
#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET \
  (NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET +   \
   NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH)
#define NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH 2

#define NSE_ORDER_RESPONSE_CLOSEOUTFLAG_OFFSET                 \
  (NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET + \
   NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH)
#define NSE_ORDER_RESPONSE_CLOSEOUTFLAG_LENGTH sizeof(char)

#define NSE_ORDER_RESPONSE_PAD_OFFSET (NSE_ORDER_RESPONSE_CLOSEOUTFLAG_OFFSET + NSE_ORDER_RESPONSE_CLOSEOUTFLAG_LENGTH)
#define NSE_ORDER_RESPONSE_PAD_LENGTH sizeof(char)

#define NSE_ORDER_RESPONSE_ORDERNUMBER_OFFSET (NSE_ORDER_RESPONSE_PAD_OFFSET + NSE_ORDER_RESPONSE_PAD_LENGTH)
#define NSE_ORDER_RESPONSE_ORDERNUMBER_LENGTH sizeof(double)

#define NSE_ORDER_RESPONSE_ACCOUNTNUMBER_OFFSET \
  (NSE_ORDER_RESPONSE_ORDERNUMBER_OFFSET + NSE_ORDER_RESPONSE_ORDERNUMBER_LENGTH)
#define NSE_ORDER_RESPONSE_ACCOUNTNUMBER_LENGTH LENGTH_OF_NSE_ORDER_RESPONSE_ACCOUNTNUMBER_CHAR_FIELD

#define NSE_ORDER_RESPONSE_BOOKTYPE_OFFSET \
  (NSE_ORDER_RESPONSE_ACCOUNTNUMBER_OFFSET + NSE_ORDER_RESPONSE_ACCOUNTNUMBER_LENGTH)
#define NSE_ORDER_RESPONSE_BOOKTYPE_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_BUYSELLINDICATOR_OFFSET \
  (NSE_ORDER_RESPONSE_BOOKTYPE_OFFSET + NSE_ORDER_RESPONSE_BOOKTYPE_LENGTH)
#define NSE_ORDER_RESPONSE_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_DISCLOSEDVOLUME_OFFSET \
  (NSE_ORDER_RESPONSE_BUYSELLINDICATOR_OFFSET + NSE_ORDER_RESPONSE_BUYSELLINDICATOR_LENGTH)
#define NSE_ORDER_RESPONSE_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_ORDER_RESPONSE_DISCLOSEDVOLUME_OFFSET + NSE_ORDER_RESPONSE_DISCLOSEDVOLUME_LENGTH)
#define NSE_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_TOTALVOLUMEREMAINING_OFFSET \
  (NSE_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET + NSE_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_ORDER_RESPONSE_TOTALVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_VOLUME_OFFSET \
  (NSE_ORDER_RESPONSE_TOTALVOLUMEREMAINING_OFFSET + NSE_ORDER_RESPONSE_TOTALVOLUMEREMAINING_LENGTH)
#define NSE_ORDER_RESPONSE_VOLUME_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_VOLUMEFILLEDTODAY_OFFSET \
  (NSE_ORDER_RESPONSE_VOLUME_OFFSET + NSE_ORDER_RESPONSE_VOLUME_LENGTH)
#define NSE_ORDER_RESPONSE_VOLUMEFILLEDTODAY_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_PRICE_OFFSET \
  (NSE_ORDER_RESPONSE_VOLUMEFILLEDTODAY_OFFSET + NSE_ORDER_RESPONSE_VOLUMEFILLEDTODAY_LENGTH)
#define NSE_ORDER_RESPONSE_PRICE_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_GOODTILLDATE_OFFSET (NSE_ORDER_RESPONSE_PRICE_OFFSET + NSE_ORDER_RESPONSE_PRICE_LENGTH)
#define NSE_ORDER_RESPONSE_GOODTILLDATE_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_ENTRYDATETIME_OFFSET \
  (NSE_ORDER_RESPONSE_GOODTILLDATE_OFFSET + NSE_ORDER_RESPONSE_GOODTILLDATE_LENGTH)
#define NSE_ORDER_RESPONSE_ENTRYDATETIME_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_LASTMODIFIED_OFFSET \
  (NSE_ORDER_RESPONSE_ENTRYDATETIME_OFFSET + NSE_ORDER_RESPONSE_ENTRYDATETIME_LENGTH)
#define NSE_ORDER_RESPONSE_LASTMODIFIED_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_STORDERFLAGS_STRUCT_OFFSET \
  (NSE_ORDER_RESPONSE_LASTMODIFIED_OFFSET + NSE_ORDER_RESPONSE_LASTMODIFIED_LENGTH)
#define NSE_ORDER_RESPONSE_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_BRNACHID_OFFSET \
  (NSE_ORDER_RESPONSE_STORDERFLAGS_STRUCT_OFFSET + NSE_ORDER_RESPONSE_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_ORDER_RESPONSE_BRNACHID_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_TRADERID_OFFSET (NSE_ORDER_RESPONSE_BRNACHID_OFFSET + NSE_ORDER_RESPONSE_BRNACHID_LENGTH)
#define NSE_ORDER_RESPONSE_TRADERID_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_BROKERID_OFFSET (NSE_ORDER_RESPONSE_TRADERID_OFFSET + NSE_ORDER_RESPONSE_TRADERID_LENGTH)
#define NSE_ORDER_RESPONSE_BROKERID_LENGTH LENGTH_OF_NSE_ORDER_RESPONSE_BROKERID_CHAR_FIELD

#define NSE_ORDER_RESPONSE_OPENCLOSE_OFFSET (NSE_ORDER_RESPONSE_BROKERID_OFFSET + NSE_ORDER_RESPONSE_BROKERID_LENGTH)
#define NSE_ORDER_RESPONSE_OPENCLOSE_LENGTH sizeof(char)

#define NSE_ORDER_RESPONSE_SETTLOR_OFFSET (NSE_ORDER_RESPONSE_OPENCLOSE_OFFSET + NSE_ORDER_RESPONSE_OPENCLOSE_LENGTH)
#define NSE_ORDER_RESPONSE_SETTLOR_LENGTH LENGTH_OF_NSE_ORDER_RESPONSE_SETTLOR_CHAR_FIELD

#define NSE_ORDER_RESPONSE_PROCLIENTINDICATOR_OFFSET \
  (NSE_ORDER_RESPONSE_SETTLOR_OFFSET + NSE_ORDER_RESPONSE_SETTLOR_LENGTH)
#define NSE_ORDER_RESPONSE_PROCLIENTINDICATOR_LENGTH sizeof(int16_t)

#define NSE_ORDER_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_OFFSET \
  (NSE_ORDER_RESPONSE_PROCLIENTINDICATOR_OFFSET + NSE_ORDER_RESPONSE_PROCLIENTINDICATOR_LENGTH)
#define NSE_ORDER_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_LENGTH sizeof(int8_t)

#define NSE_ORDER_RESPONSE_PAD_1_OFFSET \
  (NSE_ORDER_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_OFFSET + NSE_ORDER_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_LENGTH)
#define NSE_ORDER_RESPONSE_PAD_1_LENGTH sizeof(char)

#define NSE_ORDER_RESPONSE_FILLER_OFFSET (NSE_ORDER_RESPONSE_PAD_1_OFFSET + NSE_ORDER_RESPONSE_PAD_1_LENGTH)
#define NSE_ORDER_RESPONSE_FILLER_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_NFFIELD_OFFSET (NSE_ORDER_RESPONSE_FILLER_OFFSET + NSE_ORDER_RESPONSE_FILLER_LENGTH)
#define NSE_ORDER_RESPONSE_NFFIELD_LENGTH sizeof(double)

#define NSE_ORDER_RESPONSE_TIMESTAMP_OFFSET (NSE_ORDER_RESPONSE_NFFIELD_OFFSET + NSE_ORDER_RESPONSE_NFFIELD_LENGTH)
#define NSE_ORDER_RESPONSE_TIMESTAMP_LENGTH sizeof(int64_t)

#define NSE_ORDER_RESPONSE_PAN_OFFSET (NSE_ORDER_RESPONSE_TIMESTAMP_OFFSET + NSE_ORDER_RESPONSE_TIMESTAMP_LENGTH)
#define NSE_ORDER_RESPONSE_PAN_LENGTH  10

#define NSE_ORDER_RESPONSE_ALGOID_OFFSET (NSE_ORDER_RESPONSE_PAN_OFFSET + NSE_ORDER_RESPONSE_PAN_LENGTH)
#define NSE_ORDER_RESPONSE_ALGOID_LENGTH sizeof(int32_t)

#define NSE_ORDER_RESPONSE_RESERVED_OFFSET (NSE_ORDER_RESPONSE_ALGOID_OFFSET + NSE_ORDER_RESPONSE_ALGOID_LENGTH)
#define NSE_ORDER_RESPONSE_RESERVED_LENGTH sizeof(int16_t) 

#define NSE_ORDER_RESPONSE_LASTACTIVITYREFERENCE_OFFSET (NSE_ORDER_RESPONSE_RESERVED_OFFSET + NSE_ORDER_RESPONSE_RESERVED_LENGTH)
#define NSE_ORDER_RESPONSE_LASTACTIVITYREFERENCE_LENGTH sizeof(int64_t)

#define NSE_ORDER_RESPONSE_STP_RESERVE_OFFSET (NSE_ORDER_RESPONSE_LASTACTIVITYREFERENCE_OFFSET + NSE_ORDER_RESPONSE_LASTACTIVITYREFERENCE_LENGTH)
#define NSE_ORDER_RESPONSE_STP_RESERVE_LENGTH 52

#define NSE_ORDER_RESPONSE_LENGTH ( NSE_ORDER_RESPONSE_STP_RESERVE_OFFSET + NSE_ORDER_RESPONSE_STP_RESERVE_LENGTH)


namespace HFSAT {
namespace NSE {

/*
 * Defines Order response semantics for Derivatives market
 * Extends generic orderResponse template for NSE trimmed structure.
 */

class OrderResponseDerivatives : public OrderResponse {
 public:
  inline ProcessedOrderResponse *ProcessOrderResponse(const char *msg_ptr) {
    memcpy((void *)processed_order_response_.instrument_name,
           (void *)(msg_ptr + NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET),
           NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH);

    memcpy((void *)processed_order_response_.symbol,
           (void *)(msg_ptr + NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET),
           NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH);

    memcpy((void *)processed_order_response_.option_type,
           (void *)(msg_ptr + NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET),
           NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH);

    processed_order_response_.expiry_date =
        ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET)));

    processed_order_response_.strike_price =
        ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET)));

    processed_order_response_.order_number =
        (int64_t)ntoh64(*((int64_t *)(msg_ptr + NSE_ORDER_RESPONSE_ORDERNUMBER_OFFSET)));

    processed_order_response_.last_activity_reference = 
		(int64_t)(ntoh64)(*(int64_t*)(msg_ptr + NSE_ORDER_RESPONSE_LASTACTIVITYREFERENCE_OFFSET));

    processed_order_response_.price = ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_PRICE_OFFSET)));
    processed_order_response_.size = ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_TOTALVOLUMEREMAINING_OFFSET)));

    processed_order_response_.disclosed_size =
        ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET)));

    processed_order_response_.entry_date_time =
        ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_ENTRYDATETIME_OFFSET)));

    processed_order_response_.last_modified_date_time =
        ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_LASTMODIFIED_OFFSET)));

    processed_order_response_.saos = ntoh32(*((int32_t *)(msg_ptr + NSE_ORDER_RESPONSE_FILLER_OFFSET)));
    processed_order_response_.reason_code = ntoh16(*((int16_t *)(msg_ptr + NSE_ORDER_RESPONSE_REASONCODE_OFFSET)));
    processed_order_response_.error_code = ntoh16(*((int16_t *)(msg_ptr + NSE_ORDER_RESPONSE_ERRORCODE_OFFSET)));
    processed_order_response_.mod_cxl_by = (*((char *)(msg_ptr + NSE_ORDER_RESPONSE_MOD_CAN_BY_OFFSET)));

    return &processed_order_response_;
  }
};
}
}
