// =====================================================================================
//
//       Filename:  OrderResponsesNonTR.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/29/2015 11:11:05 PM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/RequestPacket.hpp"
#include "infracore/NSET/NSETemplates/RequestHeader.hpp"
#include "dvccode/CDef/debug_logger.hpp"

#define NSE_ORDERENTRY_REQUEST_NON_TR_PARTCIPANTTYPE_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_ORDERENTRY_REQUEST_NON_TR_PARTCIPANTTYPE_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_1_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_PARTCIPANTTYPE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_PARTCIPANTTYPE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_1_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_COMPETITORPERIOD_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_1_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_1_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_COMPETITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_SOLICITORPERIOD_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_COMPETITORPERIOD_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_COMPETITORPERIOD_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_SOLICITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_MODIFIED_OR_CANCELLED_BY_FLAG_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_SOLICITORPERIOD_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_SOLICITORPERIOD_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_MODIFIED_OR_CANCELLED_BY_FLAG_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_2_OFFSET                 \
  (NSE_ORDERENTRY_REQUEST_NON_TR_MODIFIED_OR_CANCELLED_BY_FLAG_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_MODIFIED_OR_CANCELLED_BY_FLAG_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_2_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_REASONCODE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_2_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_2_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_REASONCODE_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_3_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_REASONCODE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_REASONCODE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_3_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_TOKENNO_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_3_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_3_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_TOKENNO_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_TOKENNO_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_TOKENNO_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH 6

#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET      \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH 10

#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET +        \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET +     \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET +   \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH 2

#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH 2

#define NSE_ORDERENTRY_REQUEST_NON_TR_COUNTERPARTYBROKERID_OFFSET      \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_COUNTERPARTYBROKERID_LENGTH 5

#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_4_OFFSET        \
  (NSE_ORDERENTRY_REQUEST_NON_TR_COUNTERPARTYBROKERID_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_COUNTERPARTYBROKERID_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_4_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_5_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_4_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_4_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_5_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_CLOSEOUTFLAG_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_5_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_5_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CLOSEOUTFLAG_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_6_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CLOSEOUTFLAG_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_CLOSEOUTFLAG_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_6_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_ORDERTYPE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_6_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_6_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_ORDERTYPE_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_ORDERNUMBER_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_ORDERTYPE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_ORDERTYPE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_ORDERNUMBER_LENGTH sizeof(double)

#define NSE_ORDERENTRY_REQUEST_NON_TR_ACCOUNTNUMBER_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_ORDERNUMBER_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_ORDERNUMBER_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_ACCOUNTNUMBER_LENGTH 10

#define NSE_ORDERENTRY_REQUEST_NON_TR_BOOKTYPE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_ACCOUNTNUMBER_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_ACCOUNTNUMBER_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_BOOKTYPE_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_BUYSELLINDICATOR_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_BOOKTYPE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_BOOKTYPE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUME_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_BUYSELLINDICATOR_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_BUYSELLINDICATOR_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUME_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUME_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_TOTALVOLUMEREMAINING_OFFSET  \
  (NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUMEREMAINING_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_TOTALVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_VOLUME_OFFSET            \
  (NSE_ORDERENTRY_REQUEST_NON_TR_TOTALVOLUMEREMAINING_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_TOTALVOLUMEREMAINING_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_VOLUME_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_VOLUMEFILLEDTODAY_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_VOLUME_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_VOLUME_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_VOLUMEFILLEDTODAY_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_PRICE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_VOLUMEFILLEDTODAY_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_VOLUMEFILLEDTODAY_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_PRICE_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_TRIGGERPRICE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_PRICE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_PRICE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_TRIGGERPRICE_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_GOODTILLDATE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_TRIGGERPRICE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_TRIGGERPRICE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_GOODTILLDATE_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_ENTRYDATETIME_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_GOODTILLDATE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_GOODTILLDATE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_ENTRYDATETIME_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_MINIMUMFILL_OR_AONVOLUME_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_ENTRYDATETIME_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_ENTRYDATETIME_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_MINIMUMFILL_OR_AONVOLUME_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_LASTMODIFIED_OFFSET          \
  (NSE_ORDERENTRY_REQUEST_NON_TR_MINIMUMFILL_OR_AONVOLUME_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_MINIMUMFILL_OR_AONVOLUME_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_LASTMODIFIED_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_STORDERFLAGS_STRUCT_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_LASTMODIFIED_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_LASTMODIFIED_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_BRNACHID_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_STORDERFLAGS_STRUCT_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_BRNACHID_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_TRADERID_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_BRNACHID_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_BRNACHID_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_TRADERID_LENGTH sizeof(int32_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_BROKERID_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_TRADERID_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_TRADERID_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_BROKERID_LENGTH 5

#define NSE_ORDERENTRY_REQUEST_NON_TR_CORDFILLER_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_BROKERID_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_BROKERID_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_CORDFILLER_LENGTH 24

#define NSE_ORDERENTRY_REQUEST_NON_TR_OPENCLOSE_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_CORDFILLER_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_CORDFILLER_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_OPENCLOSE_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_SETTLOR_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_OPENCLOSE_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_OPENCLOSE_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_SETTLOR_LENGTH 12

#define NSE_ORDERENTRY_REQUEST_NON_TR_PROCLIENTINDICATOR_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_SETTLOR_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_SETTLOR_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_PROCLIENTINDICATOR_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_SETTLEMENTPERIOD_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_PROCLIENTINDICATOR_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_PROCLIENTINDICATOR_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_SETTLEMENTPERIOD_LENGTH sizeof(int16_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_ADDITIONALORDERFLAGS_STRUCT_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_SETTLEMENTPERIOD_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_SETTLEMENTPERIOD_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_ADDITIONALORDERFLAGS_STRUCT_LENGTH sizeof(int8_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_GIVENUPFLAG_OFFSET              \
  (NSE_ORDERENTRY_REQUEST_NON_TR_ADDITIONALORDERFLAGS_STRUCT_OFFSET + \
   NSE_ORDERENTRY_REQUEST_NON_TR_ADDITIONALORDERFLAGS_STRUCT_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_GIVENUPFLAG_LENGTH sizeof(char)

#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_1_TO_8_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_GIVENUPFLAG_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_GIVENUPFLAG_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_1_TO_8_LENGTH sizeof(int8_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_9_TO_16_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_1_TO_8_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_1_TO_8_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_9_TO_16_LENGTH sizeof(int8_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_17_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_9_TO_16_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_9_TO_16_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_17_LENGTH sizeof(int8_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_18_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_17_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_17_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_18_LENGTH sizeof(int8_t)

#define NSE_ORDERENTRY_REQUEST_NON_TR_NFFIELD_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_18_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_18_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_NFFIELD_LENGTH sizeof(double)

#define NSE_ORDERENTRY_REQUEST_NON_TR_MKTREPLAY_OFFSET \
  (NSE_ORDERENTRY_REQUEST_NON_TR_NFFIELD_OFFSET + NSE_ORDERENTRY_REQUEST_NON_TR_NFFIELD_LENGTH)
#define NSE_ORDERENTRY_REQUEST_NON_TR_MKTREPLAY_LENGTH sizeof(double)

#define NSE_ORDERENTRY_REQUEST_NON_TR_LENGTH                                                                           \
  (NSE_ORDERENTRY_REQUEST_NON_TR_PARTCIPANTTYPE_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_1_LENGTH +             \
   NSE_ORDERENTRY_REQUEST_NON_TR_COMPETITORPERIOD_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_SOLICITORPERIOD_LENGTH +      \
   NSE_ORDERENTRY_REQUEST_NON_TR_MODIFIED_OR_CANCELLED_BY_FLAG_LENGTH +                                                \
   NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_2_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_REASONCODE_LENGTH +                 \
   NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_3_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_TOKENNO_LENGTH +                    \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH +                                          \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH +                                                  \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH +                                              \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH +                                             \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH +                                              \
   NSE_ORDERENTRY_REQUEST_NON_TR_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH +                                                 \
   NSE_ORDERENTRY_REQUEST_NON_TR_COUNTERPARTYBROKERID_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_4_LENGTH +       \
   NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_5_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_CLOSEOUTFLAG_LENGTH +               \
   NSE_ORDERENTRY_REQUEST_NON_TR_RESERVED_6_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_ORDERTYPE_LENGTH +                  \
   NSE_ORDERENTRY_REQUEST_NON_TR_ORDERNUMBER_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_ACCOUNTNUMBER_LENGTH +             \
   NSE_ORDERENTRY_REQUEST_NON_TR_BOOKTYPE_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_BUYSELLINDICATOR_LENGTH +             \
   NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUME_LENGTH +                                                              \
   NSE_ORDERENTRY_REQUEST_NON_TR_DISCLOSEDVOLUMEREMAINING_LENGTH +                                                     \
   NSE_ORDERENTRY_REQUEST_NON_TR_TOTALVOLUMEREMAINING_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_VOLUME_LENGTH +           \
   NSE_ORDERENTRY_REQUEST_NON_TR_VOLUMEFILLEDTODAY_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_PRICE_LENGTH +               \
   NSE_ORDERENTRY_REQUEST_NON_TR_TRIGGERPRICE_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_GOODTILLDATE_LENGTH +             \
   NSE_ORDERENTRY_REQUEST_NON_TR_ENTRYDATETIME_LENGTH +                                                                \
   NSE_ORDERENTRY_REQUEST_NON_TR_MINIMUMFILL_OR_AONVOLUME_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_LASTMODIFIED_LENGTH + \
   NSE_ORDERENTRY_REQUEST_NON_TR_STORDERFLAGS_STRUCT_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_BRNACHID_LENGTH +          \
   NSE_ORDERENTRY_REQUEST_NON_TR_TRADERID_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_BROKERID_LENGTH +                     \
   NSE_ORDERENTRY_REQUEST_NON_TR_CORDFILLER_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_OPENCLOSE_LENGTH +                  \
   NSE_ORDERENTRY_REQUEST_NON_TR_SETTLOR_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_PROCLIENTINDICATOR_LENGTH +            \
   NSE_ORDERENTRY_REQUEST_NON_TR_SETTLEMENTPERIOD_LENGTH +                                                             \
   NSE_ORDERENTRY_REQUEST_NON_TR_ADDITIONALORDERFLAGS_STRUCT_LENGTH +                                                  \
   NSE_ORDERENTRY_REQUEST_NON_TR_GIVENUPFLAG_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_1_TO_8_LENGTH +         \
   NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_9_TO_16_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_17_LENGTH +      \
   NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_18_LENGTH + NSE_ORDERENTRY_REQUEST_NON_TR_NFFIELD_LENGTH +                 \
   NSE_ORDERENTRY_REQUEST_NON_TR_MKTREPLAY_LENGTH)

namespace HFSAT {
namespace NSE {

class OrderResponseNonTR {
 private:
  ProcessedOrderResponseNonTR processed_order_response_;

 public:
  OrderResponseNonTR() { memset((void *)&processed_order_response_, 0, sizeof(ProcessedOrderResponseNonTR)); }
  inline ProcessedOrderResponseNonTR *ProcessOrderResponse(char const *msg_ptr) {
    processed_order_response_.saos =
        ntoh32(*((int32_t *)(msg_ptr + NSE_ORDERENTRY_REQUEST_NON_TR_FLLERFLAGS_1_TO_8_OFFSET)));
    return &processed_order_response_;
  }
};
}
}
