// =====================================================================================
//
//       Filename:  RequestHeader.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/28/2015 05:31:02 PM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/DataDefines.hpp"

//=================  NSE PACKET REQUEST START ====================================================//

#define NSE_REQUEST_MESSAGE_HEADER_TRANSACTION_CODE_OFFSET (NSE_REQUEST_START_OFFSET + NSE_PACKET_REQUEST_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_TRANSACTION_CODE_LENGTH sizeof(int16_t)

#define NSE_REQUEST_MESSAGE_HEADER_LOGTIME_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_TRANSACTION_CODE_OFFSET + NSE_REQUEST_MESSAGE_HEADER_TRANSACTION_CODE_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_LOGTIME_LENGTH sizeof(int32_t)

#define NSE_REQUEST_MESSAGE_HEADER_ALPHACHAR_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_LOGTIME_OFFSET + NSE_REQUEST_MESSAGE_HEADER_LOGTIME_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_ALPHACHAR_LENGTH LENGTH_OF_MESSAGE_HEADER_ALPHACHAR_CHAR_FIELD

#define NSE_REQUEST_MESSAGE_HEADER_TRADERID_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_ALPHACHAR_OFFSET + NSE_REQUEST_MESSAGE_HEADER_ALPHACHAR_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_TRADERID_LENGTH sizeof(int32_t)

#define NSE_REQUEST_MESSAGE_HEADER_ERRORCODE_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_TRADERID_OFFSET + NSE_REQUEST_MESSAGE_HEADER_TRADERID_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_ERRORCODE_LENGTH sizeof(int16_t)

#define NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_ERRORCODE_OFFSET + NSE_REQUEST_MESSAGE_HEADER_ERRORCODE_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP_LENGTH LENGTH_OF_MESSAGE_HEADER_TIMESTAMP_CHAR_FIELD

#define NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP1_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP_OFFSET + NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP1_LENGTH LENGTH_OF_MESSAGE_HEADER_TIMESTAMP_CHAR_FIELD

#define NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP2_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP1_OFFSET + NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP1_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP2_LENGTH LENGTH_OF_MESSAGE_HEADER_TIMESTAMP_CHAR_FIELD

#define NSE_REQUEST_MESSAGE_HEADER_MESSAGELENGTH_OFFSET \
  (NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP2_OFFSET + NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP2_LENGTH)
#define NSE_REQUEST_MESSAGE_HEADER_MESSAGELENGTH_LENGTH sizeof(int16_t)

#define NSE_REQUEST_MESSAGE_HEADER_LENGTH                                                           \
  (NSE_REQUEST_MESSAGE_HEADER_TRANSACTION_CODE_LENGTH + NSE_REQUEST_MESSAGE_HEADER_LOGTIME_LENGTH + \
   NSE_REQUEST_MESSAGE_HEADER_ALPHACHAR_LENGTH + NSE_REQUEST_MESSAGE_HEADER_TRADERID_LENGTH +       \
   NSE_REQUEST_MESSAGE_HEADER_ERRORCODE_LENGTH + NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP_LENGTH +      \
   NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP1_LENGTH + NSE_REQUEST_MESSAGE_HEADER_TIMESTAMP2_LENGTH +    \
   NSE_REQUEST_MESSAGE_HEADER_MESSAGELENGTH_LENGTH)
