// =====================================================================================
//
//       Filename:  SystemInformationResponse.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/30/2015 08:32:04 AM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/DataDefines.hpp"
#include "infracore/NSET/NSETemplates/SystemInformationResponse.hpp"

//============================  NSE SYSTEM INFORMATION RESPONSE  =================================//

#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_NORMAL_OFFSET (NSE_RESPONSE_START_OFFSET)
#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_NORMAL_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_ODDLOT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_NORMAL_OFFSET +    \
   NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_NORMAL_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_ODDLOT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_SPOT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_ODDLOT_OFFSET +  \
   NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_ODDLOT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_SPOT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_AUCTION_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_SPOT_OFFSET +       \
   NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_SPOT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_AUCTION_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_NORMAL_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_AUCTION_OFFSET +      \
   NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_AUCTION_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_NORMAL_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_ODDLOT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_NORMAL_OFFSET +    \
   NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_NORMAL_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_ODDLOT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_SPOT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_ODDLOT_OFFSET +  \
   NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_ODDLOT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_SPOT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_AUCTION_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_SPOT_OFFSET +       \
   NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_SPOT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_AUCTION_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_NORMAL_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_AUCTION_OFFSET +   \
   NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_AUCTION_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_NORMAL_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_ODDLOT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_NORMAL_OFFSET +    \
   NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_NORMAL_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_ODDLOT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_SPOT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_ODDLOT_OFFSET +  \
   NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_ODDLOT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_SPOT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_AUCTION_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_SPOT_OFFSET +       \
   NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_SPOT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_AUCTION_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_UPDATEPORTFOLIO_OFFSET                 \
  (NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_AUCTION_OFFSET + \
   NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_AUCTION_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_UPDATEPORTFOLIO_LENGTH sizeof(char)

#define NSE_SYSTEMINFO_RESPONSE_MARKETINDEX_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_UPDATEPORTFOLIO_OFFSET + NSE_SYSTEMINFO_RESPONSE_UPDATEPORTFOLIO_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_MARKETINDEX_LENGTH sizeof(int32_t)

#define NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_MARKETINDEX_OFFSET + NSE_SYSTEMINFO_RESPONSE_MARKETINDEX_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_OFFSET +  \
   NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_OFFSET +       \
   NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_OFFSET             \
  (NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_OFFSET + \
   NSE_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_OFFSET + NSE_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_WARNINGPERCENT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_OFFSET + NSE_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_WARNINGPERCENT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_WARNINGPERCENT_OFFSET + NSE_SYSTEMINFO_RESPONSE_WARNINGPERCENT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_SNAPQUOTETIME_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_OFFSET + NSE_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_SNAPQUOTETIME_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_RESERVED_1_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_SNAPQUOTETIME_OFFSET + NSE_SYSTEMINFO_RESPONSE_SNAPQUOTETIME_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_RESERVED_1_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_BOARDLOTQTY_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_RESERVED_1_OFFSET + NSE_SYSTEMINFO_RESPONSE_RESERVED_1_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_BOARDLOTQTY_LENGTH sizeof(int32_t)

#define NSE_SYSTEMINFO_RESPONSE_TICKSIZE_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_BOARDLOTQTY_OFFSET + NSE_SYSTEMINFO_RESPONSE_BOARDLOTQTY_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_TICKSIZE_LENGTH sizeof(int32_t)

#define NSE_SYSTEMINFO_RESPONSE_MAXGTCDAYS_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_TICKSIZE_OFFSET + NSE_SYSTEMINFO_RESPONSE_TICKSIZE_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_MAXGTCDAYS_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_OFFSET \
  (NSE_SYSTEMINFO_RESPONSE_MAXGTCDAYS_OFFSET + NSE_SYSTEMINFO_RESPONSE_MAXGTCDAYS_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_OFFSET          \
  (NSE_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_OFFSET + \
   NSE_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_LENGTH)

#define NSE_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_LENGTH sizeof(int16_t)

#define NSE_SYSTEMINFO_RESPONSE_RISKFREEINTERESTRATE_OFFSET    \
  (NSE_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_OFFSET + \
   NSE_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_LENGTH)
#define NSE_SYSTEMINFO_RESPONSE_RISKFREEINTERESTRATE_LENGTH sizeof(int32_t)

namespace HFSAT {
namespace NSE {

class SystemInfoResponseDerivatives : public SystemInfoResponse {
 public:
  inline ProcessedSystemInformationResponse* ProcessSystemInfoResponse(char const* msg_ptr) {
    processed_system_info_response.st_mkt_status.normal =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_NORMAL_OFFSET)));
    processed_system_info_response.st_mkt_status.oddlot =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_ODDLOT_OFFSET)));
    processed_system_info_response.st_mkt_status.spot =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_SPOT_OFFSET)));
    processed_system_info_response.st_mkt_status.auction =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_MARKET_STATUS_STRUCT_AUCTION_OFFSET)));

    processed_system_info_response.st_ex_mkt_status.normal =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_NORMAL_OFFSET)));
    processed_system_info_response.st_ex_mkt_status.oddlot =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_ODDLOT_OFFSET)));
    processed_system_info_response.st_ex_mkt_status.spot =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_SPOT_OFFSET)));
    processed_system_info_response.st_ex_mkt_status.auction =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_EX_MARKET_STATUS_STRUCT_AUCTION_OFFSET)));

    processed_system_info_response.st_pl_mkt_status.normal =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_NORMAL_OFFSET)));
    processed_system_info_response.st_pl_mkt_status.oddlot =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_ODDLOT_OFFSET)));
    processed_system_info_response.st_pl_mkt_status.spot =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_SPOT_OFFSET)));
    processed_system_info_response.st_pl_mkt_status.auction =
        ntoh16(*((int16_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_ST_PL_MARKET_STATUS_STRUCT_AUCTION_OFFSET)));

    processed_system_info_response.market_index =
        ntoh32(*((int32_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_MARKETINDEX_OFFSET)));
    processed_system_info_response.risk_free_interest_rate =
        ntoh32(*((int32_t*)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_RISKFREEINTERESTRATE_OFFSET)));
    processed_system_info_response.update_portfolio =
        *((char *)(msg_ptr + NSE_SYSTEMINFO_RESPONSE_UPDATEPORTFOLIO_OFFSET));
   
    return &processed_system_info_response;
  }
};
}
}
