/**
   \file ExecLogic/strategy_options.hpp

   \author: (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
   Address:
   Suite No 353, Evoma, #14, Bhattarhalli,
   Old Madras Road, Near Garden City College,
   KR Puram, Bangalore 560049, India
   +91 80 4190 3551
*/
#pragma once

#include "dvctrade/ExecLogic/directional_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/directional_aggressive_trading_modify.hpp"
#include "dvctrade/ExecLogic/directional_aggressive_trading_modifyv2.hpp"
#include "dvctrade/ExecLogic/directional_aggressive_trading_single_order.hpp"
#include "dvctrade/ExecLogic/trade_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_based_aggressive_trading2.hpp"
#include "dvctrade/ExecLogic/price_based_aggressive_pro_rata_trading.hpp"
#include "dvctrade/ExecLogic/min_risk_price_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_based_intervention_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/directional_intervention_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_based_security_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_based_trading.hpp"
#include "dvctrade/ExecLogic/price_based_scalper.hpp"
#include "dvctrade/ExecLogic/price_based_aggressive_scalper.hpp"
#include "dvctrade/ExecLogic/price_based_vol_trading.hpp"
#include "dvctrade/ExecLogic/vol_mm_trading.hpp"
#include "dvctrade/ExecLogic/price_pair_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_pair_based_aggressive_trading_v2.hpp"
#include "dvctrade/ExecLogic/directional_pair_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_based_security_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/directional_logistic_trading.hpp"
#include "dvctrade/ExecLogic/directional_intervention_logistic_trading.hpp"
#include "dvctrade/ExecLogic/event_price_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/event_directional_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/structured_price_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/nik_price_pair_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/price_based_spread_trading.hpp"
#include "dvctrade/ExecLogic/price_based_leg_trading.hpp"
#include "dvctrade/ExecLogic/retail_trading.hpp"
#include "dvctrade/ExecLogic/desired_position_trading.hpp"
#include "dvctrade/ExecLogic/risk_based_structured_trading.hpp"
#include "dvctrade/ExecLogic/regime_based_vol_dat_trading.hpp"
#include "dvctrade/ExecLogic/returns_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/regime_trading.hpp"
#include "dvctrade/ExecLogic/structured_general_trading.hpp"
#include "dvctrade/ExecLogic/equity_trading_2.hpp"
#include "dvctrade/ExecLogic/projected_price_pair_based_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/arb_trading.hpp"
#include "dvctrade/ExecLogic/event_bias_aggress_trading.hpp"
#include "dvctrade/ExecLogic/retail_fly_trading_manager.hpp"
#include "dvctrade/ExecLogic/feu3_mm.hpp"
#include "dvctrade/ExecLogic/directional_aggressive_trading_single_order.hpp"
#include "dvctrade/ExecLogic/arb_trading_todtom.hpp"
#include "dvctrade/ExecLogic/directional_synthetic_trading.hpp"
#include "dvctrade/ExecLogic/mean_reverting_trading.hpp"
#include "dvctrade/ExecLogic/options_mean_reverting_trading.hpp"
#include "dvctrade/ExecLogic/index_futures_mean_reverting_trading.hpp"
#include "dvctrade/ExecLogic/base_multiple_trading.hpp"
#include "dvctrade/ExecLogic/nk_trader.hpp"
#include "dvctrade/ExecLogic/sgx_nk1_mm_trading.hpp"
#include "dvctrade/ExecLogic/sgx_nk_spread_mm_trading.hpp"
#include "dvctrade/ExecLogic/pairs_trading.hpp"
#include "dvctrade/ExecLogic/ose_pmm.hpp"
#include "dvctrade/ExecLogic/jp400_pmm.hpp"
#include "dvctrade/ExecLogic/sgx_nk_price_pair_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/sgx_nifty_price_pair_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/implied_price_pair_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/implied_directional_aggressive_trading.hpp"
#include "dvctrade/ExecLogic/fill_time_logger.hpp"
#include "dvctrade/ExecLogic/base_port_trading.hpp"
namespace HFSAT {}
