#! /bin/bash
#
# chkconfig: 2345 95 20
# description: This application was developed by me and is tested on this server
# processname:  midterm_exec_slack_notif
# Author : Akik Dey (c)
#
# midterm_exec_slack_notif : Picks executions for Midterm trades and puts them on slack
# description: Custom execs/scripts enabled as service 
#
### BEGIN INIT INFO
# Provides: custom functionality 
### END INIT INFO

# Source function library.
. /etc/init.d/functions

PIDFILE="/tmp/dvc_mslack.pid"
RETVAL=0

start () {

  echo "Starting Up MidTerm executions Slack Notifier..." 
  bash /home/pengine/prod/live_scripts/push_slack_notifs_from_given_locations.sh >/dev/null 2>&1 &
  PID=`ps -ef |grep push_slack_notifs_from_given_locations | grep -v grep | awk '{print $2}'` ;
  echo $PID > $PIDFILE ;
  is_alive=`ps -ef |grep $PID | grep -v grep | wc -l` ;
  action "Checking If Daemon Was Brought Up" [ "$is_alive" != "0" ]
  return $RETVAL

}

stop () {

  echo "Shutting Down MidTerm executions Slack Notifier..."

  PID=`ps -ef |grep push_slack_notifs_from_given_locations | grep -v grep | awk '{print $2}'`

  if [ -f $PIDFILE ] ; then

    sudo kill -s SIGINT `cat $PIDFILE` >/dev/null 2>/dev/null

  else

    #unusual, but we could make sure to terminate all instances 
    sudo killall -SIGINT push_slack_notifs_from_given_locations >/dev/null 2>/dev/null

  fi

  is_alive=`ps -ef |grep push_slack_notifs_from_given_locations | grep -v grep | wc -l` ;

  if [ $is_alive -gt 0 ] ; then
    sudo kill -9 `ps -ef |grep push_slack_notifs_from_given_locations | grep -v grep | awk '{print $2}'` ;
  fi

  is_alive=`ps -ef |grep push_slack_notifs_from_given_locations | grep -v grep | wc -l` ;

  action "Checking If Daemon Has Been Brought Down" [ "$is_alive" == "0" ]
  rm -rf $PIDFILE ;

  return $RETVAL

}

dostatus () {

  if [ -f "/etc/init.d/functions" ]; then
    status push_slack_notifs_from_given_locations.sh
  fi

}

restart () {

  stop
  start

}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
    restart
    ;;
  status)
        dostatus
        ;;
  *)
        echo "Usage: dvc_mslack {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL

