#ifndef _COMMON_INITIALIZER_DEFINES_H
#define _COMMON_INITIALIZER_DEFINES_H

#define BIT_UNSET_ALL 0x0000
#define BIT_SET_ALL 0xFFFF

#define ORSRISK_STATUS_SET 0x0400
#define HARDLOSS_STATUS_SET 0x0200
#define RISK_STATUS_SET 0x0100
#define CONFIG_STATUS_SET 0x0080
#define CTRLMSG_STATUS_SET 0x0040
#define LOSS_STATUS_SET 0x0020
#define FREEZE_STATUS_SET 0x0010
#define SHOOT_STATUS_SET 0x0008
#define SPREADLIMIT_STATUS_SET 0x0004
#define INVALIDBOOK_STATUS_SET 0x0002
#define SQUAREOFF_STATUS_SET 0x0001
#define CHILD_STATUS_SET 0x0800
#define BANNED_STATUS_SET 0x1000
#define NEAR_CIRCUIT_PRIMARY_STATUS_SET 0X2000
#define NEAR_CIRCUIT_SECONDARY_STATUS_SET 0X4000
#define BAD_FILL_RATIO_STATUS_SET 0X8000

#define ORSRISK_STATUS_UNSET 0xFBFF
#define HARDLOSS_STATUS_UNSET 0xFDFF
#define RISK_STATUS_UNSET 0xFEFF
#define CONFIG_STATUS_UNSET 0xFF7F
#define CTRLMSG_STATUS_UNSET 0xFFBF
#define LOSS_STATUS_UNSET 0xFFDF
#define FREEZE_STATUS_UNSET 0xFFEF
#define SHOOT_STATUS_UNSET 0xFFF7
#define SPREADLIMIT_STATUS_UNSET 0xFFFB
#define INVALIDBOOK_STATUS_UNSET 0xFFFD
#define SQUAREOFF_STATUS_UNSET 0xFFFE
#define CHILD_STATUS_UNSET 0xF7FF
#define BANNED_STATUS_UNSET 0xEFFF
#define NEAR_CIRCUIT_PRIMARY_STATUS_UNSET 0XDFFF
#define NEAR_CIRCUIT_SECONDARY_STATUS_UNSET 0XBFFF
#define BAD_FILL_RATIO_STATUS_UNSET 0X7FFF

#define NOSQUAREOFF_BITS_SET 0x0060
#define SQUAREOFF_BITS_SET 0x0004

#define DOUBLE_PRECISION 0.000001

#define MAX_PRICE 1000000
#define MIN_PRICE -1000

#define MAX_QUEUE_SIZE 6000

typedef enum {
  pORDER_BOOK_BEST_PRICE = 0,
  pVWAP_PRICE,
  pVWAP_PRICE_PASSIVE,
  pCUSTOM_PRICE_TYPE,
  pMID_PRICE,
} SecPriceType_t;

typedef enum { pUPWARD = 0, pNEUTRAL, pDOWNWARD } MovementIndicator_t;

#endif
