#!/bin/bash

load_msg_accelerator () {

  NW_ACCELERATOR_FILE="/home/pengine/prod/live_configs/which_msg_accelerator_should_i_use_for_"`hostname` ;
  ACR=`cat $NW_ACCELERATOR_FILE` ;
  ACCELERATOR_PREFIX="" ;

  if [ "$ACR" == "ONLOAD" ] ; then

   export EF_LOG_VIA_IOCTL=1 ;
   export EF_NO_FAIL=0 ;
   export EF_UDP_RECV_MCAST_UL_ONLY=1 ;
   export EF_SPIN_USEC=-1 ; export EF_POLL_USEC=-1 ; export EF_SELECT_SPIN=1 ;
   export EF_MULTICAST_LOOP_OFF=0 ;
   export EF_MAX_ENDPOINTS=1024 ;
   export EF_SHARE_WITH=-1;
   export EF_NAME=ORS_STACK ;
   ACCELERATOR_PREFIX="onload" ;

  else

    echo "do_nothing" >/dev/null ;

  fi

}

load_msg_accelerator ;

$ACCELERATOR_PREFIX /home/pengine/prod/live_execs/user_msg $@ 2>/dev/null
