
# ----------------------------------------------------
# GLOBAL CONFIGURATION
[GLOBAL]

# PATH TO THE LICENSE FILE
LICENSE_PATH = "/home/pengine/prod/live_configs/siliconMD_NSE.lic"

# PATH TO THE LOG FOLDER **MUST EXIST**
LOG_FOLDER_PATH = "/spare/local/logs/alllogs/"

# PATH TO THE CHANNEL CONFIG DOWNLOADED FROM CME
#NSE_CHANNELS = ["CM:001:239.60.60.41:16641", "CM:002:239.60.60.42:16642", "CM:003:239.60.60.43:16643", "CM:004:239.60.60.44:16644", "FO:005:239.70.70.41:17741", "FO:006:239.70.70.42:17742", "FO:007:239.70.70.43:17743", "FO:008:239.70.70.44:17744", "FO:009:239.70.70.45:17745", "FO:010:239.70.70.46:17746", "FO:011:239.70.70.47:17747", "FO:012:239.70.70.48:17748", "CD:013:239.80.80.41:18841", "CO:014:239.90.90.41:19941"]

#NSE_CHANNELS = ["CM:001:239.60.60.41:16641", "CM:002:239.60.60.42:16642", "CM:003:239.60.60.43:16643", "CM:004:239.60.60.44:16644"]
#NSE_CHANNELS = ["FO:005:239.70.70.41:17741","FO:006:239.70.70.42:17742"]
NSE_CHANNELS = ["FO:007:239.70.70.61:17761","FO:008:239.70.70.62:17762"]

NSE_SNAPSHOT_QUEUE_NAMES = ["005:lvq.nse.fo.od.1.orderbook","006:lvq.nse.fo.od.2.orderbook"]

NSE_RECOVERY = ["CM:172.28.124.34:10984","FO:172.28.124.30:10990","CD:172.28.124.32:10970","CO:172.19.125.84:10960"]

NSE_SNAPSHOT = ["CM:172.28.124.44:10987:member_cm_prod:LxJRe#0414:od_cm_prod","FO:172.28.124.40:10986:member_fo_prod:YoEvx#9675:od_fo_prod","CD:172.28.124.42:10988:member_cd_prod:48Qd5d:od_cd_prod"]

# ----------------------------------------------------
# GENERAL CONFIGURATION ABOUT THE API
[MESSAGE_API]

# INTERFACE TO LISTEN ON OR FPGA IP, DEPENDING IF USING FPGA OR SOCKET
INTERFACE_A = "10.230.154.73"
INTERFACE_B = "10.1.1.19"

# FEEDS TO LISTEN ON
# * IF ONLY ONE FEED IS CHOSEN, ALL CHANNELS WILL USE THAT FEED FOR RECEIVING MARKET DATA
# * IF BOTH A AND B CHOSEN, INCREMENTAL CHANNELS WILL USE BOTH FEEDS TO AVOID
# MISSING MESSAGES, AND OTHER CHANNEL TYPES WILL USE FEED A
#FEED = ["A", "B"]

#PCAP CAPTURE
CAPTURE_ENABLED = false

# ----------------------------------------------------
# THREADED SPECIFIC CONFIGURATION (ONLY USED WHEN ON ThreadedMessageApi)
[THREADED_MESSAGE_API]

# SETS THE MAIN THREAD (WHERE THE API IS CREATED) AFFINITY
#MAIN_THREAD_AFFINITY = 1

# SETS THE THREAD COUNT (IGNORING THE MAIN THREAD)
THREAD_COUNT = 1

# SETS THE THREAD AFFINITY (FOR THREADS EXCEPT MAIN)
#THREAD_AFFINITY = [3, 5, 7]


## ----------------------------------------------------
## TCP RECOVERY AUTHENTICATION (NOT AVAILABLE)
[TCP_RECOVERY]
USERNAME = "NSE"
PASSWORD = "NSE"


# ----------------------------------------------------
# ADVANCED FEATURES

# ----------------------------------------------------
# SOCKET RECEIVER CONFIGURATION
[SOCKET_RECEIVER]

# SETS THE RECEIVER TO BLOCKING OR NON BLOCKING
# ** CAREFUL: NON BLOCKING WILL USE 100% CPU ON EACH THREAD
#BLOCKING = false

# ----------------------------------------------------
# FPGA RECEIVER CONFIGURATION
[FPGA_RECEIVER]

# IGMP WAIT TIME IN MILLISECONDS
#IGMP_WAIT_TIME = 50

# IGMP NO MESSAGE TIMOUT IN SECONDS
#IGMP_NO_MESSAGE_TIMEOUT = 100

# ----------------------------------------------------
# PCAP RECEIVER CONFIGURATION
[PCAP_RECEIVER]

PCAP_FILEPATH = "channel_005_WithoutHB.pcap"

[EVENT_API]
MBP_BOOK_HW = true
MBP_BOOK_HW_PRE_MATCHED = false
