#! /bin/bash
#
# chkconfig: 2345 95 20
# description: Process to rsync the query tags to saci map to NY server
# processname: dvc_pushtag
# Author : Nishank S Bisht (c)
#
# description: Custom execs/scripts enabled as service 
#
### BEGIN INIT INFO
# Provides: custom functionality 
### END INIT INFO

# Source function library.
. /etc/init.d/functions

PIDFILE="/tmp/dvc_pushtag.pid"
RETVAL=0

start () {

  echo "Starting Up DVCPushTag..." 
  sudo runuser -l dvcinfra -c '/home/pengine/prod/live_scripts/tag_rsync.sh >/dev/null 2>/dev/null &'
  PID=`ps -ef |grep tag_rsync | grep -v grep | awk '{print $2}'` ;
  echo $PID > $PIDFILE ;
  is_alive=`ps -ef |grep $PID | grep -v grep | wc -l` ;
  action "Checking If Daemon Was Brought Up" [ "$is_alive" != "0" ]
  return $RETVAL

}

stop () {

  echo "Shutting Down DVCPushTags..."
  PID=`ps -ef |grep tag_rsync | grep -v grep | awk '{print $2}'`

  if [ -f $PIDFILE ] ; then
    sudo kill -s SIGINT `cat $PIDFILE` >/dev/null 2>/dev/null
  else
    #unusual, but we could make sure to terminate all instances 
    sudo killall -SIGINT tag_rsync >/dev/null 2>/dev/null
  fi

  is_alive=`ps -ef |grep tag_rsync | grep -v grep | wc -l` ;

  if [ $is_alive -gt 0 ] ; then
    sudo kill -9 `ps -ef |grep tag_rsync | grep -v grep | awk '{print $2}'` ;
  fi

  is_alive=`ps -ef |grep tag_rsync | grep -v grep | wc -l` ;

  action "Checking If Daemon Has Been Brought Down" [ "$is_alive" == "0" ]
  rm -rf $PIDFILE ;

  return $RETVAL

}

dostatus () {

  if [ -f "/etc/init.d/functions" ]; then
    status tag_rsync.sh
  fi

}

restart () {

  stop
  start

}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
    restart
    ;;
  status)
        dostatus
        ;;
  *)
        echo "Usage: dvc_pushtag {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL

