#ifndef _MDS_SHM_INTERFACE_DEFINES_HPP_
#define _MDS_SHM_INTERFACE_DEFINES_HPP_

#define MULTI_MDS_QUEUE_SIZE 65792
#define MULTI_MDS_QUEUE_SIZE_LAG_THRESHOLD 61680
#define MULTI_MDS_SHM_KEY 9126

#endif
