// =====================================================================================
//
//       Filename:  OrderEntry.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/29/2015 11:11:05 PM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/RequestPacket.hpp"
#include "infracore/NSET/NSETemplates/RequestHeader.hpp"

///////////////////////////////////////////////////////////////////////
//    			  Cash Market Logon Request Defines 				 //
///////////////////////////////////////////////////////////////////////

#define NSE_CM_LOGON_REQUEST_USERID_OFFSET \
  (NSE_REQUEST_START_OFFSET + NSE_REQUEST_MESSAGE_HEADER_LENGTH + NSE_PACKET_REQUEST_LENGTH)
#define NSE_CM_LOGON_REQUEST_USERID_LENGTH sizeof(int32_t)

#define NSE_CM_LOGON_REQUEST_STP_RESERVED_1_OFFSET \
  (NSE_CM_LOGON_REQUEST_USERID_OFFSET + NSE_CM_LOGON_REQUEST_USERID_LENGTH)
#define NSE_CM_LOGON_REQUEST_STP_RESERVED_1_LENGTH 8

#define NSE_CM_LOGON_REQUEST_PASSWORD_OFFSET \
  (NSE_CM_LOGON_REQUEST_STP_RESERVED_1_OFFSET + NSE_CM_LOGON_REQUEST_STP_RESERVED_1_LENGTH)
#define NSE_CM_LOGON_REQUEST_PASSWORD_LENGTH LENGTH_OF_LOGON_REQUEST_PASSWORD_CHAR_FIELD

#define NSE_CM_LOGON_REQUEST_STP_RESERVED_2_OFFSET \
  (NSE_CM_LOGON_REQUEST_PASSWORD_OFFSET + NSE_CM_LOGON_REQUEST_PASSWORD_LENGTH)
#define NSE_CM_LOGON_REQUEST_STP_RESERVED_2_LENGTH 8

#define NSE_CM_LOGON_REQUEST_NEWPASSWORD_OFFSET \
  (NSE_CM_LOGON_REQUEST_STP_RESERVED_2_OFFSET + NSE_CM_LOGON_REQUEST_STP_RESERVED_2_LENGTH)
#define NSE_CM_LOGON_REQUEST_NEWPASSWORD_LENGTH LENGTH_OF_LOGON_REQUEST_PASSWORD_CHAR_FIELD

#define NSE_CM_LOGON_REQUEST_TRADERNAME_OFFSET \
  (NSE_CM_LOGON_REQUEST_NEWPASSWORD_OFFSET + NSE_CM_LOGON_REQUEST_NEWPASSWORD_LENGTH)
#define NSE_CM_LOGON_REQUEST_TRADERNAME_LENGTH LENGTH_OF_LOGON_REQUEST_TRADERNAME_CHAR_FIELD

#define NSE_CM_LOGON_REQUEST_LASTPASSWORDCHANGEDATE_OFFSET \
  (NSE_CM_LOGON_REQUEST_TRADERNAME_OFFSET + NSE_CM_LOGON_REQUEST_TRADERNAME_LENGTH)
#define NSE_CM_LOGON_REQUEST_LASTPASSWORDCHANGEDATE_LENGTH sizeof(int32_t)

#define NSE_CM_LOGON_REQUEST_BROKERID_OFFSET \
  (NSE_CM_LOGON_REQUEST_LASTPASSWORDCHANGEDATE_OFFSET + NSE_CM_LOGON_REQUEST_LASTPASSWORDCHANGEDATE_LENGTH)
#define NSE_CM_LOGON_REQUEST_BROKERID_LENGTH LENGTH_OF_LOGON_REQUEST_BROKERID_CHAR_FIELD

#define NSE_CM_LOGON_REQUEST_RESERVED_1_OFFSET \
  (NSE_CM_LOGON_REQUEST_BROKERID_OFFSET + NSE_CM_LOGON_REQUEST_BROKERID_LENGTH)
#define NSE_CM_LOGON_REQUEST_RESERVED_1_LENGTH sizeof(char)

#define NSE_CM_LOGON_REQUEST_BRANCHID_OFFSET \
  (NSE_CM_LOGON_REQUEST_RESERVED_1_OFFSET + NSE_CM_LOGON_REQUEST_RESERVED_1_LENGTH)
#define NSE_CM_LOGON_REQUEST_BRANCHID_LENGTH sizeof(int16_t)

#define NSE_CM_LOGON_REQUEST_VERSIONNUMBER_OFFSET \
  (NSE_CM_LOGON_REQUEST_BRANCHID_OFFSET + NSE_CM_LOGON_REQUEST_BRANCHID_LENGTH)
#define NSE_CM_LOGON_REQUEST_VERSIONNUMBER_LENGTH sizeof(int32_t)

#define NSE_CM_LOGON_REQUEST_RESERVED_2_OFFSET \
  (NSE_CM_LOGON_REQUEST_VERSIONNUMBER_OFFSET + NSE_CM_LOGON_REQUEST_VERSIONNUMBER_LENGTH)
#define NSE_CM_LOGON_REQUEST_RESERVED_2_LENGTH LENGTH_OF_CM_LOGON_REQUEST_RESERVED_2_LENGTH

#define NSE_CM_LOGON_REQUEST_USERTYPE_OFFSET \
  (NSE_CM_LOGON_REQUEST_RESERVED_2_OFFSET + NSE_CM_LOGON_REQUEST_RESERVED_2_LENGTH)
#define NSE_CM_LOGON_REQUEST_USERTYPE_LENGTH sizeof(int16_t)

#define NSE_CM_LOGON_REQUEST_SEQUENCENUMBER_OFFSET \
  (NSE_CM_LOGON_REQUEST_USERTYPE_OFFSET + NSE_CM_LOGON_REQUEST_USERTYPE_LENGTH)
#define NSE_CM_LOGON_REQUEST_SEQUENCENUMBER_LENGTH sizeof(double)

#define NSE_CM_LOGON_REQUEST_WSCLASSNAME_OFFSET \
  (NSE_CM_LOGON_REQUEST_SEQUENCENUMBER_OFFSET + NSE_CM_LOGON_REQUEST_SEQUENCENUMBER_LENGTH)
#define NSE_CM_LOGON_REQUEST_WSCLASSNAME_LENGTH LENGTH_OF_LOGON_REQUEST_WSCLASSNAME_CHAR_FIELD

#define NSE_CM_LOGON_REQUEST_BROKERSTATUS_OFFSET \
  (NSE_CM_LOGON_REQUEST_WSCLASSNAME_OFFSET + NSE_CM_LOGON_REQUEST_WSCLASSNAME_LENGTH)
#define NSE_CM_LOGON_REQUEST_BROKERSTATUS_LENGTH sizeof(char)

#define NSE_CM_LOGON_REQUEST_SHOWINDEX_OFFSET \
  (NSE_CM_LOGON_REQUEST_BROKERSTATUS_OFFSET + NSE_CM_LOGON_REQUEST_BROKERSTATUS_LENGTH)
#define NSE_CM_LOGON_REQUEST_SHOWINDEX_LENGTH sizeof(char)

#define NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_OFFSET \
  (NSE_CM_LOGON_REQUEST_SHOWINDEX_OFFSET + NSE_CM_LOGON_REQUEST_SHOWINDEX_LENGTH)
#define NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH sizeof(int8_t)

#define NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_OFFSET \
  (NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_OFFSET +    \
   NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH)
#define NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH sizeof(int8_t)

#define NSE_CM_LOGON_REQUEST_BROKERNAME_OFFSET                           \
  (NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_OFFSET + \
   NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH)
#define NSE_CM_LOGON_REQUEST_BROKERNAME_LENGTH LENGTH_OF_CM_LOGON_REQUEST_BROKERNAME_CHAR_FIELD

#define NSE_CM_LOGON_REQUEST_LENGTH                                                                               \
  (NSE_PACKET_REQUEST_LENGTH + NSE_REQUEST_MESSAGE_HEADER_LENGTH + NSE_CM_LOGON_REQUEST_USERID_LENGTH +           \
   NSE_CM_LOGON_REQUEST_PASSWORD_LENGTH + NSE_CM_LOGON_REQUEST_NEWPASSWORD_LENGTH +                               \
   NSE_CM_LOGON_REQUEST_TRADERNAME_LENGTH + NSE_CM_LOGON_REQUEST_LASTPASSWORDCHANGEDATE_LENGTH +                  \
   NSE_CM_LOGON_REQUEST_BROKERID_LENGTH + NSE_CM_LOGON_REQUEST_RESERVED_1_LENGTH +                                \
   NSE_CM_LOGON_REQUEST_BRANCHID_LENGTH + NSE_CM_LOGON_REQUEST_VERSIONNUMBER_LENGTH +                             \
   NSE_CM_LOGON_REQUEST_RESERVED_2_LENGTH + NSE_CM_LOGON_REQUEST_USERTYPE_LENGTH +                                \
   NSE_CM_LOGON_REQUEST_SEQUENCENUMBER_LENGTH + NSE_CM_LOGON_REQUEST_WSCLASSNAME_LENGTH +                         \
   NSE_CM_LOGON_REQUEST_BROKERSTATUS_LENGTH + NSE_CM_LOGON_REQUEST_SHOWINDEX_LENGTH +                             \
   NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH +                                          \
   NSE_CM_LOGON_REQUEST_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH + NSE_CM_LOGON_REQUEST_BROKERNAME_LENGTH + \
   NSE_CM_LOGON_REQUEST_STP_RESERVED_1_LENGTH + NSE_CM_LOGON_REQUEST_STP_RESERVED_2_LENGTH + 48)

///////////////////////////////////////////////////////////////////////
//    			  Cash Market Logon Response Defines 				 //
///////////////////////////////////////////////////////////////////////

#define NSE_CM_LOGON_RESPONSE_USERID_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_CM_LOGON_RESPONSE_USERID_LENGTH sizeof(int32_t)

#define NSE_CM_LOGON_RESPONSE_STP_RESERVED_1_OFFSET \
  (NSE_CM_LOGON_RESPONSE_USERID_OFFSET + NSE_CM_LOGON_RESPONSE_USERID_LENGTH)
#define NSE_CM_LOGON_RESPONSE_STP_RESERVED_1_LENGTH 8

#define NSE_CM_LOGON_RESPONSE_PASSWORD_OFFSET \
  (NSE_CM_LOGON_RESPONSE_STP_RESERVED_1_OFFSET + NSE_CM_LOGON_RESPONSE_STP_RESERVED_1_LENGTH)
#define NSE_CM_LOGON_RESPONSE_PASSWORD_LENGTH LENGTH_OF_LOGON_RESPONSE_PASSWORD_CHAR_FIELD

#define NSE_CM_LOGON_RESPONSE_STP_RESERVED_2_OFFSET \
  (NSE_CM_LOGON_RESPONSE_PASSWORD_OFFSET + NSE_CM_LOGON_RESPONSE_PASSWORD_LENGTH)
#define NSE_CM_LOGON_RESPONSE_STP_RESERVED_2_LENGTH 8

#define NSE_CM_LOGON_RESPONSE_NEWPASSWORD_OFFSET \
  (NSE_CM_LOGON_RESPONSE_STP_RESERVED_2_OFFSET + NSE_CM_LOGON_RESPONSE_STP_RESERVED_2_LENGTH)
#define NSE_CM_LOGON_RESPONSE_NEWPASSWORD_LENGTH LENGTH_OF_LOGON_RESPONSE_PASSWORD_CHAR_FIELD

#define NSE_CM_LOGON_RESPONSE_TRADERNAME_OFFSET \
  (NSE_CM_LOGON_RESPONSE_NEWPASSWORD_OFFSET + NSE_CM_LOGON_RESPONSE_NEWPASSWORD_LENGTH)
#define NSE_CM_LOGON_RESPONSE_TRADERNAME_LENGTH LENGTH_OF_LOGON_RESPONSE_TRADERNAME_CHAR_FIELD

#define NSE_CM_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_OFFSET \
  (NSE_CM_LOGON_RESPONSE_TRADERNAME_OFFSET + NSE_CM_LOGON_RESPONSE_TRADERNAME_LENGTH)
#define NSE_CM_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_LENGTH sizeof(int32_t)

#define NSE_CM_LOGON_RESPONSE_BROKERID_OFFSET \
  (NSE_CM_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_OFFSET + NSE_CM_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_LENGTH)
#define NSE_CM_LOGON_RESPONSE_BROKERID_LENGTH LENGTH_OF_LOGON_RESPONSE_BROKERID_CHAR_FIELD

#define NSE_CM_LOGON_RESPONSE_RESERVED_1_OFFSET \
  (NSE_CM_LOGON_RESPONSE_BROKERID_OFFSET + NSE_CM_LOGON_RESPONSE_BROKERID_LENGTH)
#define NSE_CM_LOGON_RESPONSE_RESERVED_1_LENGTH sizeof(char)

#define NSE_CM_LOGON_RESPONSE_BRANCHID_OFFSET \
  (NSE_CM_LOGON_RESPONSE_RESERVED_1_OFFSET + NSE_CM_LOGON_RESPONSE_RESERVED_1_LENGTH)
#define NSE_CM_LOGON_RESPONSE_BRANCHID_LENGTH sizeof(int16_t)

#define NSE_CM_LOGON_RESPONSE_VERSIONNUMBER_OFFSET \
  (NSE_CM_LOGON_RESPONSE_BRANCHID_OFFSET + NSE_CM_LOGON_RESPONSE_BRANCHID_LENGTH)
#define NSE_CM_LOGON_RESPONSE_VERSIONNUMBER_LENGTH sizeof(int32_t)

#define NSE_CM_LOGON_RESPONSE_BATCH2STARTTIME_OFFSET \
  (NSE_CM_LOGON_RESPONSE_VERSIONNUMBER_OFFSET + NSE_CM_LOGON_RESPONSE_VERSIONNUMBER_LENGTH)
#define NSE_CM_LOGON_RESPONSE_BATCH2STARTTIME_LENGTH sizeof(int32_t)

#define NSE_CM_LOGON_RESPONSE_HOSTSWITCHCONTEXT_OFFSET \
  (NSE_CM_LOGON_RESPONSE_BATCH2STARTTIME_OFFSET + NSE_CM_LOGON_RESPONSE_BATCH2STARTTIME_LENGTH)
#define NSE_CM_LOGON_RESPONSE_HOSTSWITCHCONTEXT_LENGTH sizeof(char)

#define NSE_CM_LOGON_RESPONSE_COLOUR_OFFSET \
  (NSE_CM_LOGON_RESPONSE_HOSTSWITCHCONTEXT_OFFSET + NSE_CM_LOGON_RESPONSE_HOSTSWITCHCONTEXT_LENGTH)
#define NSE_CM_LOGON_RESPONSE_COLOUR_LENGTH LENGTH_OF_LOGON_RESPONSE_COLOUR_CHAR_FIELD

#define NSE_CM_LOGON_RESPONSE_RESERVED_2_OFFSET \
  (NSE_CM_LOGON_RESPONSE_COLOUR_OFFSET + NSE_CM_LOGON_RESPONSE_COLOUR_LENGTH)
#define NSE_CM_LOGON_RESPONSE_RESERVED_2_LENGTH sizeof(char)

#define NSE_CM_LOGON_RESPONSE_USERTYPE_OFFSET \
  (NSE_CM_LOGON_RESPONSE_RESERVED_2_OFFSET + NSE_CM_LOGON_RESPONSE_RESERVED_2_LENGTH)
#define NSE_CM_LOGON_RESPONSE_USERTYPE_LENGTH sizeof(int16_t)

#define NSE_CM_LOGON_RESPONSE_SEQUENCENUMBER_OFFSET \
  (NSE_CM_LOGON_RESPONSE_USERTYPE_OFFSET + NSE_CM_LOGON_RESPONSE_USERTYPE_LENGTH)
#define NSE_CM_LOGON_RESPONSE_SEQUENCENUMBER_LENGTH sizeof(double)

#define NSE_CM_LOGON_RESPONSE_WSCLASSNAME_OFFSET \
  (NSE_CM_LOGON_RESPONSE_SEQUENCENUMBER_OFFSET + NSE_CM_LOGON_RESPONSE_SEQUENCENUMBER_LENGTH)
#define NSE_CM_LOGON_RESPONSE_WSCLASSNAME_LENGTH LENGTH_OF_LOGON_RESPONSE_WSCLASSNAME_CHAR_FIELD

#define NSE_CM_LOGON_RESPONSE_BROKERSTATUS_OFFSET \
  (NSE_CM_LOGON_RESPONSE_WSCLASSNAME_OFFSET + NSE_CM_LOGON_RESPONSE_WSCLASSNAME_LENGTH)
#define NSE_CM_LOGON_RESPONSE_BROKERSTATUS_LENGTH sizeof(char)

#define NSE_CM_LOGON_RESPONSE_SHOWINDEX_OFFSET \
  (NSE_CM_LOGON_RESPONSE_BROKERSTATUS_OFFSET + NSE_CM_LOGON_RESPONSE_BROKERSTATUS_LENGTH)
#define NSE_CM_LOGON_RESPONSE_SHOWINDEX_LENGTH sizeof(char)

#define NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_OFFSET \
  (NSE_CM_LOGON_RESPONSE_SHOWINDEX_OFFSET + NSE_CM_LOGON_RESPONSE_SHOWINDEX_LENGTH)
#define NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH sizeof(int8_t)

#define NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_OFFSET \
  (NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_OFFSET +    \
   NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH)
#define NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH sizeof(int8_t)

#define NSE_CM_LOGON_RESPONSE_BROKERNAME_OFFSET                           \
  (NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_OFFSET + \
   NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH)
#define NSE_CM_LOGON_RESPONSE_BROKERNAME_LENGTH LENGTH_OF_CM_LOGON_REQUEST_BROKERNAME_CHAR_FIELD

#define NSE_CM_LOGON_RESPONSE_LENGTH                                                                                \
  (NSE_CM_LOGON_RESPONSE_USERID_LENGTH + NSE_CM_LOGON_RESPONSE_PASSWORD_LENGTH +                                    \
   NSE_CM_LOGON_RESPONSE_NEWPASSWORD_LENGTH + NSE_CM_LOGON_RESPONSE_TRADERNAME_LENGTH +                             \
   NSE_CM_LOGON_RESPONSE_LASTPASSWORDCHANGEDATE_LENGTH + NSE_CM_LOGON_RESPONSE_BROKERID_LENGTH +                    \
   NSE_CM_LOGON_RESPONSE_RESERVED_1_LENGTH + NSE_CM_LOGON_RESPONSE_BRANCHID_LENGTH +                                \
   NSE_CM_LOGON_RESPONSE_VERSIONNUMBER_LENGTH + NSE_CM_LOGON_RESPONSE_BATCH2STARTTIME_LENGTH +                      \
   NSE_CM_LOGON_RESPONSE_HOSTSWITCHCONTEXT_LENGTH + NSE_CM_LOGON_RESPONSE_COLOUR_LENGTH +                           \
   NSE_CM_LOGON_RESPONSE_RESERVED_2_LENGTH + NSE_CM_LOGON_RESPONSE_USERTYPE_LENGTH +                                \
   NSE_CM_LOGON_RESPONSE_SEQUENCENUMBER_LENGTH + NSE_CM_LOGON_RESPONSE_WSCLASSNAME_LENGTH +                         \
   NSE_CM_LOGON_RESPONSE_BROKERSTATUS_LENGTH + NSE_CM_LOGON_RESPONSE_SHOWINDEX_LENGTH +                             \
   NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD1_LENGTH +                                           \
   NSE_CM_LOGON_RESPONSE_STBROKERELIGIBILITYPERMKT_STRUCT_FIELD2_LENGTH + NSE_CM_LOGON_RESPONSE_BROKERNAME_LENGTH + \
   NSE_CM_LOGON_REQUEST_STP_RESERVED_1_LENGTH + NSE_CM_LOGON_REQUEST_STP_RESERVED_2_LENGTH + 48)

// Logon Msgs : received on login failure if error code in header is nonzero
#define NSE_CM_LOGON_RESPONSE_ERROR_MSG_OFFSET 12
#define NSE_CM_LOGON_RESPONSE_ERROR_MSG_LENGTH 128

///////////////////////////////////////////////////////////////////////
//    			  Cash Market Sysinfo Request Defines 				 //
///////////////////////////////////////////////////////////////////////

#define NSE_CM_SYSTEMINFO_REQUEST_LENGTH (NSE_PACKET_REQUEST_LENGTH + NSE_REQUEST_MESSAGE_HEADER_LENGTH)

///////////////////////////////////////////////////////////////////////
//    			  Cash Market Sysinfo Response Defines 				 //
///////////////////////////////////////////////////////////////////////

#define NSE_CM_SYSTEMINFO_RESPONSE_NORMAL_OFFSET (NSE_RESPONSE_START_OFFSET)
#define NSE_CM_SYSTEMINFO_RESPONSE_NORMAL_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_ODDLOT_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_NORMAL_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_NORMAL_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_ODDLOT_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_SPOT_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_ODDLOT_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_ODDLOT_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_SPOT_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_AUCTION_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_SPOT_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_SPOT_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_AUCTION_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_1_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_AUCTION_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_AUCTION_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_1_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_2_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_1_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_1_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_2_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_MARKETINDEX_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_2_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_CALL_AUCTION_2_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_MARKETINDEX_LENGTH sizeof(int32_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_MARKETINDEX_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_MARKETINDEX_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_OFFSET +  \
   NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_NORMAL_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_OFFSET +       \
   NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_SPOT_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_OFFSET             \
  (NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_OFFSET + \
   NSE_CM_SYSTEMINFO_RESPONSE_DEFAULTSETTLEMENTPERIOD_AUCTION_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_COMPETITORPERIOD_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_WARNINGPERCENT_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_SOLICITORPERIOD_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_WARNINGPERCENT_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_WARNINGPERCENT_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_WARNINGPERCENT_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_RESERVED_1_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_VOLUMEFREEZEPERCENT_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_RESERVED_1_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_TERMINALIDLETIME_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_RESERVED_1_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_RESERVED_1_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_TERMINALIDLETIME_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_BOARDLOTQTY_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_TERMINALIDLETIME_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_TERMINALIDLETIME_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_BOARDLOTQTY_LENGTH sizeof(int32_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_TICKSIZE_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_BOARDLOTQTY_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_BOARDLOTQTY_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_TICKSIZE_LENGTH sizeof(int32_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_MAXGTCDAYS_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_TICKSIZE_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_TICKSIZE_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_MAXGTCDAYS_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_OFFSET \
  (NSE_CM_SYSTEMINFO_RESPONSE_MAXGTCDAYS_OFFSET + NSE_CM_SYSTEMINFO_RESPONSE_MAXGTCDAYS_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_OFFSET          \
  (NSE_CM_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_OFFSET + \
   NSE_CM_SYSTEMINFO_RESPONSE_ST_STOCK_ELIGIBILITY_INDICATORS_STRUCT_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_LENGTH sizeof(int16_t)

#define NSE_CM_SYSTEMINFO_RESPONSE_RESERVED_2_OFFSET              \
  (NSE_CM_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_OFFSET + \
   NSE_CM_SYSTEMINFO_RESPONSE_DISCLOSEDQTYPERCENTALLOWED_LENGTH)
#define NSE_CM_SYSTEMINFO_RESPONSE_RESERVED_2_LENGTH 6

///////////////////////////////////////////////////////////////////////
//    			  Cash Market Update Local DB requests               //
///////////////////////////////////////////////////////////////////////

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATESECURITYTIME_OFFSET \
  (NSE_REQUEST_START_OFFSET + NSE_REQUEST_MESSAGE_HEADER_LENGTH + NSE_PACKET_REQUEST_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATESECURITYTIME_LENGTH sizeof(int32_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATEPARTICIPANTTIME_OFFSET \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATESECURITYTIME_OFFSET +       \
   NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATESECURITYTIME_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATEPARTICIPANTTIME_LENGTH sizeof(int32_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_REQUESTFOROPENORDERS_OFFSET   \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATEPARTICIPANTTIME_OFFSET + \
   NSE_CM_UPDATELOCALDATABSE_REQUEST_LASTUPDATEPARTICIPANTTIME_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_REQUESTFOROPENORDERS_LENGTH sizeof(char)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_RESERVED_1_OFFSET        \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_REQUESTFOROPENORDERS_OFFSET + \
   NSE_CM_UPDATELOCALDATABSE_REQUEST_REQUESTFOROPENORDERS_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_RESERVED_1_LENGTH sizeof(char)

// Market
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_NORMAL_OFFSET \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_RESERVED_1_OFFSET + NSE_CM_UPDATELOCALDATABSE_REQUEST_RESERVED_1_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_NORMAL_LENGTH sizeof(int16_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_ODDLOT_OFFSET \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_NORMAL_OFFSET + NSE_CM_UPDATELOCALDATABSE_REQUEST_NORMAL_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_ODDLOT_LENGTH sizeof(int16_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_SPOT_OFFSET \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_ODDLOT_OFFSET + NSE_CM_UPDATELOCALDATABSE_REQUEST_ODDLOT_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_SPOT_LENGTH sizeof(int16_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_AUCTION_OFFSET \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_SPOT_OFFSET + NSE_CM_UPDATELOCALDATABSE_REQUEST_SPOT_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_AUCTION_LENGTH sizeof(int16_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_1_OFFSET \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_AUCTION_OFFSET + NSE_CM_UPDATELOCALDATABSE_REQUEST_AUCTION_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_1_LENGTH sizeof(int16_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_2_OFFSET \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_1_OFFSET + NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_1_LENGTH)
#define NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_2_LENGTH sizeof(int16_t)

#define NSE_CM_UPDATELOCALDATABSE_REQUEST_LENGTH \
  (NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_2_OFFSET + NSE_CM_UPDATELOCALDATABSE_REQUEST_CALL_AUCTION_2_LENGTH)

///////////////////////////////////////////////////////////////////////
//    			  Cash Market Order Entry Defines 					 //
///////////////////////////////////////////////////////////////////////

#define NSE_CM_ORDERENTRY_REQUEST_TRANSACTIONCODE_OFFSET (NSE_REQUEST_START_OFFSET + NSE_PACKET_REQUEST_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_TRANSACTIONCODE_LENGTH sizeof(int16_t)

#define NSE_CM_ORDERENTRY_REQUEST_USERID_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_TRANSACTIONCODE_OFFSET + NSE_CM_ORDERENTRY_REQUEST_TRANSACTIONCODE_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_USERID_LENGTH sizeof(int32_t)

#define NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SYMBOL_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_USERID_OFFSET + NSE_CM_ORDERENTRY_REQUEST_USERID_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SYMBOL_LENGTH \
  LENGTH_OF_NSE_CM_CONTRACT_SECINFO_STRUCT_SYMBOL_CHAR_FIELD

#define NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SERIES_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SYMBOL_OFFSET +    \
   NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SYMBOL_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SERIES_LENGTH 2

#define NSE_CM_ORDERENTRY_REQUEST_ACCOUNTNUMBER_OFFSET               \
  (NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SERIES_OFFSET + \
   NSE_CM_ORDERENTRY_REQUEST_CONTRACT_SECINFO_STRUCT_SERIES_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_ACCOUNTNUMBER_LENGTH LENGTH_OF_NSE_CM_ACCOUNTNUMBER_CHAR_FIELD

#define NSE_CM_ORDERENTRY_REQUEST_BOOKTYPE_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_ACCOUNTNUMBER_OFFSET + NSE_CM_ORDERENTRY_REQUEST_ACCOUNTNUMBER_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_BOOKTYPE_LENGTH sizeof(int16_t)

#define NSE_CM_ORDERENTRY_REQUEST_BUYSELLINDICATOR_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_BOOKTYPE_OFFSET + NSE_CM_ORDERENTRY_REQUEST_BOOKTYPE_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_CM_ORDERENTRY_REQUEST_DISCLOSEDVOLUME_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_BUYSELLINDICATOR_OFFSET + NSE_CM_ORDERENTRY_REQUEST_BUYSELLINDICATOR_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_CM_ORDERENTRY_REQUEST_VOLUME_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_DISCLOSEDVOLUME_OFFSET + NSE_CM_ORDERENTRY_REQUEST_DISCLOSEDVOLUME_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_VOLUME_LENGTH sizeof(int32_t)

#define NSE_CM_ORDERENTRY_REQUEST_PRICE_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_VOLUME_OFFSET + NSE_CM_ORDERENTRY_REQUEST_VOLUME_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_PRICE_LENGTH sizeof(int32_t)

#define NSE_CM_ORDERENTRY_REQUEST_GOODTILLDATE_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_PRICE_OFFSET + NSE_CM_ORDERENTRY_REQUEST_PRICE_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_GOODTILLDATE_LENGTH sizeof(int32_t)

#define NSE_CM_ORDERENTRY_REQUEST_STORDERFLAGS_STRUCT_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_GOODTILLDATE_OFFSET + NSE_CM_ORDERENTRY_REQUEST_GOODTILLDATE_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_CM_ORDERENTRY_REQUEST_BRNACHID_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_STORDERFLAGS_STRUCT_OFFSET + NSE_CM_ORDERENTRY_REQUEST_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_BRNACHID_LENGTH sizeof(int16_t)

#define NSE_CM_ORDERENTRY_REQUEST_TRADERID_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_BRNACHID_OFFSET + NSE_CM_ORDERENTRY_REQUEST_BRNACHID_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_TRADERID_LENGTH sizeof(int32_t)

#define NSE_CM_ORDERENTRY_REQUEST_BROKERID_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_TRADERID_OFFSET + NSE_CM_ORDERENTRY_REQUEST_TRADERID_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_BROKERID_LENGTH LENGTH_OF_NSE_CM_BROKERID_CHAR_FIELD

#define NSE_CM_ORDERENTRY_REQUEST_SUSPENDED_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_BROKERID_OFFSET + NSE_CM_ORDERENTRY_REQUEST_BROKERID_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_SUSPENDED_LENGTH sizeof(char)

#define NSE_CM_ORDERENTRY_REQUEST_SETTLOR_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_SUSPENDED_OFFSET + NSE_CM_ORDERENTRY_REQUEST_SUSPENDED_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_SETTLOR_LENGTH LENGTH_OF_NSE_CM_SETTLOR_CHAR_FIELD

#define NSE_CM_ORDERENTRY_REQUEST_PROCLIENTINDICATOR_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_SETTLOR_OFFSET + NSE_CM_ORDERENTRY_REQUEST_SETTLOR_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_PROCLIENTINDICATOR_LENGTH sizeof(int16_t)

#define NSE_CM_ORDERENTRY_REQUEST_NFFIELD_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_PROCLIENTINDICATOR_OFFSET + NSE_CM_ORDERENTRY_REQUEST_PROCLIENTINDICATOR_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_NFFIELD_LENGTH sizeof(double)

#define NSE_CM_ORDERENTRY_REQUEST_TRANSACTION_ID_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_NFFIELD_OFFSET + NSE_CM_ORDERENTRY_REQUEST_NFFIELD_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_TRANSACTION_ID_LENGTH sizeof(int32_t)

#define NSE_CM_ORDERENTRY_REQUEST_PAN_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_TRANSACTION_ID_OFFSET + NSE_CM_ORDERENTRY_REQUEST_TRANSACTION_ID_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_PAN_LENGTH 10

#define NSE_CM_ORDERENTRY_REQUEST_ALGOID_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_PAN_OFFSET + NSE_CM_ORDERENTRY_REQUEST_PAN_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_ALGOID_LENGTH 4

#define NSE_CM_ORDERENTRY_REQUEST_ALGOCAT_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_ALGOID_OFFSET + NSE_CM_ORDERENTRY_REQUEST_ALGOID_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_ALGOCAT_LENGTH 2

#define NSE_CM_ORDERENTRY_REQUEST_STP_RESERVED_OFFSET \
  (NSE_CM_ORDERENTRY_REQUEST_ALGOCAT_OFFSET + NSE_CM_ORDERENTRY_REQUEST_ALGOCAT_LENGTH)
#define NSE_CM_ORDERENTRY_REQUEST_STP_RESERVED_LENGTH 32

#define NSE_CM_ORDERENTRY_REQUEST_LENGTH \
  NSE_CM_ORDERENTRY_REQUEST_STP_RESERVED_OFFSET + NSE_CM_ORDERENTRY_REQUEST_STP_RESERVED_LENGTH

///////////////////////////////////////////////////////////////////////////////////////////////
//    			  Cash Market Order Modify, Cancel and Response Defines                      //
///////////////////////////////////////////////////////////////////////////////////////////////

#define NSE_CM_ORDER_RESPONSE_TRANSACTIONCODE_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_CM_ORDER_RESPONSE_TRANSACTIONCODE_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_LOGTIME_OFFSET      \
  (NSE_CM_ORDER_RESPONSE_TRANSACTIONCODE_OFFSET + \
   NSE_CM_ORDER_RESPONSE_TRANSACTIONCODE_LENGTH)
#define NSE_CM_ORDER_RESPONSE_LOGTIME_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_USERID_OFFSET \
  (NSE_CM_ORDER_RESPONSE_LOGTIME_OFFSET + NSE_CM_ORDER_RESPONSE_LOGTIME_LENGTH)
#define NSE_CM_ORDER_RESPONSE_USERID_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_ERRORCODE_OFFSET \
  (NSE_CM_ORDER_RESPONSE_USERID_OFFSET + NSE_CM_ORDER_RESPONSE_USERID_LENGTH)
#define NSE_CM_ORDER_RESPONSE_ERRORCODE_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_TIMESTAMP1_OFFSET \
  (NSE_CM_ORDER_RESPONSE_ERRORCODE_OFFSET + NSE_CM_ORDER_RESPONSE_ERRORCODE_LENGTH)
#define NSE_CM_ORDER_RESPONSE_TIMESTAMP1_LENGTH sizeof(double)

#define NSE_CM_ORDER_RESPONSE_TIMESTAMP2_OFFSET \
  (NSE_CM_ORDER_RESPONSE_TIMESTAMP1_OFFSET + NSE_CM_ORDER_RESPONSE_TIMESTAMP1_LENGTH)
#define NSE_CM_ORDER_RESPONSE_TIMESTAMP2_LENGTH sizeof(char)

#define NSE_CM_ORDER_RESPONSE_MOD_CAN_BY_OFFSET \
  (NSE_CM_ORDER_RESPONSE_TIMESTAMP2_OFFSET + NSE_CM_ORDER_RESPONSE_TIMESTAMP2_LENGTH)
#define NSE_CM_ORDER_RESPONSE_MOD_CAN_BY_LENGTH sizeof(char)

#define NSE_CM_ORDER_RESPONSE_REASONCODE_OFFSET \
  (NSE_CM_ORDER_RESPONSE_MOD_CAN_BY_OFFSET + NSE_CM_ORDER_RESPONSE_MOD_CAN_BY_LENGTH)
#define NSE_CM_ORDER_RESPONSE_REASONCODE_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_OFFSET \
  (NSE_CM_ORDER_RESPONSE_REASONCODE_OFFSET + NSE_CM_ORDER_RESPONSE_REASONCODE_LENGTH)
#define NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_LENGTH \
  LENGTH_OF_NSE_CM_CONTRACT_SECINFO_STRUCT_SYMBOL_CHAR_FIELD

#define NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_OFFSET \
  (NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_OFFSET +    \
   NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_LENGTH)
#define NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_LENGTH 2

#define NSE_CM_ORDER_RESPONSE_ORDERNUMBER_OFFSET                 \
  (NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_OFFSET + \
   NSE_CM_ORDER_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_LENGTH)
#define NSE_CM_ORDER_RESPONSE_ORDERNUMBER_LENGTH sizeof(double)

#define NSE_CM_ORDER_RESPONSE_ACCOUNTNUMBER_OFFSET \
  (NSE_CM_ORDER_RESPONSE_ORDERNUMBER_OFFSET + NSE_CM_ORDER_RESPONSE_ORDERNUMBER_LENGTH)
#define NSE_CM_ORDER_RESPONSE_ACCOUNTNUMBER_LENGTH LENGTH_OF_NSE_CM_ACCOUNTNUMBER_CHAR_FIELD

#define NSE_CM_ORDER_RESPONSE_BOOKTYPE_OFFSET   \
  (NSE_CM_ORDER_RESPONSE_ACCOUNTNUMBER_OFFSET + \
   NSE_CM_ORDER_RESPONSE_ACCOUNTNUMBER_LENGTH)
#define NSE_CM_ORDER_RESPONSE_BOOKTYPE_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_BUYSELLINDICATOR_OFFSET \
  (NSE_CM_ORDER_RESPONSE_BOOKTYPE_OFFSET + NSE_CM_ORDER_RESPONSE_BOOKTYPE_LENGTH)
#define NSE_CM_ORDER_RESPONSE_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUME_OFFSET \
  (NSE_CM_ORDER_RESPONSE_BUYSELLINDICATOR_OFFSET +   \
   NSE_CM_ORDER_RESPONSE_BUYSELLINDICATOR_LENGTH)
#define NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUME_OFFSET +             \
   NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUME_LENGTH)
#define NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_TOTALVOLUMEREMAINING_OFFSET  \
  (NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET + \
   NSE_CM_ORDER_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_CM_ORDER_RESPONSE_TOTALVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_VOLUME_OFFSET            \
  (NSE_CM_ORDER_RESPONSE_TOTALVOLUMEREMAINING_OFFSET + \
   NSE_CM_ORDER_RESPONSE_TOTALVOLUMEREMAINING_LENGTH)
#define NSE_CM_ORDER_RESPONSE_VOLUME_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_VOLUMEFILLEDTODAY_OFFSET \
  (NSE_CM_ORDER_RESPONSE_VOLUME_OFFSET + NSE_CM_ORDER_RESPONSE_VOLUME_LENGTH)
#define NSE_CM_ORDER_RESPONSE_VOLUMEFILLEDTODAY_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_PRICE_OFFSET          \
  (NSE_CM_ORDER_RESPONSE_VOLUMEFILLEDTODAY_OFFSET + \
   NSE_CM_ORDER_RESPONSE_VOLUMEFILLEDTODAY_LENGTH)
#define NSE_CM_ORDER_RESPONSE_PRICE_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_ENTRYDATETIME_OFFSET \
  (NSE_CM_ORDER_RESPONSE_PRICE_OFFSET + NSE_CM_ORDER_RESPONSE_PRICE_LENGTH)
#define NSE_CM_ORDER_RESPONSE_ENTRYDATETIME_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_LASTMODIFIED_OFFSET \
  (NSE_CM_ORDER_RESPONSE_ENTRYDATETIME_OFFSET +   \
   NSE_CM_ORDER_RESPONSE_ENTRYDATETIME_LENGTH)
#define NSE_CM_ORDER_RESPONSE_LASTMODIFIED_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_STORDERFLAGS_STRUCT_OFFSET \
  (NSE_CM_ORDER_RESPONSE_LASTMODIFIED_OFFSET + NSE_CM_ORDER_RESPONSE_LASTMODIFIED_LENGTH)
#define NSE_CM_ORDER_RESPONSE_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_BRANCHID_OFFSET         \
  (NSE_CM_ORDER_RESPONSE_STORDERFLAGS_STRUCT_OFFSET + \
   NSE_CM_ORDER_RESPONSE_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_CM_ORDER_RESPONSE_BRANCHID_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_TRADERID_OFFSET \
  (NSE_CM_ORDER_RESPONSE_BRANCHID_OFFSET + NSE_CM_ORDER_RESPONSE_BRANCHID_LENGTH)
#define NSE_CM_ORDER_RESPONSE_TRADERID_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_BROKERID_OFFSET \
  (NSE_CM_ORDER_RESPONSE_TRADERID_OFFSET + NSE_CM_ORDER_RESPONSE_TRADERID_LENGTH)
#define NSE_CM_ORDER_RESPONSE_BROKERID_LENGTH LENGTH_OF_NSE_CM_BROKERID_CHAR_FIELD

#define NSE_CM_ORDER_RESPONSE_SUSPENDED_OFFSET \
  (NSE_CM_ORDER_RESPONSE_BROKERID_OFFSET + NSE_CM_ORDER_RESPONSE_BROKERID_LENGTH)
#define NSE_CM_ORDER_RESPONSE_SUSPENDED_LENGTH sizeof(char)

#define NSE_CM_ORDER_RESPONSE_SETTLOR_OFFSET \
  (NSE_CM_ORDER_RESPONSE_SUSPENDED_OFFSET + NSE_CM_ORDER_RESPONSE_SUSPENDED_LENGTH)
#define NSE_CM_ORDER_RESPONSE_SETTLOR_LENGTH LENGTH_OF_NSE_CM_SETTLOR_CHAR_FIELD

#define NSE_CM_ORDER_RESPONSE_PROCLIENTINDICATOR_OFFSET \
  (NSE_CM_ORDER_RESPONSE_SETTLOR_OFFSET + NSE_CM_ORDER_RESPONSE_SETTLOR_LENGTH)
#define NSE_CM_ORDER_RESPONSE_PROCLIENTINDICATOR_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_SETTLEMENT_PERIOD_OFFSET \
  (NSE_CM_ORDER_RESPONSE_PROCLIENTINDICATOR_OFFSET +   \
   NSE_CM_ORDER_RESPONSE_PROCLIENTINDICATOR_LENGTH)
#define NSE_CM_ORDER_RESPONSE_SETTLEMENT_PERIOD_LENGTH sizeof(int16_t)

#define NSE_CM_ORDER_RESPONSE_NFFIELD_OFFSET        \
  (NSE_CM_ORDER_RESPONSE_SETTLEMENT_PERIOD_OFFSET + \
   NSE_CM_ORDER_RESPONSE_SETTLEMENT_PERIOD_LENGTH)
#define NSE_CM_ORDER_RESPONSE_NFFIELD_LENGTH sizeof(double)

#define NSE_CM_ORDER_RESPONSE_TRANSACTION_ID_OFFSET \
  (NSE_CM_ORDER_RESPONSE_NFFIELD_OFFSET + NSE_CM_ORDER_RESPONSE_NFFIELD_LENGTH)
#define NSE_CM_ORDER_RESPONSE_TRANSACTION_ID_LENGTH sizeof(int32_t)

#define NSE_CM_ORDER_RESPONSE_TIMESTAMP_OFFSET         \
  (NSE_CM_ORDER_RESPONSE_TRANSACTION_ID_OFFSET + \
   NSE_CM_ORDER_RESPONSE_TRANSACTION_ID_LENGTH)
#define NSE_CM_ORDER_RESPONSE_TIMESTAMP_LENGTH 8

#define NSE_CM_ORDER_RESPONSE_PAN_OFFSET         \
  (NSE_CM_ORDER_RESPONSE_TIMESTAMP_OFFSET + \
   NSE_CM_ORDER_RESPONSE_TIMESTAMP_LENGTH)
#define NSE_CM_ORDER_RESPONSE_PAN_LENGTH 10

#define NSE_CM_ORDER_RESPONSE_ALGOID_OFFSET \
  (NSE_CM_ORDER_RESPONSE_PAN_OFFSET + NSE_CM_ORDER_RESPONSE_PAN_LENGTH)
#define NSE_CM_ORDER_RESPONSE_ALGOID_LENGTH 4

#define NSE_CM_ORDER_RESPONSE_ALGOCAT_OFFSET \
  (NSE_CM_ORDER_RESPONSE_ALGOID_OFFSET + NSE_CM_ORDER_RESPONSE_ALGOID_LENGTH)
#define NSE_CM_ORDER_RESPONSE_ALGOCAT_LENGTH 2

#define NSE_CM_ORDER_RESPONSE_LASTACTIVITYREFERENCE_OFFSET \
  (NSE_CM_ORDER_RESPONSE_ALGOCAT_OFFSET + NSE_CM_ORDER_RESPONSE_ALGOCAT_LENGTH)
#define NSE_CM_ORDER_RESPONSE_LASTACTIVITYREFERENCE_LENGTH sizeof(uint64_t)

#define NSE_CM_ORDER_RESPONSE_STP_RESERVED_OFFSET \
  (NSE_CM_ORDER_RESPONSE_LASTACTIVITYREFERENCE_OFFSET + NSE_CM_ORDER_RESPONSE_LASTACTIVITYREFERENCE_LENGTH)
#define NSE_CM_ORDER_RESPONSE_STP_RESERVED_LENGTH 52

///////////////////////////////////////////////////////////////////////////////////////////////
//    			  		Cash Market Trade Defines                                            //
///////////////////////////////////////////////////////////////////////////////////////////////

#define NSE_CM_TRADE_RESPONSE_TRANSACTIONCODE_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_CM_TRADE_RESPONSE_TRANSACTIONCODE_LENGTH sizeof(int16_t)

#define NSE_CM_TRADE_RESPONSE_LOGTIME_OFFSET \
  (NSE_CM_TRADE_RESPONSE_TRANSACTIONCODE_OFFSET + NSE_CM_TRADE_RESPONSE_TRANSACTIONCODE_LENGTH)
#define NSE_CM_TRADE_RESPONSE_LOGTIME_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_CM_TRADERID_OFFSET \
  (NSE_CM_TRADE_RESPONSE_LOGTIME_OFFSET + NSE_CM_TRADE_RESPONSE_LOGTIME_LENGTH)
#define NSE_CM_TRADE_RESPONSE_CM_TRADERID_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_TIMESTAMP_OFFSET \
  (NSE_CM_TRADE_RESPONSE_CM_TRADERID_OFFSET + NSE_CM_TRADE_RESPONSE_CM_TRADERID_LENGTH)
#define NSE_CM_TRADE_RESPONSE_TIMESTAMP_LENGTH sizeof(double)

#define NSE_CM_TRADE_RESPONSE_TIMESTAMP1_OFFSET \
  (NSE_CM_TRADE_RESPONSE_TIMESTAMP_OFFSET + NSE_CM_TRADE_RESPONSE_TIMESTAMP_LENGTH)
#define NSE_CM_TRADE_RESPONSE_TIMESTAMP1_LENGTH sizeof(double)

#define NSE_CM_TRADE_RESPONSE_ORDER_NUM_OFFSET \
  (NSE_CM_TRADE_RESPONSE_TIMESTAMP1_OFFSET + NSE_CM_TRADE_RESPONSE_TIMESTAMP1_LENGTH)
#define NSE_CM_TRADE_RESPONSE_ORDER_NUM_LENGTH sizeof(double)

#define NSE_CM_TRADE_RESPONSE_TIMESTAMP2_OFFSET \
  (NSE_CM_TRADE_RESPONSE_ORDER_NUM_OFFSET + NSE_CM_TRADE_RESPONSE_ORDER_NUM_LENGTH)
#define NSE_CM_TRADE_RESPONSE_TIMESTAMP2_LENGTH sizeof(char)

#define NSE_CM_TRADE_RESPONSE_BROKERID_OFFSET \
  (NSE_CM_TRADE_RESPONSE_TIMESTAMP2_OFFSET + NSE_CM_TRADE_RESPONSE_TIMESTAMP2_LENGTH)
#define NSE_CM_TRADE_RESPONSE_BROKERID_LENGTH LENGTH_OF_NSE_CM_BROKERID_CHAR_FIELD

#define NSE_CM_TRADE_RESPONSE_TRADERNUM_OFFSET \
  (NSE_CM_TRADE_RESPONSE_BROKERID_OFFSET + NSE_CM_TRADE_RESPONSE_BROKERID_LENGTH)
#define NSE_CM_TRADE_RESPONSE_TRADERNUM_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_BUYSELLINDICATOR_OFFSET \
  (NSE_CM_TRADE_RESPONSE_TRADERNUM_OFFSET + NSE_CM_TRADE_RESPONSE_TRADERNUM_LENGTH)
#define NSE_CM_TRADE_RESPONSE_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_CM_TRADE_RESPONSE_ACCOUNTNUMBER_OFFSET \
  (NSE_CM_TRADE_RESPONSE_BUYSELLINDICATOR_OFFSET + NSE_CM_TRADE_RESPONSE_BUYSELLINDICATOR_LENGTH)
#define NSE_CM_TRADE_RESPONSE_ACCOUNTNUMBER_LENGTH LENGTH_OF_NSE_CM_ACCOUNTNUMBER_CHAR_FIELD

#define NSE_CM_TRADE_RESPONSE_ORIGINALVOLUME_OFFSET \
  (NSE_CM_TRADE_RESPONSE_ACCOUNTNUMBER_OFFSET + NSE_CM_TRADE_RESPONSE_ACCOUNTNUMBER_LENGTH)
#define NSE_CM_TRADE_RESPONSE_ORIGINALVOLUME_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUME_OFFSET \
  (NSE_CM_TRADE_RESPONSE_ORIGINALVOLUME_OFFSET + NSE_CM_TRADE_RESPONSE_ORIGINALVOLUME_LENGTH)
#define NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_REMAININGVOLUME_OFFSET \
  (NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUME_OFFSET + NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUME_LENGTH)
#define NSE_CM_TRADE_RESPONSE_REMAININGVOLUME_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_CM_TRADE_RESPONSE_REMAININGVOLUME_OFFSET + NSE_CM_TRADE_RESPONSE_REMAININGVOLUME_LENGTH)
#define NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_PRICE_OFFSET \
  (NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET + NSE_CM_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_CM_TRADE_RESPONSE_PRICE_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_STORDERFLAGS_STRUCT_OFFSET \
  (NSE_CM_TRADE_RESPONSE_PRICE_OFFSET + NSE_CM_TRADE_RESPONSE_PRICE_LENGTH)
#define NSE_CM_TRADE_RESPONSE_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_CM_TRADE_RESPONSE_FILLNUMBER_OFFSET \
  (NSE_CM_TRADE_RESPONSE_STORDERFLAGS_STRUCT_OFFSET + NSE_CM_TRADE_RESPONSE_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_CM_TRADE_RESPONSE_FILLNUMBER_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_FILLQUANTITY_OFFSET \
  (NSE_CM_TRADE_RESPONSE_FILLNUMBER_OFFSET + NSE_CM_TRADE_RESPONSE_FILLNUMBER_LENGTH)
#define NSE_CM_TRADE_RESPONSE_FILLQUANTITY_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_FILLPRICE_OFFSET \
  (NSE_CM_TRADE_RESPONSE_FILLQUANTITY_OFFSET + NSE_CM_TRADE_RESPONSE_FILLQUANTITY_LENGTH)
#define NSE_CM_TRADE_RESPONSE_FILLPRICE_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_VOL_FILLED_TODAY_OFFSET \
  (NSE_CM_TRADE_RESPONSE_FILLPRICE_OFFSET + NSE_CM_TRADE_RESPONSE_FILLPRICE_LENGTH)
#define NSE_CM_TRADE_RESPONSE_VOL_FILLED_TODAY_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_ACTIVITY_TYPE_OFFSET \
  (NSE_CM_TRADE_RESPONSE_VOL_FILLED_TODAY_OFFSET + NSE_CM_TRADE_RESPONSE_VOL_FILLED_TODAY_LENGTH)
#define NSE_CM_TRADE_RESPONSE_ACTIVITY_TYPE_LENGTH 2

#define NSE_CM_TRADE_RESPONSE_ACTIVITY_TIME_OFFSET \
  (NSE_CM_TRADE_RESPONSE_ACTIVITY_TYPE_OFFSET + NSE_CM_TRADE_RESPONSE_ACTIVITY_TYPE_LENGTH)
#define NSE_CM_TRADE_RESPONSE_ACTIVITY_TIME_LENGTH sizeof(int32_t)

#define NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_OFFSET \
  (NSE_CM_TRADE_RESPONSE_ACTIVITY_TIME_OFFSET + NSE_CM_TRADE_RESPONSE_ACTIVITY_TIME_LENGTH)
#define NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_LENGTH \
  LENGTH_OF_NSE_CM_CONTRACT_SECINFO_STRUCT_SYMBOL_CHAR_FIELD

#define NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_OFFSET \
  (NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_OFFSET +    \
   NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SYMBOL_LENGTH)
#define NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_LENGTH 2

#define NSE_CM_TRADE_RESPONSE_BOOK_TYPE_OFFSET                   \
  (NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_OFFSET + \
   NSE_CM_TRADE_RESPONSE_CONTRACT_SECINFO_STRUCT_SERIES_LENGTH)
#define NSE_CM_TRADE_RESPONSE_BOOK_TYPE_LENGTH sizeof(int16_t)

#define NSE_CM_TRADE_RESPONSE_PROCLIENT_OFFSET \
  (NSE_CM_TRADE_RESPONSE_BOOK_TYPE_OFFSET + NSE_CM_TRADE_RESPONSE_BOOK_TYPE_LENGTH)
#define NSE_CM_TRADE_RESPONSE_PROCLIENT_LENGTH sizeof(int16_t)

#define NSE_CM_TRADE_RESPONSE_PAN_OFFSET \
  (NSE_CM_TRADE_RESPONSE_PROCLIENT_OFFSET + NSE_CM_TRADE_RESPONSE_PROCLIENT_LENGTH)
#define NSE_CM_TRADE_RESPONSE_PAN_LENGTH 10

#define NSE_CM_TRADE_RESPONSE_ALGOID_OFFSET (NSE_CM_TRADE_RESPONSE_PAN_OFFSET + NSE_CM_TRADE_RESPONSE_PAN_LENGTH)
#define NSE_CM_TRADE_RESPONSE_ALGOID_LENGTH 4

#define NSE_CM_TRADE_RESPONSE_ALGOCAT_OFFSET (NSE_CM_TRADE_RESPONSE_ALGOID_OFFSET + NSE_CM_TRADE_RESPONSE_ALGOID_LENGTH)
#define NSE_CM_TRADE_RESPONSE_ALGOCAT_LENGTH 2

#define NSE_CM_TRADE_RESPONSE_LASTACTIVITYREFERENCE_OFFSET \
  (NSE_CM_TRADE_RESPONSE_ALGOCAT_OFFSET + NSE_CM_TRADE_RESPONSE_ALGOCAT_LENGTH)
#define NSE_CM_TRADE_RESPONSE_LASTACTIVITYREFERENCE_LENGTH sizeof(int64_t)

#define NSE_CM_TRADE_RESPONSE_STP_RESERVED_OFFSET \
  (NSE_CM_TRADE_RESPONSE_LASTACTIVITYREFERENCE_OFFSET + NSE_CM_TRADE_RESPONSE_LASTACTIVITYREFERENCE_LENGTH)
#define NSE_CM_TRADE_RESPONSE_STP_RESERVED_LENGTH 52

#define NSE_CM_TRADE_RESPONSE_LENGTH \
  (NSE_CM_TRADE_RESPONSE_STP_RESERVED_OFFSET + NSE_CM_TRADE_RESPONSE_STP_RESERVED_LENGTH)
