// =====================================================================================
//
//       Filename:  SecurityMasterUpdateDBResponse.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/30/2015 09:44:07 AM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/DataDefines.hpp"

//======================================  NSE SECURITY MASTER UPDATE DB RESPONSE ==================================//

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TOKEN_OFFSET (NSE_RESPONSE_START_OFFSET)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TOKEN_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_INSTRUMENTNAME_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TOKEN_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TOKEN_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_INSTRUMENTNAME_LENGTH 6

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SYMBOL_OFFSET      \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_INSTRUMENTNAME_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_INSTRUMENTNAME_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SYMBOL_LENGTH 10

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SERIES_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SYMBOL_OFFSET +    \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SYMBOL_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SERIES_LENGTH 2

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_EXPIRYDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SERIES_OFFSET +        \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_SERIES_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_OPTIONTYPE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_EXPIRYDATE_OFFSET +    \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_EXPIRYDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_OPTIONTYPE_LENGTH 2

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_CALEVEL_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_OPTIONTYPE_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_OPTIONTYPE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_CALEVEL_LENGTH sizeof(int16_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_PERMITTEDTOTRADE_OFFSET    \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_CALEVEL_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_SECINFO_STRUCT_CALEVEL_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_PERMITTEDTOTRADE_LENGTH sizeof(int16_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEDCAPITAL_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_PERMITTEDTOTRADE_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_PERMITTEDTOTRADE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEDCAPITAL_LENGTH sizeof(double)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_WARNINGQUANTITY_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEDCAPITAL_OFFSET +      \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEDCAPITAL_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_WARNINGQUANTITY_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_FREEZEQUANTITY_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_WARNINGQUANTITY_OFFSET +   \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_WARNINGQUANTITY_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_FREEZEQUANTITY_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_CREDITRATING_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_FREEZEQUANTITY_OFFSET +  \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_FREEZEQUANTITY_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_CREDITRATING_LENGTH 12

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_SEC_ELIGIBILITY_PER_MARKET_REPITITIVE_STRUCT_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_CREDITRATING_OFFSET +                                       \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_CREDITRATING_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_SEC_ELIGIBILITY_PER_MARKET_REPITITIVE_STRUCT_LENGTH 12

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUERATE_OFFSET                                    \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_SEC_ELIGIBILITY_PER_MARKET_REPITITIVE_STRUCT_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_SEC_ELIGIBILITY_PER_MARKET_REPITITIVE_STRUCT_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUERATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUESTARTDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUERATE_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUERATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUESTARTDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTERESTPAYMENTDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUESTARTDATE_OFFSET +         \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUESTARTDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTERESTPAYMENTDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEMATURITYDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTERESTPAYMENTDATE_OFFSET +  \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTERESTPAYMENTDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEMATURITYDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MARGINPERCENTAGE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEMATURITYDATE_OFFSET +   \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ISSUEMATURITYDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MARGINPERCENTAGE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MINIMUMLOTQUANTITY_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MARGINPERCENTAGE_OFFSET +      \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MARGINPERCENTAGE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MINIMUMLOTQUANTITY_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOARDLOTQUANTITY_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MINIMUMLOTQUANTITY_OFFSET +  \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MINIMUMLOTQUANTITY_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOARDLOTQUANTITY_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TICKSIZE_OFFSET      \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOARDLOTQUANTITY_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOARDLOTQUANTITY_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TICKSIZE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NAME_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TICKSIZE_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TICKSIZE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NAME_LENGTH 25

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RESERVED_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NAME_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NAME_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RESERVED_LENGTH 1

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LISTINGDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RESERVED_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RESERVED_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LISTINGDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPULSIONDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LISTINGDATE_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LISTINGDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPULSIONDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_READMISSIONDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPULSIONDATE_OFFSET +      \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPULSIONDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_READMISSIONDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RECORDDATE_OFFSET   \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_READMISSIONDATE_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_READMISSIONDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RECORDDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOWPRICERANGE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RECORDDATE_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_RECORDDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOWPRICERANGE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_HIGHPRICERANGE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOWPRICERANGE_OFFSET +     \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOWPRICERANGE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_HIGHPRICERANGE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPIRYDATE_OFFSET  \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_HIGHPRICERANGE_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_HIGHPRICERANGE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYSTARTDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPIRYDATE_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPIRYDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYSTARTDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYENDDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYSTARTDATE_OFFSET +  \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYSTARTDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYENDDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_1_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYENDDATE_OFFSET +                          \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NODELIVERYENDDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_1_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_2_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_1_OFFSET +    \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_1_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_2_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSURESTARTDATE_OFFSET                 \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_2_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_2_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSURESTARTDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSUREENDDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSURESTARTDATE_OFFSET +  \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSURESTARTDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSUREENDDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISESTARTDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSUREENDDATE_OFFSET +   \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOOKCLOSUREENDDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISESTARTDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISEENDDATE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISESTARTDATE_OFFSET +  \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISESTARTDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISEENDDATE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_OLDTOKEN_OFFSET     \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISEENDDATE_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXERCISEENDDATE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_OLDTOKEN_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETINSTRUMENT_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_OLDTOKEN_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_OLDTOKEN_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETINSTRUMENT_LENGTH 6

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETNAME_OFFSET    \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETINSTRUMENT_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETINSTRUMENT_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETNAME_LENGTH 10

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETTOKEN_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETNAME_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETNAME_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETTOKEN_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTRINSICVALUE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETTOKEN_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETTOKEN_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTRINSICVALUE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXTRINSICVALUE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTRINSICVALUE_OFFSET +    \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_INTRINSICVALUE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXTRINSICVALUE_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_1_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXTRINSICVALUE_OFFSET +               \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXTRINSICVALUE_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_1_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_2_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_1_OFFSET +    \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_1_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_2_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOCALUPDATEDATETIME_OFFSET    \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_2_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_2_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOCALUPDATEDATETIME_LENGTH sizeof(int32_t)

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_DELETEFLAG_OFFSET       \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOCALUPDATEDATETIME_OFFSET + \
   NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOCALUPDATEDATETIME_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_DELETEFLAG_LENGTH 1

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_REMARK_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_DELETEFLAG_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_DELETEFLAG_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_REMARK_LENGTH 25

#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BASEPRICE_OFFSET \
  (NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_REMARK_OFFSET + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_REMARK_LENGTH)
#define NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BASEPRICE_LENGTH sizeof(int32_t)

namespace HFSAT {
namespace NSE {

class NSESecurityUpdate {
 private:
  ProcessedSeurityUpdateInfoResponse processed_security_update_;

 public:
  NSESecurityUpdate() { memset((void *)&processed_security_update_, 0, sizeof(ProcessedSeurityUpdateInfoResponse)); }

  inline ProcessedSeurityUpdateInfoResponse *ProcessSecurityUpdate(char const *msg_ptr) {
    processed_security_update_.token =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TOKEN_OFFSET)));

    processed_security_update_.permitted_to_trade =
        ntoh16(*((int16_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_PERMITTEDTOTRADE_OFFSET)));

    processed_security_update_.minimum_lot_quantity =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_MINIMUMLOTQUANTITY_OFFSET)));

    processed_security_update_.board_lot_quantity =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BOARDLOTQUANTITY_OFFSET)));

    processed_security_update_.tick_size =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_TICKSIZE_OFFSET)));

    memcpy((void *)processed_security_update_.name,
           (void *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NAME_OFFSET),
           NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_NAME_LENGTH);

    processed_security_update_.low_price_range =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOWPRICERANGE_OFFSET)));

    processed_security_update_.high_price_range =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_HIGHPRICERANGE_LENGTH)));

    processed_security_update_.expiry_date =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_EXPIRYDATE_OFFSET)));

    memcpy((void *)processed_security_update_.asset_instrument,
           (void *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETINSTRUMENT_OFFSET),
           NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETINSTRUMENT_LENGTH);

    memcpy((void *)processed_security_update_.asset_name,
           (void *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETNAME_OFFSET),
           NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETNAME_LENGTH);

    memcpy((void *)processed_security_update_.asset_token,
           (void *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETTOKEN_OFFSET),
           NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ASSETTOKEN_LENGTH);

    processed_security_update_.local_update_date_time =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_LOCALUPDATEDATETIME_OFFSET)));

    processed_security_update_.delete_flag =
        *((char *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_DELETEFLAG_OFFSET));

    processed_security_update_.base_price =
        ntoh32(*((int32_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_BASEPRICE_OFFSET)));

    for (uint32_t status_counter = 0; status_counter < (uint32_t)4; status_counter++) {
      processed_security_update_.sec_eligibility_status[status_counter].reserved_eligibilty =
          *((int8_t *)(msg_ptr +
                       NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_SEC_ELIGIBILITY_PER_MARKET_REPITITIVE_STRUCT_OFFSET +
                       3 * status_counter));

      processed_security_update_.sec_eligibility_status[status_counter].status = ntoh16(
          *((int16_t *)(msg_ptr +
                        NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_SEC_ELIGIBILITY_PER_MARKET_REPITITIVE_STRUCT_OFFSET +
                        sizeof(int8_t) + 3 * status_counter)));
    }

    processed_security_update_.eligibility_info =
        *((int8_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_ELIGIBLITY_INDICATORS_STRUCT_FIELD_1_OFFSET));

    processed_security_update_.purpose =
        ntoh16(*((int16_t *)(msg_ptr + NSE_SECURITYMASTER_UPDATEDDB_RESPONSE_ST_PURPOSE_STRUCT_FIELD_1_OFFSET)));

    return &processed_security_update_;
  }
};
}
}
