// =====================================================================================
//
//       Filename:  SpreadOrderResponses.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/29/2015 11:11:05 PM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/RequestPacket.hpp"
#include "infracore/NSET/NSETemplates/RequestHeader.hpp"
#include "dvccode/CDef/debug_logger.hpp"
#include "infracore/NSET/NSETemplates/DataDefines.hpp"

#define NSE_SPREAD_ORDERENTRY_RESPONSE_PARTCIPANTTYPE_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_PARTCIPANTTYPE_LENGTH sizeof(char)

/* TEMP #define NSE_SPREAD_ORDERENTRY_RESPONSE_PARTCIPANTTYPE_OFFSET \
   TMEP (NSE_RESPONSE_START_OFFSET + NSE_RESPONSE_MESSAGE_HEADER_LENGTH + NSE_PACKET_RESPONSE_LENGTH)
*/

#define NSE_SPREAD_ORDERENTRY_RESPONSE_PARTCIPANTTYPE_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_PARTCIPANTTYPE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_PARTCIPANTTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_COMPETITORPERIOD_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_COMPETITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_SOLICITORPERIOD_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_COMPETITORPERIOD_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_COMPETITORPERIOD_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_SOLICITORPERIOD_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MODIFIED_OR_CANCELLED_BY_FLAG_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_SOLICITORPERIOD_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_SOLICITORPERIOD_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MODIFIED_OR_CANCELLED_BY_FLAG_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_2_OFFSET                 \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MODIFIED_OR_CANCELLED_BY_FLAG_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MODIFIED_OR_CANCELLED_BY_FLAG_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_2_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_REASONCODE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_2_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_2_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_REASONCODE_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_STARTAPLHA_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_REASONCODE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_REASONCODE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_STARTAPLHA_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_ENDAPLHA_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_STARTAPLHA_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_STARTAPLHA_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_ENDAPLHA_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_TOKENNO_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_ENDAPLHA_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_ENDAPLHA_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_TOKENNO_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_TOKENNO_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_TOKENNO_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH 6

#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET      \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH 10

#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET +        \
   NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET +     \
   NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET +   \
   NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH 2

#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH 2

#define NSE_SPREAD_ORDERENTRY_RESPONSE_OPBROKERID_OFFSET                \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_OPBROKERID_LENGTH 5

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_X_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_OPBROKERID_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_OPBROKERID_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_X_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_OPTIONS_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_X_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_X_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_OPTIONS_LENGTH 3

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_Y_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_OPTIONS_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_OPTIONS_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_Y_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERTYPE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_Y_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FILLER_Y_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERTYPE_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERNUMBER_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERTYPE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERNUMBER_LENGTH sizeof(double)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_ACCOUNTNUMBER_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERNUMBER_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERNUMBER_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_ACCOUNTNUMBER_LENGTH 10

#define NSE_SPREAD_ORDERENTRY_RESPONSE_BOOKTYPE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_ACCOUNTNUMBER_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_ACCOUNTNUMBER_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_BOOKTYPE_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_BUYSELLINDICATOR_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_BOOKTYPE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_BOOKTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_BUYSELLINDICATOR_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_BUYSELLINDICATOR_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUME_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_TOTALVOLUMEREMAINING_OFFSET  \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_TOTALVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUME_OFFSET            \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_TOTALVOLUMEREMAINING_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_TOTALVOLUMEREMAINING_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUMEFILLEDTODAY_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUME_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUMEFILLEDTODAY_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_PRICE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUMEFILLEDTODAY_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUMEFILLEDTODAY_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_PRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_TRIGGERPRICE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_PRICE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_PRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_TRIGGERPRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_GOODTILLDATE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_TRIGGERPRICE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_TRIGGERPRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_GOODTILLDATE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_ENTRYDATETIME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_GOODTILLDATE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_GOODTILLDATE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_ENTRYDATETIME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MINIMUMFILL_OR_AONVOLUME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_ENTRYDATETIME_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_ENTRYDATETIME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MINIMUMFILL_OR_AONVOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_LASTMODIFIED_OFFSET          \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MINIMUMFILL_OR_AONVOLUME_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MINIMUMFILL_OR_AONVOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_LASTMODIFIED_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_STORDERFLAGS_STRUCT_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_LASTMODIFIED_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_LASTMODIFIED_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_BRNACHID_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_STORDERFLAGS_STRUCT_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_BRNACHID_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_TRADERID_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_BRNACHID_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_BRNACHID_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_TRADERID_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_BROKERID_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_TRADERID_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_TRADERID_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_BROKERID_LENGTH 5

#define NSE_SPREAD_ORDERENTRY_RESPONSE_CORDFILLER_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_BROKERID_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_BROKERID_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_CORDFILLER_LENGTH 24

#define NSE_SPREAD_ORDERENTRY_RESPONSE_OPENCLOSE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_CORDFILLER_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_CORDFILLER_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_OPENCLOSE_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLOR_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_OPENCLOSE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_OPENCLOSE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLOR_LENGTH 12

#define NSE_SPREAD_ORDERENTRY_RESPONSE_PROCLIENTINDICATOR_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLOR_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLOR_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_PROCLIENTINDICATOR_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLEMENTPERIOD_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_PROCLIENTINDICATOR_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_PROCLIENTINDICATOR_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLEMENTPERIOD_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLEMENTPERIOD_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_SETTLEMENTPERIOD_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_GIVENUPFLAG_OFFSET              \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_GIVENUPFLAG_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_1_TO_8_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_GIVENUPFLAG_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_GIVENUPFLAG_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_1_TO_8_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_9_TO_16_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_1_TO_8_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_1_TO_8_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_9_TO_16_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_17_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_9_TO_16_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_9_TO_16_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_17_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_18_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_17_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_17_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_18_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_NFFIELD_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_18_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_18_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_NFFIELD_LENGTH sizeof(double)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MKTREPLAY_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_NFFIELD_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_NFFIELD_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MKTREPLAY_LENGTH sizeof(double)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_PAN_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MKTREPLAY_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_MKTREPLAY_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_PAN_LENGTH 10

#define NSE_SPREAD_ORDERENTRY_RESPONSE_ALGOID_OFFSET (NSE_SPREAD_ORDERENTRY_RESPONSE_PAN_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_PAN_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_ALGOID_LENGTH 4

#define NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_3_OFFSET (NSE_SPREAD_ORDERENTRY_RESPONSE_ALGOID_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_ALGOID_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_3_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_LAST_ACTIVITY_REFERENCE_OFFSET (NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_3_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_3_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_LAST_ACTIVITY_REFERENCE_LENGTH sizeof(int64_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_4_OFFSET (NSE_SPREAD_ORDERENTRY_RESPONSE_LAST_ACTIVITY_REFERENCE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_LAST_ACTIVITY_REFERENCE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_4_LENGTH 52

#define NSE_SPREAD_ORDERENTRY_RESPONSE_PRICEDIFF_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_4_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_RESERVED_4_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_PRICEDIFF_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOKENNO_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_PRICEDIFF_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_PRICEDIFF_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOKENNO_LENGTH 4

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOKENNO_OFFSET +                                \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOKENNO_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH 6

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET      \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH 10

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET +        \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET +     \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET +   \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH 2

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH 2

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPBROKERID_OFFSET                \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPBROKERID_LENGTH 5

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FILLER_X_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPBROKERID_OFFSET +  \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPBROKERID_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FILLER_X_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ORDERTYPE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FILLER_X_OFFSET +     \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FILLER_X_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ORDERTYPE_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_BUYSELLINDICATOR_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ORDERTYPE_OFFSET +           \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ORDERTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_BUYSELLINDICATOR_OFFSET +   \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_BUYSELLINDICATOR_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUME_OFFSET +             \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOTALVOLUMEREMAINING_OFFSET  \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUMEREMAINING_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOTALVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUME_OFFSET            \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOTALVOLUMEREMAINING_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TOTALVOLUMEREMAINING_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUMEFILLEDTODAY_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUME_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUMEFILLEDTODAY_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_PRICE_OFFSET          \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUMEFILLEDTODAY_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_VOLUMEFILLEDTODAY_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_PRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TRIGGERPRICE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_PRICE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_PRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TRIGGERPRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_MINIMUMFILL_OR_AONVOLUME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TRIGGERPRICE_OFFSET +                \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_TRIGGERPRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_MINIMUMFILL_OR_AONVOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_STORDERFLAGS_STRUCT_OFFSET   \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_MINIMUMFILL_OR_AONVOLUME_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_MINIMUMFILL_OR_AONVOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPENCLOSE_OFFSET        \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_STORDERFLAGS_STRUCT_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPENCLOSE_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ADDITIONALORDERFLAGS_STRUCT_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPENCLOSE_OFFSET +                      \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_OPENCLOSE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ADDITIONALORDERFLAGS_STRUCT_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_GIVENUPFLAG_OFFSET              \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ADDITIONALORDERFLAGS_STRUCT_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_ADDITIONALORDERFLAGS_STRUCT_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_GIVENUPFLAG_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FLLERFLAGS_Y_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_GIVENUPFLAG_OFFSET +     \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_GIVENUPFLAG_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FLLERFLAGS_Y_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOKENNO_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FLLERFLAGS_Y_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FLLERFLAGS_Y_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOKENNO_LENGTH 4

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOKENNO_OFFSET +                                \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOKENNO_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH 6

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET      \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH 10

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET +        \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET +     \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET +   \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH 2

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH 2

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPBROKERID_OFFSET                \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_CALEVEL_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_CONTRACT_DESC_STRUCT_CALEVEL_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPBROKERID_LENGTH 5

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FILLER_X_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPBROKERID_OFFSET +  \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPBROKERID_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FILLER_X_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ORDERTYPE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FILLER_X_OFFSET +     \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FILLER_X_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ORDERTYPE_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_BUYSELLINDICATOR_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ORDERTYPE_OFFSET +           \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ORDERTYPE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_BUYSELLINDICATOR_OFFSET +   \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_BUYSELLINDICATOR_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUME_OFFSET +             \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOTALVOLUMEREMAINING_OFFSET  \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUMEREMAINING_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOTALVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUME_OFFSET            \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOTALVOLUMEREMAINING_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TOTALVOLUMEREMAINING_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUMEFILLEDTODAY_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUME_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUMEFILLEDTODAY_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_PRICE_OFFSET          \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUMEFILLEDTODAY_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_VOLUMEFILLEDTODAY_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_PRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TRIGGERPRICE_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_PRICE_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_PRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TRIGGERPRICE_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_MINIMUMFILL_OR_AONVOLUME_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TRIGGERPRICE_OFFSET +                \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_TRIGGERPRICE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_MINIMUMFILL_OR_AONVOLUME_LENGTH sizeof(int32_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_STORDERFLAGS_STRUCT_OFFSET   \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_MINIMUMFILL_OR_AONVOLUME_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_MINIMUMFILL_OR_AONVOLUME_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPENCLOSE_OFFSET        \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_STORDERFLAGS_STRUCT_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPENCLOSE_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ADDITIONALORDERFLAGS_STRUCT_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPENCLOSE_OFFSET +                      \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OPENCLOSE_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ADDITIONALORDERFLAGS_STRUCT_LENGTH sizeof(int8_t)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_GIVENUPFLAG_OFFSET              \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ADDITIONALORDERFLAGS_STRUCT_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_ADDITIONALORDERFLAGS_STRUCT_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_GIVENUPFLAG_LENGTH sizeof(char)

#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FLLERFLAGS_Y_OFFSET \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_GIVENUPFLAG_OFFSET +     \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_GIVENUPFLAG_LENGTH)
#define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FLLERFLAGS_Y_LENGTH sizeof(int8_t)

/*
 #define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_OFFSET           \
   (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FLLERFLAGS_Y_OFFSET + \
   NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_2_FLLERFLAGS_Y_LENGTH)
 #define NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_LENGTH 80
*/

#define NSE_SPREAD_ORDERENTRY_RESPONSE_LENGTH \
  (NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FLLERFLAGS_Y_OFFSET + NSE_SPREAD_ORDERENTRY_RESPONSE_MS_SPD_LEG_3_FLLERFLAGS_Y_LENGTH)

namespace HFSAT {
namespace NSE {

// ============= SpreadOrdeEntryConfirmation Response =====================================

class SpreadOrderResponse {
 private:
  ProcessedSpreadOrderResponse processed_order_response_;

 public:
  SpreadOrderResponse() { memset((void*)&processed_order_response_, 0, sizeof(ProcessedSpreadOrderResponse)); }
  inline ProcessedSpreadOrderResponse* ProcessSpreadOrderResponse(char const* msg_ptr) {
    processed_order_response_.entry_date_time =
        ntoh32(*((int32_t*)(msg_ptr + NSE_SPREAD_ORDERENTRY_RESPONSE_ENTRYDATETIME_OFFSET)));

    processed_order_response_.order_number =
        ntoh64(*((int64_t*)(msg_ptr + NSE_SPREAD_ORDERENTRY_RESPONSE_ORDERNUMBER_OFFSET)));

    processed_order_response_.price = ntoh32(*((int32_t*)(msg_ptr + NSE_SPREAD_ORDERENTRY_RESPONSE_PRICEDIFF_OFFSET)));

    processed_order_response_.last_modified_date_time =
        ntoh32(*((int32_t*)(msg_ptr + NSE_SPREAD_ORDERENTRY_RESPONSE_LASTMODIFIED_OFFSET)));

    processed_order_response_.size = ntoh32(*((int32_t*)(msg_ptr + NSE_SPREAD_ORDERENTRY_RESPONSE_VOLUME_OFFSET)));

    processed_order_response_.saos =
        ntoh32(*((int32_t*)(msg_ptr + NSE_SPREAD_ORDERENTRY_RESPONSE_FLLERFLAGS_1_TO_8_OFFSET)));

    return &processed_order_response_;
  }
};
}
}
