// =====================================================================================
//
//       Filename:  TradeConfirmationResponse.hpp
//
//    Description:
//
//        Version:  1.0
//        Created:  06/29/2015 11:11:05 PM
//       Revision:  none
//       Compiler:  g++
//
//         Author:  (c) Copyright Two Roads Technological Solutions Pvt Ltd 2011
//
//        Address:  Suite No 162, Evoma, #14, Bhattarhalli,
//                  Old Madras Road, Near Garden City College,
//                  KR Puram, Bangalore 560049, India
//          Phone:  +91 80 4190 3551
//
// =====================================================================================

#pragma once

#include "infracore/NSET/NSETemplates/TradeConfirmationResponse.hpp"

#define NSE_TRADE_RESPONSE_TRANSACTIONCODE_OFFSET (NSE_REQUEST_START_OFFSET)
#define NSE_TRADE_RESPONSE_TRANSACTIONCODE_LENGTH sizeof(int16_t)

#define NSE_TRADE_RESPONSE_LOGTIME_OFFSET \
  (NSE_TRADE_RESPONSE_TRANSACTIONCODE_OFFSET + NSE_TRADE_RESPONSE_TRANSACTIONCODE_LENGTH)
#define NSE_TRADE_RESPONSE_LOGTIME_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_TRADERID_OFFSET (NSE_TRADE_RESPONSE_LOGTIME_OFFSET + NSE_TRADE_RESPONSE_LOGTIME_LENGTH)
#define NSE_TRADE_RESPONSE_TRADERID_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_TIMESTAMP_OFFSET (NSE_TRADE_RESPONSE_TRADERID_OFFSET + NSE_TRADE_RESPONSE_TRADERID_LENGTH)
#define NSE_TRADE_RESPONSE_TIMESTAMP_LENGTH sizeof(double)

#define NSE_TRADE_RESPONSE_TIMESTAMP1_OFFSET (NSE_TRADE_RESPONSE_TIMESTAMP_OFFSET + NSE_TRADE_RESPONSE_TIMESTAMP_LENGTH)
#define NSE_TRADE_RESPONSE_TIMESTAMP1_LENGTH sizeof(double)

#define NSE_TRADE_RESPONSE_TIMESTAMP2_OFFSET \
  (NSE_TRADE_RESPONSE_TIMESTAMP1_OFFSET + NSE_TRADE_RESPONSE_TIMESTAMP1_LENGTH)
#define NSE_TRADE_RESPONSE_TIMESTAMP2_LENGTH sizeof(double)

#define NSE_TRADE_RESPONSE_ORDER_NUM_OFFSET \
  (NSE_TRADE_RESPONSE_TIMESTAMP2_OFFSET + NSE_TRADE_RESPONSE_TIMESTAMP2_LENGTH)
#define NSE_TRADE_RESPONSE_ORDER_NUM_LENGTH sizeof(double)

#define NSE_TRADE_RESPONSE_BROKERID_OFFSET (NSE_TRADE_RESPONSE_ORDER_NUM_OFFSET + NSE_TRADE_RESPONSE_ORDER_NUM_LENGTH)
#define NSE_TRADE_RESPONSE_BROKERID_LENGTH LENGTH_OF_NSE_TRADE_RESPONSE_BROKERID_CHAR_FIELD

#define NSE_TRADE_RESPONSE_RESERVED_OFFSET (NSE_TRADE_RESPONSE_BROKERID_OFFSET + NSE_TRADE_RESPONSE_BROKERID_LENGTH)
#define NSE_TRADE_RESPONSE_RESERVED_LENGTH sizeof(char)

#define NSE_TRADE_RESPONSE_ACCOUNTNUMBER_OFFSET \
  (NSE_TRADE_RESPONSE_RESERVED_OFFSET + NSE_TRADE_RESPONSE_RESERVED_LENGTH)
#define NSE_TRADE_RESPONSE_ACCOUNTNUMBER_LENGTH LENGTH_OF_NSE_TRADE_RESPONSE_ACCOUNTNUMBER_CHAR_FIELD

#define NSE_TRADE_RESPONSE_BUYSELLINDICATOR_OFFSET \
  (NSE_TRADE_RESPONSE_ACCOUNTNUMBER_OFFSET + NSE_TRADE_RESPONSE_ACCOUNTNUMBER_LENGTH)
#define NSE_TRADE_RESPONSE_BUYSELLINDICATOR_LENGTH sizeof(int16_t)

#define NSE_TRADE_RESPONSE_ORIGINALVOLUME_OFFSET \
  (NSE_TRADE_RESPONSE_BUYSELLINDICATOR_OFFSET + NSE_TRADE_RESPONSE_BUYSELLINDICATOR_LENGTH)
#define NSE_TRADE_RESPONSE_ORIGINALVOLUME_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_DISCLOSEDVOLUME_OFFSET \
  (NSE_TRADE_RESPONSE_ORIGINALVOLUME_OFFSET + NSE_TRADE_RESPONSE_ORIGINALVOLUME_LENGTH)
#define NSE_TRADE_RESPONSE_DISCLOSEDVOLUME_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_REMAININGVOLUME_OFFSET \
  (NSE_TRADE_RESPONSE_DISCLOSEDVOLUME_OFFSET + NSE_TRADE_RESPONSE_DISCLOSEDVOLUME_LENGTH)
#define NSE_TRADE_RESPONSE_REMAININGVOLUME_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET \
  (NSE_TRADE_RESPONSE_REMAININGVOLUME_OFFSET + NSE_TRADE_RESPONSE_REMAININGVOLUME_LENGTH)
#define NSE_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_PRICE_OFFSET \
  (NSE_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_OFFSET + NSE_TRADE_RESPONSE_DISCLOSEDVOLUMEREMAINING_LENGTH)
#define NSE_TRADE_RESPONSE_PRICE_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_STORDERFLAGS_STRUCT_OFFSET \
  (NSE_TRADE_RESPONSE_PRICE_OFFSET + NSE_TRADE_RESPONSE_PRICE_LENGTH)
#define NSE_TRADE_RESPONSE_STORDERFLAGS_STRUCT_LENGTH sizeof(int16_t)

#define NSE_TRADE_RESPONSE_GOODTILLDATE_OFFSET \
  (NSE_TRADE_RESPONSE_STORDERFLAGS_STRUCT_OFFSET + NSE_TRADE_RESPONSE_STORDERFLAGS_STRUCT_LENGTH)
#define NSE_TRADE_RESPONSE_GOODTILLDATE_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_FILLNUMBER_OFFSET \
  (NSE_TRADE_RESPONSE_GOODTILLDATE_OFFSET + NSE_TRADE_RESPONSE_GOODTILLDATE_LENGTH)
#define NSE_TRADE_RESPONSE_FILLNUMBER_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_FILLQUANTITY_OFFSET \
  (NSE_TRADE_RESPONSE_FILLNUMBER_OFFSET + NSE_TRADE_RESPONSE_FILLNUMBER_LENGTH)
#define NSE_TRADE_RESPONSE_FILLQUANTITY_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_FILLPRICE_OFFSET \
  (NSE_TRADE_RESPONSE_FILLQUANTITY_OFFSET + NSE_TRADE_RESPONSE_FILLQUANTITY_LENGTH)
#define NSE_TRADE_RESPONSE_FILLPRICE_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_VOL_FILLED_TODAY_OFFSET \
  (NSE_TRADE_RESPONSE_FILLPRICE_OFFSET + NSE_TRADE_RESPONSE_FILLPRICE_LENGTH)
#define NSE_TRADE_RESPONSE_VOL_FILLED_TODAY_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_ACTIVITY_TYPE_OFFSET \
  (NSE_TRADE_RESPONSE_VOL_FILLED_TODAY_OFFSET + NSE_TRADE_RESPONSE_VOL_FILLED_TODAY_LENGTH)
#define NSE_TRADE_RESPONSE_ACTIVITY_TYPE_LENGTH 2

#define NSE_TRADE_RESPONSE_ACTIVITY_TIME_OFFSET \
  (NSE_TRADE_RESPONSE_ACTIVITY_TYPE_OFFSET + NSE_TRADE_RESPONSE_ACTIVITY_TYPE_LENGTH)
#define NSE_TRADE_RESPONSE_ACTIVITY_TIME_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_TOKENNUM_OFFSET \
  (NSE_TRADE_RESPONSE_ACTIVITY_TIME_OFFSET + NSE_TRADE_RESPONSE_ACTIVITY_TIME_LENGTH)
#define NSE_TRADE_RESPONSE_TOKENNUM_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET \
  (NSE_TRADE_RESPONSE_TOKENNUM_OFFSET + NSE_TRADE_RESPONSE_TOKENNUM_LENGTH)
#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH \
  LENGTH_OF_NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_CHAR_FIELD

#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET      \
  (NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET + \
   NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH)
#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH \
  LENGTH_OF_NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_CHAR_FIELD

#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET \
  (NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET + NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH)
#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET \
  (NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET +     \
   NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_LENGTH)
#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET \
  (NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET +   \
   NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_LENGTH)
#define NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH 2

#define NSE_TRADE_RESPONSE_OPENCLOSE_OFFSET                    \
  (NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET + \
   NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH)
#define NSE_TRADE_RESPONSE_OPENCLOSE_LENGTH sizeof(char)

#define NSE_TRADE_RESPONSE_BOOK_TYPE_OFFSET (NSE_TRADE_RESPONSE_OPENCLOSE_OFFSET + NSE_TRADE_RESPONSE_OPENCLOSE_LENGTH)
#define NSE_TRADE_RESPONSE_BOOK_TYPE_LENGTH sizeof(char)

#define NSE_TRADE_RESPONSE_PARTICIPANT_OFFSET \
  (NSE_TRADE_RESPONSE_BOOK_TYPE_OFFSET + NSE_TRADE_RESPONSE_BOOK_TYPE_LENGTH)
#define NSE_TRADE_RESPONSE_PARTICIPANT_LENGTH LENGTH_OF_NSE_TRADE_RESPONSE_PARTICIPANT_CHAR_FIELD

#define NSE_TRADE_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_OFFSET \
  (NSE_TRADE_RESPONSE_PARTICIPANT_OFFSET + NSE_TRADE_RESPONSE_PARTICIPANT_LENGTH)
#define NSE_TRADE_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_LENGTH sizeof(int8_t)

#define NSE_TRADE_RESPONSE_PAD_OFFSET \
  (NSE_TRADE_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_OFFSET + NSE_TRADE_RESPONSE_ADDITIONALORDERFLAGS_STRUCT_LENGTH)
#define NSE_TRADE_RESPONSE_PAD_LENGTH sizeof(int8_t)

#define NSE_TRADE_RESPONSE_PAN_OFFSET (NSE_TRADE_RESPONSE_PAD_OFFSET + NSE_TRADE_RESPONSE_PAD_LENGTH)
#define NSE_TRADE_RESPONSE_PAN_LENGTH 10

#define NSE_TRADE_RESPONSE_ALGOID_OFFSET (NSE_TRADE_RESPONSE_PAN_OFFSET+NSE_TRADE_RESPONSE_PAN_LENGTH) 
#define NSE_TRADE_RESPONSE_ALGOID_LENGTH sizeof(int32_t)

#define NSE_TRADE_RESPONSE_RESERVEDFILLER_OFFSET (NSE_TRADE_RESPONSE_ALGOID_OFFSET+NSE_TRADE_RESPONSE_ALGOID_LENGTH)
#define NSE_TRADE_RESPONSE_RESERVEDFILLER_LENGTH sizeof(int16_t)

#define NSE_TRADE_RESPONSE_LASTACTIVITYREFERENCE_OFFSET ( NSE_TRADE_RESPONSE_RESERVEDFILLER_OFFSET+NSE_TRADE_RESPONSE_RESERVEDFILLER_LENGTH)
#define NSE_TRADE_RESPONSE_LASTACTIVITYREFERENCE_LENGTH sizeof(int64_t)

#define NSE_TRADE_RESPONSE_LENGTH \
  (NSE_TRADE_RESPONSE_LASTACTIVITYREFERENCE_OFFSET + NSE_TRADE_RESPONSE_LASTACTIVITYREFERENCE_LENGTH + 52)

namespace HFSAT {
namespace NSE {

/*
 * Defines Trade confirmation semantics for Derivatives market
 * Extends generic  TradeConfirmationResponse  template for NSE trimmed structure.
 */

class TradeConfirmationResponseDerivatives : public TradeConfirmationResponse {
 public:
  inline ProcessedTradeConfirmationResponse* ProcessTradeConfirmationResponse(const char* msg_ptr) {
    memcpy((void*)processed_trade_conf_response_.instrument_name,
           (void*)(msg_ptr + NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_OFFSET),
           NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_INSTRUMENTNAME_LENGTH);

    memcpy((void*)processed_trade_conf_response_.symbol,
           (void*)(msg_ptr + NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_OFFSET),
           NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_SYMBOL_LENGTH);

    memcpy((void*)processed_trade_conf_response_.option_type,
           (void*)(msg_ptr + NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_OFFSET),
           NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_OPTIONTYPE_LENGTH);

    processed_trade_conf_response_.expiry_date =
        ntoh32(*((int32_t*)(msg_ptr + NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_EXPIRYDATE_OFFSET)));

    processed_trade_conf_response_.strike_price =
        ntoh32(*((int32_t*)(msg_ptr + NSE_TRADE_RESPONSE_CONTRACT_DESC_STRUCT_STRIKEPRICE_OFFSET)));

    processed_trade_conf_response_.order_number =
        ntoh64((*((int64_t*)(msg_ptr + NSE_TRADE_RESPONSE_ORDER_NUM_OFFSET))));

    processed_trade_conf_response_.price = ntoh32(*((int32_t*)(msg_ptr + NSE_TRADE_RESPONSE_FILLPRICE_OFFSET)));

    processed_trade_conf_response_.size_executed =
        ntoh32(*((int32_t*)(msg_ptr + NSE_TRADE_RESPONSE_FILLQUANTITY_OFFSET)));

    processed_trade_conf_response_.size_remaining =
        ntoh32(*((int32_t*)(msg_ptr + NSE_TRADE_RESPONSE_REMAININGVOLUME_OFFSET)));

    processed_trade_conf_response_.buy_sell =
        ntoh16(*((int16_t*)(msg_ptr + NSE_TRADE_RESPONSE_BUYSELLINDICATOR_OFFSET)));

    processed_trade_conf_response_.token = ntoh32(*((int32_t*)(msg_ptr + NSE_TRADE_RESPONSE_TOKENNUM_OFFSET)));
    processed_trade_conf_response_.activity_time =
        ntoh32(*((int32_t*)(msg_ptr + NSE_TRADE_RESPONSE_ACTIVITY_TIME_OFFSET)));
    processed_trade_conf_response_.last_activity_reference = 
        ntoh64(*((int64_t *)(msg_ptr + NSE_TRADE_RESPONSE_LASTACTIVITYREFERENCE_OFFSET)));
    return &processed_trade_conf_response_;
  }
};
}
}
